### ISSUE TITLE
error after click [Comfirm Swap]: The method eth_sendTransaction does not exist/is no available

### ISSUE THREAD

**Issue by PokimLee** [Uniswap/uniswap-interface#1000]
**Bug Description**
I've pull the latest version(v2.4.1) and build the interface up. But when I click the  [Comfirm Swap], there occurs a error says: The method eth_sendTransaction does not exist/is no available

**Steps to Reproduce**
1.click [Comfirm Swap]

**Expected Behavior**

**Additional Context**
![image](https://user-images.githubusercontent.com/3247265/88388783-c5ecee80-cde7-11ea-959f-94085888d43e.png)

**Comment by moodysalem** [comment]
probably related to upgrading ethers.js from beta to 5.0.x between uniswap interface versions 2.4.1 and 2.3.2
https://github.com/WalletConnect/walletconnect-monorepo/issues/309
diff
https://github.com/Uniswap/uniswap-interface/compare/v2.3.2...v2.4.1

thanks for the report! we will fix this before we deploy this version to app.uniswap.org

**Comment by moodysalem** [comment]
should be fixed in tomorrow's release/master
