### ISSUE TITLE
Add liquidity to pool failed

### ISSUE THREAD

**Issue by pres87** [Uniswap/uniswap-interface#1002]
I tried multiple times to add liquidity to ETH-AMPL pool, which keeps failing.
Error message on Etherscan is:
Fail with error 'UniswapV2Router: INSUFFICIENT_A_AMOUNT

I have certainly enough ETH/AMPL amount.
Here's three hashes of these failed transactions:
0x3c362191017db126350a53d59da96881aca447bb81c5d20f15f51dff8a434009

0x27897e47719c6e7bc01f850a47f8627576171bdd13b9b941e1525eced6de278a

0x60d97c282ed47bc561f287b0c0db2f873a1ecc15811db504e447bcb8aa3e8d5b

Keep losing fees, I'm gonna give up.
Tried from mobile and desktop, with same result.
What is the problem here?

**Comment by moodysalem** [comment]
It means the price moved between the time you submitted the transaction and when it was mined. You can try again, and I recommend setting a higher gas price and increasing slippage tolerance. Please ask these questions in the discord.
