### ISSUE TITLE
Add liquidity

### ISSUE THREAD

**Issue by Cjohnson66** [Uniswap/uniswap-interface#1003]
Tried to add to te ETH/AMPL pool and got the following error
Fail with error 'UniswapV2Router: INSUFFICIENT_A_AMOUNT'

There was both ETH and AMPL in the attached Metamask wallet

Transaction Hash is
0xa8221e6b8abc105ae9c8421e33a42e07ff8e1dc137e6de41b538b26adbbefd9b
and
0x0b9f08ae01a9d084d610c94d68bc3f3dea7de7b186a332c8e2f46452dce5c26c

Two attempts made

**Additional Context**
Add any other context about the problem here (screenshots, whether the bug only occurs only in certain mobile/desktop/browser environments, etc.)

**Comment by moodysalem** [comment]
It means the price moved between the time you submitted the transaction and when it was mined. You have to try again, and I recommend setting a higher gas price and increasing slippage tolerance. Please ask these questions in the discord.
