### ISSUE TITLE
uniswapv2router: insufficient_output_amount

### ISSUE THREAD

**Issue by ace716** [Uniswap/uniswap-interface#1004]
I used‘ uniswapv2 exchange’ to convert 6000 ampl to eth with Coinbase wallet , and this error was reported: uniswapv2router: insufficient_output_amount

Transaction Hash:
0x3875cfccf9df36f72fea87ae95bb34206aac7d9f7b59fc140ecf05dfa54208a8 
Status:
Fail with error 'UniswapV2Router: INSUFFICIENT_OUTPUT_AMOUNT'
Block:
10542010 360 Block Confirmations
Timestamp:
1 hr 25 mins ago (Jul-27-2020 02:06:02 PM +UTC)
From:
0xfe0984c3502a1033c74c5d4756ffd221da15d648 
To:
Contract 0x7a250d5630b4cf539739df2c5dacb4c659f2488d (Uniswap V2: Router 2)  
 Warning! Error encountered during contract execution [Reverted] 

Now my exchange is down here
Email:ace.stark@outlook.com

**Comment by moodysalem** [comment]
It means the price moved between the time you submitted the transaction and when it was mined. You can try again, and I recommend setting a higher gas price and/or increasing slippage tolerance in the settings menu. Please ask these questions in the discord.
