### ISSUE TITLE
v1 expiration not set to infinity

### ISSUE THREAD

**Issue by wjmelements** [Uniswap/uniswap-interface#1006]
**Bug Description**
V1 orders can fail because of expiration, taking all gas.
There used to be an advanced setting for this but now it is gone.

**Steps to Reproduce**
1. Set gasprice to 39 gwei (or current safeLow) on v1 swap
2. Wait for confirmation
3. Reverted

**Expected Behavior**
The transaction should not revert

**Additional Context**
Since v1 eats all of your gas on revert you want it to attempt the trade no matter what, which means setting an infinite expiration. I recommend 0xff0000..00 because of txdatazero.

**Comment by moodysalem** [comment]
The setting is not gone, it's in the settings menu
![image](https://user-images.githubusercontent.com/7897876/88599675-f1631980-d031-11ea-9dba-dc2e5662b16d.png)

**Comment by wjmelements** [comment]
Okay, but as mentioned in the title it is not infinity.

**Comment by moodysalem** [comment]
Why is 9999999 not sufficient?

**Comment by wjmelements** [comment]
@moodysalem It costs more gas to use nonzero bytes than zero bytes, as mentioned in the description.

**Comment by wjmelements** [comment]
Search "txdatazero" in the [yellow paper](https://ethereum.github.io/yellowpaper/paper.pdf).

**Comment by moodysalem** [comment]
Zero deadline against a v1 exchange will always fail, unless I'm missing something
https://github.com/Uniswap/uniswap-v1/blob/master/contracts/uniswap_exchange.vy#L168
You would need to pass the maximum uint256 value to get the equivalent of an 'infinite' deadline
And from the yellow paper, afaict it saves 64 gas for V1 swaps only (nonzero vs zero). I don't think the Uniswap V1 interface even allowed you to set infinite deadline?

**Comment by wjmelements** [comment]
@moodysalem see description

> I recommend 0xff0000..00 because of txdatazero.

**Comment by wjmelements** [comment]
> I don't think the Uniswap V1 interface even allowed you to set infinite deadline?
any deadline after the heat death of the universe can be considered "infinite"
