### ISSUE TITLE
Default slippage settings empower front-running

### ISSUE THREAD

**Issue by wjmelements** [Uniswap/uniswap-interface#1007]
**Bug Description**
It is [extremely profitable](https://etherscan.io/address/0xc3ca90684fd7b8c7e4be88c329269fc32111c4bd
) to front-run transactions issued from this interface. There is no way to limit slippage anymore.

**Steps to Reproduce**
Trade 1000 ETH for DAI, lose all of the allowed slippage

**Expected Behavior**
Nobody can front-run you without reverting your transaction.
Allow me to configure it or set a much lower default, perhaps one that isn't a percentage of the input.

**Additional Context**
v1 was way better than v2. v2 is for bots.

**Comment by moodysalem** [comment]
You can configure it, it's in the settings menu. The default is 0.5% as it was in the Uniswap V1 interface.

**Comment by wjmelements** [comment]
This is a huge improvement because it retains my preferences. Thanks.
