### ISSUE TITLE
Fail with error "UniswapV2Router: Insufficient_A_amount"

### ISSUE THREAD

**Issue by julian-barker** [Uniswap/uniswap-interface#1013]
I am trying to add liquidity to the ETH-AMPL pool and getting this error message.

Transaction Hash: 0x105e1d223807b7e92c4fd582aa0060f60efd75227dd3db26eaedcc2489ce7067

**Comment by tr007008** [comment]
I'm having the  same problem.  Have failed three times so far.  Is there any point in continuing?

I contributed to this pool (successfully)  about 12 hrs ago.  Could it be that I'm using the same addresses as the previous time?  Should I be using all new addresses?

**Comment by moodysalem** [comment]
You can increase your slippage tolerance (settings button, top right) and gas price. This will give your transaction a better chance of being included before the price moves too much.

**Comment by tr007008** [comment]
That did the trick!! Awesome! thanks for the help!
