### ISSUE TITLE
Can't remove liquidity for UDOO-ETH pair

### ISSUE THREAD

**Issue by Ikabott-MRM** [Uniswap/uniswap-interface#1014]
**Bug Description**
I'm trying to remove liquity for my ETH-UDOO pair
Approval goes ok.  Confirm button does nothing. 

**Steps to Reproduce**
1. Go to Pool - Remove liquidity - 100% - Approve - Confirm
2. Nothing Happens!
...

**Expected Behavior**
The transaction for removing liquidity to be sent

**Additional Context**
I tried different browsers, both on mobile an laptop. 
I tried removing 50% and 100% liquidity
I tried both "receive ETH" and "receive WETH"
I tried removing less uni-v2 token.
Nothing works :(

My Wallet Address
0x652164D5FD53D1f7eaE245FF9545cC9F4888A400

Thanks in advance!

![Remove Liquidity](https://user-images.githubusercontent.com/68831287/88913184-d0b7e100-d236-11ea-9b7c-f2c077ee2df7.png)
![Confirm Button](https://user-images.githubusercontent.com/68831287/88913193-d4e3fe80-d236-11ea-940a-05b961d4d44c.png)

**Comment by Ikabott-MRM** [comment]
Browser Console shows:
index.tsx:282 estimateGas failed for removeLiquidityETHWithPermitSupportingFeeOnTransferTokens TypeError: Cannot read property '_hex' of undefined
    at Function.value (bignumber.ts:236)
    at r.<anonymous> (base-provider.js:584)
    at c (runtime.js:63)
    at Generator._invoke (runtime.js:293)
    at Generator.next (runtime.js:118)
    at o (base-provider.js:5)

**Comment by moodysalem** [comment]
It seems like it's an always failing transaction, uDOO is not verified on Etherscan so I can't say what's preventing the remove liquidity.

Tracking the UX improvement in #872

**Comment by Ikabott-MRM** [comment]
I'm not an expert, so maybe I', wrong, but I see udoo token address listed here on etherscan

https://etherscan.io/token/0x12f649a9e821f90bb143089a6e56846945892ffb

**Comment by moodysalem** [comment]
Verified means the code is public for me to read it and see what's going on

You can try an older release to see if it works, but I don't think it will
https://cloudflare-ipfs.com/ipfs/QmXWAQkFd2GRBoQh8eSvXRQuWYG8cqdFcZo8RnwMNnbUuE/#/swap

**Comment by Ikabott-MRM** [comment]
Thank you, and Sorry if I go off topic, but what should I do to get my tokens back to my wallet?

**Comment by moodysalem** [comment]
If the older version doesn't work, I would reach out to uDOO support channel

**Comment by Ikabott-MRM** [comment]
Same result.  I'll try to reach them.  Wish me luck.
