### ISSUE TITLE
Uniswap "Connect Smart Wallet" On Mac OS Failure Error

### ISSUE THREAD

**Issue by CryptoFox226** [Uniswap/uniswap-interface#1017]
**Bug Description**
When trying to connect any smart wallet to Uniswap on Mac OS, a fatal error occurs and a "Try again" button appears immediately, and cannot progress past this. This bug got progressively worse, noticed about 7pm PCT. Prior, the wallet would connect and the transaction would be confirmed in the wallet, however the transaction would stay "Pending" with no progress. You could manually confirm the transaction multiple times in V1 of uniswap, however no progress will be made. As of now on Mac OS I cannot connect a smart wallet to either uniswap version.

**Steps to Reproduce**
1. Go to Connect Wallet 
2. Click on Wallet Connect option
3. The error should appear and no refresh will help the page move and function normally. 
...

**Expected Behavior**
After clicking connect smart wallet from the wallet options, the window will open and close right away telling you to try again. No attempt can made to actually try to connect. No QR code will appear, only a "try again" button.

**Additional Context**
Uniswap seems to have trouble communicating with smart wallets at this time. As prior to this, it was connecting and working as expected. Within hours, it would connect, but bug out, and not complete transactions, regardless of approval of contract, or auto approval, despite there being sufficient funds.

**Comment by moodysalem** [comment]
What browser are you using?

**Comment by moodysalem** [comment]
Need more info, can't reproduce on MacOS with argent/trustwallet

**Comment by CryptoFox226** [comment]
It’s on Safari. It worked at some point but now it won’t work at all. On
IOS using safari it sort of works but my friend using android and windows
is having issues as well.

**Comment by CryptoFox226** [comment]
Simply hitting connect wallet and selecting wallet select results in this
screen right away, no loading times.

**Comment by CryptoFox226** [comment]
My mistake, Connecting to wallet, then selecting “wallet connect” in safari

**Comment by hydrogenbond007** [comment]
Facing this issue on MacOS on Brave browser, have gone through a few resources unable to figure out
