### ISSUE TITLE
Making NUG searchable 

### ISSUE THREAD

**Issue by DomGilmore** [Uniswap/uniswap-interface#1018]
Hello - we added our token to Uniswap just over 60 days ago - https://uniswap.info/pair/0xeab7e907e01203bf0b823dbe135b151921b74568

We would like NUG to be searchable in the interface and appear in the drop down menu, rather than users have to paste the contract address each time.

Please let me know if you require any additional information.

Thanks,
Dom.

**Comment by moodysalem** [comment]
https://github.com/Uniswap/uniswap-interface#listing-a-token
