### ISSUE TITLE
error in transaction and no re-funding

### ISSUE THREAD

**Issue by roninkaizen** [Uniswap/uniswap-interface#1025]
**Bug Description**
https://etherscan.io/tx/0xf91d4212bd4dc344da054f2ed2f620914bb1c533bbc2bb36b838f35ffcaa5907
the exchange of DAi into "rsr"
which failed.

**Expected Behavior**
a swap- DAI against "rsr"

**Additional Context**
swapping is nothing new to me, 
it worked with several other token,
i kindly ask where the "intraded and approove Dai now are" and how to claim the back,
because the transfer itself did not happen,
what is visible from the transaction.

reachable via gitter, riot, discord

**Comment by moodysalem** [comment]
Ask in support channel on discord, I do not understand the question.
