### ISSUE TITLE
"Unexpected Error, Contact Support" (preventing me from trading while prices are moving against me!)

### ISSUE THREAD

**Issue by ApopheniaPays** [Uniswap/uniswap-interface#1027]
**Bug Description**
For the past hour, from both firefox and chrome, every time I try to swap I get "Unexpected error, please try again or contact support"

**Steps to Reproduce**
1. Set up any swap.
2. Hit "Swap"
3. On confirmation popup, hit "Confirm"
4. Error pops up, telling me to "try again or contact support"
5. Waste a ton of my time searching for "support", which doesn't actually exist
6. Lose money by being unable to execute swaps while price moves drastically against me the whole time I'm engaged in this exercise
6. Throw up my hands and wonder why I'd ever trust financial transactions to a dApp when this is the kind of results I can expect

**Expected Behavior**
1. Metamask window opens normally to confirm swap.
2. If there is an error, be told what it is and what steps to take to resolve it.
3. Not be told to "contact support" if there is no support. 

**Additional Context**
Tried from two different browsers on MacOS. Tried resetting Metamask. Tried restarting my browsers. None made a difference. 
![image](https://user-images.githubusercontent.com/62907112/89700153-ad4d0000-d8e0-11ea-8b7d-a846f4876c03.png)

**Comment by gr8blondino** [comment]
Hello. I seem to have exactly the same issue all day today...
![image](https://user-images.githubusercontent.com/23213295/89734573-da222400-da54-11ea-9041-e3309abbd241.png)

Any suggestions?
Cheers

**Comment by moodysalem** [comment]
If you see this error, it probably is for a swap of a fee-on-transfer token.
Try these things to get the swap through, while I work on improving the error message.
- Increase slippage
- Only specify an input amount, not the output

**Comment by gr8blondino** [comment]
Thanks for that,

I have tried that already. it looks like uniswap stopped talking to
Metamask. I would expect a prompt to confirm the transaction. I had no
problem like this in the past. This only started today.
Any other suggestions

Thanks.

Regards
Raf Ivo Jarzebski

**Comment by hollon21** [comment]
For what it's worth, it's doing the same to me whenever I try to buy AMPL with USDT

**Comment by ghitchman** [comment]
I'm getting the same error across multiple token pairs

**Comment by moodysalem** [comment]
AMPL/X issue has been fixed (issue is that USDT/AMPL and USDC/AMPL pairs were being used in routing, however the rebase `sync()` has not been called on those pairs because it is not supported by AMPL, so now we only consider DAI and ETH when swapping with AMPL)

For other specific tokens, please post the exact error and token address

**Comment by hollon21** [comment]
Thanks for letting me know! It was just the AMPL/USDT pairs that I was having problems with but I think other people were having problems with other tokens

 
 

Sent: Tuesday, August 11, 2020 at 5:03 PM
