### ISSUE TITLE
Shortcut to add Token to Metamask

### ISSUE THREAD

**Issue by 2ge** [Uniswap/uniswap-interface#1028]
Would be great if user have possibility to add desired token which he is swapping directly to metamask, now it is like 6 clicks with copy and paste away, can be done in 2 clicks...

not sure if this is possible, but would be great also for other wallets.

**Comment by moodysalem** [comment]
@danfinlay this would require an addition to the MetaMask Ethereum API, perhaps another RPC method `metamask_addToken` with a single parameter, token address

**Comment by 2ge** [comment]
please check https://github.com/estebanmino/EIPs/blob/master/EIPS/eip-747.md - this is implemented and maybe right place to start.
