### ISSUE TITLE
Fail with error 'UniswapV2Router: EXCESSIVE_INPUT_AMOUNT'

### ISSUE THREAD

**Issue by thatguynz92** [Uniswap/uniswap-interface#1031]
**Bug Description**
Went to swap ETH to DOS Network Token. Nothing out of the ordinary. Has spat back the same error 3 times on etherscan and gas fees are adding up. 

**Steps to Reproduce**
1. Go to https://app.uniswap.org/ and try to swap ETH for DOS
2. Complete transaction (even with highest gas fee)
3. Wait for confirmation on Etherscan
4. TXN fails due to above error

**Expected Behavior**
Expected transaction to be confirmed and not failed.

**Additional Context**

Desktop
Latest version of METAMASK.
Windows 10

**Comment by moodysalem** [comment]
This is normal. Uniswap is protecting you from getting a worse price than what you saw. The gas fees for a failed swap are lower than a successful swap.
