### ISSUE TITLE
Approvals for some tokens cannot be sent if an existing approval is non-zero and insufficient

### ISSUE THREAD

**Issue by lismanown** [Uniswap/uniswap-interface#1034]
**Bug Description**
```
inpage.js:1 MetaMask - RPC Error: gas required exceeds allowance (12480476) or always failing transaction 
Object
    code: -32000
    message: "gas required exceeds allowance (12480476) or always failing transaction"
    __proto__: Object
```

**Steps to Reproduce**
1. Go to https://app.uniswap.org/#/add/ETH/0x1C83501478f1320977047008496DACBD60Bb15ef
2. Choose ETH and DGTX (token address is 0x1c83501478f1320977047008496dacbd60bb15ef)
3. Choose ratios and click "Supply", nothing happens
4. The above error will show on developer console

**Expected Behavior**
Should provide liquidity

**Additional Context**
This is happening with uniswap and metamask on chrome browser. Already tried the same steps on trustwallet but when I click to provide liquidity, nothing happens on the trustwallet app also

**Comment by moodysalem** [comment]
This ERC223 will not work with Uniswap because it requires the contract fallback on transfer to succeed, which Uniswap V2 does not handle.

**Comment by bneiluj** [comment]
It's also for ERC20 tokens. 

For example, If ETH / USDT (`https://app.uniswap.org/#/add/ETH/0xdAC17F958D2ee523a2206206994597C13D831ec7`) was approved with max $1k USDT and liquidity was correctly added then trying to add more liquidity by approving a larger amount of USDT to be added will fail. 

<img width="753" alt="Screenshot 2020-09-15 at 23 57 08" src="https://user-images.githubusercontent.com/3680497/93269438-42c89300-f7af-11ea-8456-ff0d67e7696d.png">

**Comment by educoin** [comment]
Same issue here: 
Trying to add liquidity to https://app.uniswap.org/#/add/ETH/0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984
UNI token approved
Push on the Confirm Supply botton
Nothing happens 
Error in the console: 
{code: -32000, message: "gas required exceeds allowance (12426580) or always failing transaction"}
code: -32000
message: "gas required exceeds allowance (12426580) or always failing 

Using Chrome and Brave browser and MetaMask Version
8.0.8

**Comment by moodysalem** [comment]
This error can happen for a variety of reasons, including that the interface is not synced with the latest block and the state has changed (eg price movement) in such a way that the transaction constructed based on the previous block state will never succeed.

Recommend you create a new issue describing repro steps of your bug @bneiluj

@educoin your issue sounds like it might be related to the Argent walletconnect issues in the interface

**Comment by educoin** [comment]
@moodysalem I don't use Argent walletconnect. I have tried with other pools and i have the same issue. The swapping works perfect, but the add liquidity to any pool doesn't work.

**Comment by zhangweis** [comment]
> It's also for ERC20 tokens.
> 
> For example, If ETH / USDT (`https://app.uniswap.org/#/add/ETH/0xdAC17F958D2ee523a2206206994597C13D831ec7`) was approved with max $1k USDT and liquidity was correctly added then trying to add more liquidity by approving a larger amount of USDT to be added will fail.
> 
> <img alt="Screenshot 2020-09-15 at 23 57 08" width="753" src="https://user-images.githubusercontent.com/3680497/93269438-42c89300-f7af-11ea-8456-ff0d67e7696d.png">

Same here. Approved some amount like 5000 USDT and used about 4800. Then trying to add more liquidity, clicking "Approve USDT" button but failed with console messages {code: -32000, message: "gas required exceeds allowance (12499941) or always failing transaction"}

**Comment by moodysalem** [comment]
> > It's also for ERC20 tokens.
> > For example, If ETH / USDT (`https://app.uniswap.org/#/add/ETH/0xdAC17F958D2ee523a2206206994597C13D831ec7`) was approved with max $1k USDT and liquidity was correctly added then trying to add more liquidity by approving a larger amount of USDT to be added will fail.
> > <img alt="Screenshot 2020-09-15 at 23 57 08" width="753" src="https://user-images.githubusercontent.com/3680497/93269438-42c89300-f7af-11ea-8456-ff0d67e7696d.png">
> 
> Same here. Approved some amount like 5000 USDT and used about 4800. Then trying to add more liquidity, clicking "Approve USDT" button but failed with console messages {code: -32000, message: "gas required exceeds allowance (12499941) or always failing transaction"}

I suspect the issue may be that trying to send an approve with an existing approval for some tokens fails (to avoid a well known ERC20 specification issue of an approval being frontrun by the spender). The workaround may be to remove the approval for USDT to the router and then try again

@NoahZinsmeister @callil

**Comment by moodysalem** [comment]
Confirmed this is an issue with USDT
```
        // To change the approve amount you first have to reduce the addresses`
        //  allowance to zero by calling `approve(_spender, 0)` if it is not
        //  already 0 to mitigate the race condition described here:
        //  https://github.com/ethereum/EIPs/issues/20#issuecomment-263524729
        require(!((_value != 0) && (allowed[msg.sender][_spender] != 0)));```

**Comment by wjmelements** [comment]
It's also an issue with CRV and SWRV

**Comment by cagansevencan** [comment]
Same issue occurred when I was trying to remove liquidity CORE/ETH.

**Comment by jayaliceanyc** [comment]
I'm having this same issue when trying to remove liquidity from AMPL/aDAI pool. I can sign the approval, click remove, then try to click confirm and it does nothing. This is the only pool I am having an issue removing liquidity from.

**Comment by moodysalem** [comment]
> I'm having this same issue when trying to remove liquidity from AMPL/aDAI pool. I can sign the approval, click remove, then try to click confirm and it does nothing. This is the only pool I am having an issue removing liquidity from.

This is totally unrelated. Most likely AMPL rebased and the pool is not synced.

Related to https://github.com/Uniswap/uniswap-interface/issues/1196
We may want some UI to allow users to control their approvals generally in the interface.
