### ISSUE TITLE
transactions keep failing

### ISSUE THREAD

**Issue by masadsaeed** [Uniswap/uniswap-interface#1038]
0x72dd11bd333640678339528b682552c3c6421fc7a024f1ca986702742c74b6a4

0xd5a192bb75d4428c91c1ef6ccb493816039c968c60b0b03b799630d304162802

0x165f398f438bbbc259e0b4c90cbb8f6c884ef4fbff08c5983e617e3dd7065341

**Comment by moodysalem** [comment]
All errors are simply due to price increases. Increase slippage amount if you want the trade to go through at a worse price.

**Comment by masadsaeed** [comment]
> All errors are simply due to price increases. Increase slippage amount if you want the trade to go through at a worse price.

Is 2% slippage enough? I'm paying fast gas as well

**Comment by masadsaeed** [comment]
> All errors are simply due to price increases. Increase slippage amount if you want the trade to go through at a worse price.

4% slippage still FAILED !!

0xc37969601c70d7e5ff3411e2c8e1ea64d9fe69604dce3131149b199c64362966

loosing crypto :(

**Comment by moodysalem** [comment]
Please ask in the discord
