### ISSUE TITLE
Adding $CAT logo on Uniswap

### ISSUE THREAD

**Issue by mycattoken** [Uniswap/uniswap-interface#1041]
Hello,

We are looking to have our logo added on Uniswap to make it easier for our community to find us. Also, it makes it easier for people to know it's us and not someone impersonating the token. 

Thank you
![Circle (1)](https://user-images.githubusercontent.com/69594644/90040318-ce717000-dc95-11ea-825c-46f1cda32b19.png)

**Comment by moodysalem** [comment]
https://github.com/Uniswap/uniswap-interface#listing-a-token
