### ISSUE TITLE
Disallow sending the result of a swap to bad addresses (e.g. router, pairs, tokens)

### ISSUE THREAD

**Issue by moodysalem** [Uniswap/uniswap-interface#1043]

**Comment by zbgapi** [comment]
谁能帮忙解答一下，我添加zt币之后， add Liquidity一直不起作用，create pool&  supply 后 为什么总没反应，到底需要怎样  issue 
 & pull request  呢

**Comment by zbgapi** [comment]
谁能帮忙解答一下，我添加zt币之后， add Liquidity一直不起作用，create pool& supply 后 为什么总没反应，到底需要怎样 issue
& pull request 呢   我的联系方式是zbgvip@126.com , 非常感谢
