### ISSUE TITLE
Fail with error 'UniswapV2Router: INSUFFICIENT_A_AMOUNT'

### ISSUE THREAD

**Issue by Fluxvain** [Uniswap/uniswap-interface#1044]
I tried adding liquidity to a pool, and got a failure with the above message.

this is the etherscan link: 
[https://etherscan.io/tx/0xb35d540a898e3172b370e006324e5e82c41ba7a3705f58df23ef04b20285cd03](url)

It states reverted , but the ETH is still gone from my wallet.  (coinbase wallet)

Contract 0x7a250d5630b4cf539739df2c5dacb4c659f2488d (Uniswap V2: Router 2) 
 Warning! Error encountered during contract execution [Reverted] 

I would like to know how i can get my ETH back to my wallet?

Thx

**Comment by moodysalem** [comment]
The transaction reverted resulting in no state change. Please ask support questions in discord.
