### ISSUE TITLE
Fail with error 'UniswapV2Router: INSUFFICIENT_B_AMOUNT'

### ISSUE THREAD

**Issue by Lorenzomat** [Uniswap/uniswap-interface#1045]
I tried adding liquidity, and got a failure with the above message. Tried again with higher gas, got same result. Cannot find anything googling the exact string.

What am I doing wrong?

**Comment by moodysalem** [comment]
This means the price moved after you submitted the transaction. If you wish to have the swap/add liquidity/remove liquidity execute regardless of the price, increase your slippage tolerance.
Please ask your questions in the discord.
