### ISSUE TITLE
10buks gas lost, remove liquidity: Fail with error 'UniswapV2Router: INSUFFICIENT_A_AMOUNT'

### ISSUE THREAD

**Issue by camenlx** [Uniswap/uniswap-interface#1047]
A normal 50% Remove Liquidity, ends with error Fail with error 'UniswapV2Router: INSUFFICIENT_A_AMOUNT'

1. Go to Pool  , using chrome with metamask
https://app.uniswap.org/#/remove/ETH/0xCC4304A31d09258b0029eA7FE63d032f52e44EFe

2. Click on remove liquidity
3. Select 50%
4. Click approve tx on Metamask
5. click see on ethscan, wait, watch error and your eth/gas go away
6. open bug report

**Expected Behavior**
tx should be processed and liquidity tokens in my metamask

**Additional Context**
The error tx:
https://etherscan.io/tx/0x7fa9e02c6b1372565bd47560135865a7b46ed656971932843b33db487051b6f0

**Comment by moodysalem** [comment]
from discord faq
> My transaction failed with error: "UniswapV2Router: INSUFFICIENT_B_AMOUNT" OR "UniswapV2Router: INSUFFICIENT_A_AMOUNT" OR "UniswapV2Router: INSUFFICIENT_OUTPUT_AMOUNT"
This means the price moved after you submitted the transaction. If you wish to have the swap/add liquidity/remove liquidity execute regardless of the price, increase your slippage tolerance.
