### ISSUE TITLE
Add Token Logo: Smart Contract Address: 0xd57f7aa9929b19b9443875128df3987d42a841dd

### ISSUE THREAD

**Issue by erience** [Uniswap/uniswap-interface#1053]
Smart Contract Address: 0xd57f7aa9929b19b9443875128df3987d42a841dd
Logo URL: https://quiverx.io/img/favicon.png

**Comment by moodysalem** [comment]
@erience Did you see the text in all the issue templates that says not to create a token request here and it will be deleted if you do?
