### ISSUE TITLE
The transaction cannot succeed due to error: UniswapV2Router: EXPIRED. This is probably an issue with one of the tokens you are swapping.

### ISSUE THREAD

**Issue by austinwhite93** [Uniswap/uniswap-interface#1058]
Every single transaction I attempt with any pair is giving me this response. 

I've tried restarting my computer, internet, resetting my Ledger, v1 and v2 uniswap, nothing seems to fix it. 

This is with a Ledger Nano S

**Comment by moodysalem** [comment]
@austinwhite93 is your desktop time correct? I have seen a few reports of this, can you try increasing your transaction deadline in the settings dialog? Perhaps it is set to 0.

**Comment by moodysalem** [comment]
@austinwhite93 were you able to resolve?

**Comment by medardm** [comment]
Hii I also, encountered this problem, found out it's because the system time on my device is incorrect. Please check your date and time settings like what @moodysalem instructed

**Comment by moodysalem** [comment]
@ianlapham one solution to this would be using the last block timestamp instead of (new Date().getTime()) for the current timestamp. I believe the multicall contract affords a method for getting the block timestamp, so it would be as easy as calling useSingleContractCall.

**Comment by moodysalem** [comment]
I believe this is fixed now as described above
