### ISSUE TITLE
LP function ends in "Fail with error 'UniswapV2Router: INSUFFICIENT_A_AMOUNT'"

### ISSUE THREAD

**Issue by nwocykra** [Uniswap/uniswap-interface#1062]
**Bug Description**
A clear and concise description of the bug.

**Steps to Reproduce**
1. Go to Pool
2. Click on Add Liquidity
3. Choose ocean and eth

After the approvals, the final transaction failed:
https://etherscan.io/tx/0xd03f1fb8dd77201673ad6d9f601e70add1d38104a5c439bc7c57441e5656663c

**Expected Behavior**
Liquidity added to pool

**Additional Context**
Brave Desktop browser and metamask wallet

**Comment by moodysalem** [comment]
This means the price moved after you submitted the transaction.
