### ISSUE TITLE
Tryed to change Eth into AMPL but didn´t received them

### ISSUE THREAD

**Issue by chazychazter** [Uniswap/uniswap-interface#1066]
I´ve tried to change my Eth into 100 AMPL but didnt received them.

Here is the etherscan Address:
https://etherscan.io/tx/0x2ad0d9c04c58fabcb3bce190b905414897de271cc69c13a1a241b37615f1d1b9

**Comment by chazychazter** [comment]
A few days earlier I wrote to the Ampleforth team, but so far no answer.

**Comment by moodysalem** [comment]
It looks like you used a fake Uniswap. Please ask in Discord

**Comment by chazychazter** [comment]
Hello,

How could it be a Fake Uniswap if I managed another swap on the same site
and it works? So is the Uniswap address not the right One or why do you say
it's fake?

Moody Salem <notifications@github.com> schrieb am Mi., 26. Aug. 2020, 14:39:

**Comment by moodysalem** [comment]
I say it's fake because the output from your swap went to address `0xe1f5538510bf447b9b137eca41ad27a2d4f3bb62` which seems unintended

**Comment by moodysalem** [comment]
https://app.uniswap.org is the only legitimate Uniswap Interface. Please ask in discord, deleting this issue.
