### ISSUE TITLE
Add Liquidity  ERROR

### ISSUE THREAD

**Issue by zbgapi** [Uniswap/uniswap-interface#1067]
**Bug Description**
when i  add liquidity for a new token, there is report error， you can’t  go on。
No matter which wallet is connected, metamask or walletconnect

**Steps to Reproduce**
1. Go to ...
2. Click on ...
...

**Expected Behavior**
The normal situation should be to initiate the coin deduction transaction to the wallet

walletconnect error：
TypeError: Cannot read property '_hex' of undefined
    at Function.value (bignumber.ts:236)

metamask error：
code: -32000, message: "gas required exceeds allowance (12499861) or always failing transaction"}
![0a907d3add0a40bdba8082a5de007cc3](https://user-images.githubusercontent.com/49393763/91303111-1c2fc180-e7da-11ea-9904-521794159188.png)
![fc8a0034f9a23e2c3a970a3e270dce92](https://user-images.githubusercontent.com/49393763/91303138-25209300-e7da-11ea-8fa6-e46d563d6cb3.png)

**Comment by moodysalem** [comment]
This is an issue with the token ZT. Please ask those token developers. It probably has to do with a fee collected on transfer.

**Comment by zbgapi** [comment]
OK, I see your message. I will continue to follow up this issue. If there is any follow-up information, I will contact you in time. Thank you very much for your help~！~
