### ISSUE TITLE
Improve transaction routing

### ISSUE THREAD

**Issue by moodysalem** [Uniswap/uniswap-interface#1071]
Currently transaction routing does not consider gas cost of routing through additional pairs, or risk of routing through low liquidity pairs that are likely to see significant price movement from low volume (resulting in reverts and wasted gas)

Improve the routing to:
- consider gas cost of routing through additional pairs
- avoid low liquidity pairs in routing

**Comment by callil** [comment]
Would we consider offering the user a method of customizing gas in the UI if we have the infrastructure for this? Might help address the very common pending tx problems.

**Comment by moodysalem** [comment]
Maybe just want to pick the fastest gas price from a particular source if it's available by default, since everything is time sensitive. Not sure if most wallets actually care what gas price the dapp suggests.
