### ISSUE TITLE
Avoid unnecessary approves by using permit / Argent's approveAndCall

### ISSUE THREAD

**Issue by moodysalem** [Uniswap/uniswap-interface#1072]
This will improve UX by avoiding sending an additional transaction

**Comment by gorgos** [comment]
@moodysalem Using the interface, removing liquidity already uses `removeLiquidityETHWithPermit` for me. So is this issue here done?

**Comment by moodysalem** [comment]
Note that we should prioritize Argent's `approveAndCall` over permit, since signatures produced by Argent are not supported by most tokens
