### ISSUE TITLE
Unlock Liquidity on Uniswap

### ISSUE THREAD

**Issue by dlokman** [Uniswap/uniswap-interface#1074]
Problem: 
Providing Liquidity to Uniswap as an Eth/XXX pair results in price fluctuation risk (Eth and Pair) for the liquidity provider. In the short term, due to a price drop, the liquidity provider can have a net loss (more loss in price drop than liquidity earnings). Currently, we are in a bull cycle with no clear visibility of the prices in the upcoming future so investors can still commit liquidity without much worry. However, there can come a time during a bear market, when the bear market is confirmed to investors (e.g. Aug 1,2018)  at which point most people would want to pull their liquidity out of Uniswap (price drop would no way match liquidity earnings). This will wreak havoc for Uniswap at that time.

Solution:
Find a way to unlock liquidity on Uniswap so that the Liquidity provider does not have to worry about price fluctuation of the underlying pair. RAMP DEFI & STAFI.io are working on similar projects to unlock "staked assets" since in some projects up to 70% of the circulating supply can be locked. Perhaps the uni-v2 token issued in lieu of providing liquidity can be tradeable somehow on uniswap platform (new infrastucture) for a stable coin that can retain the original value or via some other way. Providing Liquidity should not come with a price risk of the underlying pair. Or you can have 2 options for users 1) that wanna have price risk (bull market) 2) no price risk

**Comment by moodysalem** [comment]
> Providing Liquidity should not come with a price risk of the underlying pair

There is no such thing as profit without risk. If you want reduced price risk, provide liquidity in two assets that are strongly correlated (e.g. USDC/USDT).

If you have a solution to suggest, I recommend you bring it up in the Discord.
