### ISSUE TITLE
There is a Bug in Uniswap. Exchanged the Output Address. 

### ISSUE THREAD

**Issue by chazychazter** [Uniswap/uniswap-interface#1076]
Hello,

I am now trying to clarify this for the second time. The first post was deleted.

I recently tried to swap my Eth for AMPL via Uniswap. According to ethscan, the money was withdrawn and the 100 AMPL was also exchanged, but a completely different address was added for the payment of Uniswap.

When I asked, they said I had used a FAKE uniswap. But since everything is documented on etherscan, you can see that everything is wrong except for the payout address. 

See here: https://etherscan.io/tx/0x2ad0d9c04c58fabcb3bce190b905414897de271cc69c13a1a241b37615f1d1b9

My questions would be:
Why is Uniswap packing another random address in here? and who can I write to for payment?

Brief remark:
Deleting this post won't solve the problem! I ask for a reply in this post, or at least a reasonable explanation of what happened there.

Best regards
W.Geffel

**Comment by moodysalem** [comment]
This is not a bug in the Uniswap Interface. You used a malicious fork of the Uniswap interface. Anyone can fork this repository and make all swaps send to their own address, and then host the forked code at a different URL which looks like the real URL. If you are on any URL other than app.uniswap.org when doing a swap, then you risk being scammed in this way. It is likely you clicked on a phishing link, possibly advertised on Google or other sites, that led you to a fake Uniswap interface with this scam swap implementation. Please reach out to the Discord and see https://support.mycrypto.com/staying-safe/common-scams/phishing-overview for more information.

**Comment by chazychazter** [comment]
That sounds very curious, because I was on this site and reordered more
Coins to test it. There wasn't a Problem. I don't even switch the Site. So
what is your Next Excuse?  I've ordered 100 Ampl and payed for it. Uniswap
owe me 100 Ampl and I will get these. I will reopen every Day the next
issue on your Site till I get them.
If you don't want to help me Out, we will talk everyday a couple of Months,
till I get my Money. If you can't write a Programm properly, don't try it
and accuse other people for your Faults.
I've payed for the Coins and I will get them.

See you Tommorrow at Github.

Moody Salem <notifications@github.com> schrieb am Sa., 29. Aug. 2020, 18:24:
