### ISSUE TITLE
 Beware of this program / Money is gone / Noone helps

### ISSUE THREAD

**Issue by chazychazter** [Uniswap/uniswap-interface#1078]
I tried to buy Ampleforth Coins with Uniswap and invested Ether.
No coin arrived on the first try. On Etherscan you can see that the money went elsewhere. 
( https://etherscan.io/tx/0x2ad0d9c04c58fabcb3bce190b905414897de271cc69c13a1a241b37615f1d1b9  )
The support said I had used a different site than uniswap. But since I exchanged coins for a smaller amount on the side after the first test to check whether it worked and it worked, this statement from the support is not true. My first two issues were deleted and I am partially ignored. I would like to clarify the case. I also have the Etherscan address of the transactions. There you can clearly see that Uniswap has exchanged the money. The recipient was changed and Uniswap says that it was my fault. But I have not entered this address. It seems like there is a bug in the code here. I kindly ask you once again to have a look at it and possibly think about that there might be a bug in the program. That could save you a lot of trouble. I would also like to receive the performance that I am entitled to. Because I paid for it.

Best regards
W.Geffel

**Comment by moodysalem** [comment]
@chazychazter You can see here that the `to` address to which you sent your tokens is not anywhere in this repository:
https://github.com/Uniswap/uniswap-interface/search?q=e1f5538510bf447b9b137eca41ad27a2d4f3bb62&unscoped_q=e1f5538510bf447b9b137eca41ad27a2d4f3bb62

This means it is *impossible* for a bug to have caused this. The `to` address was either entered by you, or you were using a malicious fork.
