### ISSUE TITLE
uniswap can not convert band to other token(ps: eth dai) with metamask or tokenpocket

### ISSUE THREAD

**Issue by yiyanwannian** [Uniswap/uniswap-interface#1080]
**Bug Description**
A clear and concise description of the bug.

**Steps to Reproduce**
1. Go to https://app.uniswap.org/#/swap and connect your metamask which cantains some band token
2. Chose "from band" and "to eth", like picture below 
3. Click "Approve Band" button and it will trigger metamask like picture below 

**Expected Behavior**
I can click metamask "confirm" button

**Additional Context**
I can not click it for its unactive and I tried change "Slippage tolerance" max to 40%, and confirm button still unactive

**Comment by yiyanwannian** [comment]
<img width="1045" alt="截屏2020-08-30 23 04 18" src="https://user-images.githubusercontent.com/8225547/91662482-47d1e500-eb15-11ea-89f2-59a4ee218345.png">
<img width="363" alt="截屏2020-08-30 23 04 39" src="https://user-images.githubusercontent.com/8225547/91662485-4d2f2f80-eb15-11ea-9586-8b7b97f67b84.png">

**Comment by moodysalem** [comment]
It looks like you just don't have ETH to pay for the approval.
