### ISSUE TITLE
Fail with error 'UniswapV2Router: INSUFFICIENT_B_AMOUNT'

### ISSUE THREAD

**Issue by bdhf24** [Uniswap/uniswap-interface#1081]
Tx hash: 0x050c16e3214272cd528daf6d6ce7a8e2ed603119c778d84b365fa6baa09d78c1
Tx hash 2: 0xed1c9221d4c04cd7d0d7856e9e1d9405cd7d07756609273f12b36a3029e14750

I tried to withdraw from the Uniswap contract using metamask twice but both times it failed.

It looks like the gas fee was taken on both occasions.

**Comment by moodysalem** [comment]
Please ask in the Discord. This error is in the #faq channel
