### ISSUE TITLE
cannot approve and no click supply!

### ISSUE THREAD

**Issue by ZzikoWang** [Uniswap/uniswap-interface#1088]
**Bug Description**
I can't click supply when I enter a trade pair pool.（ZB/USDT、ZB/ETH etc.）
In QC / ZB, QC can approve, ZB cannot approve

**Steps to Reproduce**
1. Go to ...
2. Click on ...
...

**Expected Behavior**
1. In QC/ZB updater.tsx:190 Failed to fetch multicall chunk [{…}] 1 Error: call revert exception (method="aggregate((address,bytes)[])", errorSignature=null, errorArgs=[null], reason=null, code=CALL_EXCEPTION, version=abi/5.0.2)

  In QC/ZB, Click on Approve ZB.  use Approve Callback.ts:53 
  approve was called unnecessarily

2. In ETH/ZB, No click supply! Failed to fetch multicall chunk

**Additional Context**
![zb_uniswap_github](https://user-images.githubusercontent.com/29268352/92209504-aef9eb80-eebf-11ea-9d49-9a5798b7cfb3.jpg)
![zbQC](https://user-images.githubusercontent.com/29268352/92212065-fe421b00-eec3-11ea-9a62-aed4dddfd5d4.jpg)

**Comment by ZzikoWang** [comment]
ZB token：0xbd0793332e9fb844a52a205a233ef27a5b34b927

**Comment by ZzikoWang** [comment]
Hello,Please help to have a look。

**Comment by moodysalem** [comment]
One of the tokens likely does not implement the ERC20 specification. That's all I can tell you without digging further, I suggest you ask the token developers.

**Comment by ZzikoWang** [comment]
Very thanks!
