### ISSUE TITLE
Module not found: Can't resolve '@uniswap/sdk'

### ISSUE THREAD

**Issue by mkh01** [Uniswap/uniswap-interface#1089]
When i try to start yarn i become this error:

Module not found: Can't resolve '@uniswap/sdk' in '/var/www/html/uniswap-interface/src/components/CurrencyLogo'

in CurrenyLogo file it is imported from the write sdk dir like this import { Currency, ETHER, Token } from '@uniswap/sdk' but i don't know why it is not working for me!!!
Any ideas how solve this Problme?

**Comment by tpmccallum** [comment]
Did you run `install` in that directory before starting i.e. `npm install`?

**Comment by mkh01** [comment]
If you mean yarn install, yes i did it when i started
