### ISSUE TITLE
Fail with error 'UniswapV2Router: INSUFFICIENT_B_AMOUNT'

### ISSUE THREAD

**Issue by alikut80** [Uniswap/uniswap-interface#1090]
I can not not remove mu liquidity even i tried with highest fee 2 times. Ut gives error Fail with error 'UniswapV2Router: INSUFFICIENT_B_AMOUNT'

Anyone help ne?

**Comment by alikut80** [comment]
0xe5f38c2db188cc4e9104ff2f92ee70fba50500e1d0af56151a929fe68bd1fe1d

**Comment by moodysalem** [comment]
If you can send the transaction, this just means the price moved. Increase your slippage tolerance. Please ask support questions in the discord in the future.
