### ISSUE TITLE
ENS Tokenlists don't work while connected to test network on URL other than app.uniswap.org

### ISSUE THREAD

**Issue by MicahZoltu** [Uniswap/uniswap-interface#1091]
**Bug Description**
If you are connected to a test network through your wallet and you try to load a tokenlist by ENS address, the lookup will fail because it tries to communicate with the mainnet registrar as seen at
https://github.com/Uniswap/uniswap-interface/blob/7cf25ac7c8e2969381ebe71e9a24140902204784/src/utils/resolveENSContentHash.ts#L26

The only way to resolve this is to switch networks over to mainnet, load the tokenlist, then switch back to the test network.

**Steps to Reproduce**
1. Install MetaMask.
2. Switch to Ropsten.
3. Open https://app.uniswap.org
4. Add the tokenlist `testnet.tokenlist.eth`
5. Notice that the tokenlist fails to load, despite the tokenlist being published as a contenthash at that ENS address on both mainnet and Ropsten.

**Expected Behavior**
ENS resolution will either always go through mainnet, or it will utilize the ENS registrar currently deployed to the selected test network.

**Additional Context**
I think either of the following solutions are reasonable:
1. ENS always resolves via the currently connected network and gives a clear error if the currently selected network doesn't have a known ENS registry.
2. ENS always resolves via mainnet.

Something to consider with (2) is that if ENS resolution is happening elsewhere in the UI such as is the transfer-and-send destination field, then I think it is a bit more important to resolve with the currently selected network rather than via mainnet.

**Comment by moodysalem** [comment]
> Something to consider with (2) is that if ENS resolution is happening elsewhere in the UI such as is the transfer-and-send destination field, then I think it is a bit more important to resolve with the currently selected network rather than via mainnet.

This is the case. 

The list stuff is a little more complicated because a list identified by ENS name always references mainnet ENS name even though you're on a testnet (since lists may contain tokens on different chains)

So we don't ever want to resolve list urls on Testnet ENS for lists. The way it's written is *supposed to* always use mainnet ENS for resolving list URLs (via infura if you are connected to a testnet). However if you are running it local connected and have changed the RPC Network URL then the code won't work iirc. I'm open to improvements to this code but it can't be prioritized given it's only an issue on testnets.

**Comment by MicahZoltu** [comment]
> The way it's written is supposed to always use mainnet ENS for resolving list URLs (via infura if you are connected to a testnet).

What is the scenario where this works as intended?  I load Uniswap, connect to MetaMask, point MetaMask at testnet and it tries to read the mainnet ENS address via MetaMask (which of course fails).

**Comment by moodysalem** [comment]
> > The way it's written is supposed to always use mainnet ENS for resolving list URLs (via infura if you are connected to a testnet).
> 
> What is the scenario where this works as intended? I load Uniswap, connect to MetaMask, point MetaMask at testnet and it tries to read the mainnet ENS address via MetaMask (which of course fails).

According to https://github.com/Uniswap/uniswap-interface/blob/f33bba217603765939478a64bb0b672da63eccbc/src/hooks/useFetchListCallback.ts#L20 it should check the network ID of metamask, and fallback to the network library if it's not chain ID 1. Otherwise it should throw an error

**Comment by MicahZoltu** [comment]
Ah, I see the problem.  I have IPFS companion installed and the fallback Infura call is getting rejected because the `origin` header doesn't match the API key.

This is why we can't have nice things...

**Comment by moodysalem** [comment]
Closing since it's related to ipfs companion

**Comment by MicahZoltu** [comment]
@moodysalem There may be a misunderstanding here, the bug is in Uniswap, which doesn't work properly when using the app with IPFS currently.  My comment about IPFS companion was just me figuring out how I got into the situation I got into.

1. Load Uniswap via IPFS from localhost.
2. Notice that nothing works.

**Comment by MicahZoltu** [comment]
Infura works on cf-ipfs.com and dweb.link but does not work on localhost or `https://ipfs.my-domain.example/ipfs/CIDv1`.  It gives 403 (forbidden) in the latter two cases.
