### ISSUE TITLE
Everyonescrypto EOC

### ISSUE THREAD

**Issue by everyonescrypto** [Uniswap/uniswap-interface#1097]
Hi!
We wanna our project in uniswap-interface.
Token:
Everyonescrypto
EOC
Contract: 0xA8006e3Ac1bD94e54E3136B8e5dD75db0163e6f4
Decimals: 18
Total supply: 25,499,999 EOC
https://etherscan.io/token/0xA8006e3Ac1bD94e54E3136B8e5dD75db0163e6f4
[http://everyonescrypto.com/logo_blue.png](url)

[www.everyonescrypto.com](url)
e-mail: info@everyonescrypto.com

br:
Justin Cryfield

**Comment by moodysalem** [comment]
Wrong place.
