### ISSUE TITLE
Trying to provide liquidity on uniswap via metamask.  Error message on ether scan , eth not in wallet. 

### ISSUE THREAD

**Issue by uberslug1987** [Uniswap/uniswap-interface#1098]
I was trying to provide liquidity on uniswap using my metamask wallet. I was trying to provide liquidity on eth and elf.   Im getting the following error message when I check the transaction on etherscan 
  
I have attached the screenshot below.  The elf has appeared back in my wallet but no sign of the eth. My public address is 0xA5C05aDEf1736971c74609A5a1Ab61a54C6A3BDd

![Uniswap error](https://user-images.githubusercontent.com/53947413/92724278-3af99080-f362-11ea-87ff-75397a7b0f49.PNG)

**Comment by moodysalem** [comment]
Please ask in support channel on Discord.
