### ISSUE TITLE
Uniswap Liquidity BUG

### ISSUE THREAD

**Issue by ArunaHM** [Uniswap/uniswap-interface#1099]
i am trying to provide liquidity in Uniswap but got error all 3 times as " Fail with error 'UniswapV2Router: INSUFFICIENT_A_AMOUNT ".

Transaction Hash 0xe6ba970d89bdbef4829ce62637a55868271ab338a995a6d85448cbb91ddd3da7

**Comment by moodysalem** [comment]
Please ask in support channel on Discord.
