### ISSUE TITLE
Fail with error 'UniswapV2Router: INSUFFICIENT_OUTPUT_AMOUNT'

### ISSUE THREAD

**Issue by Acewriter2017** [Uniswap/uniswap-interface#1101]
I've attached a screenshot of what happened.  I'm a first-time Uniswap user and someone suggested I send a bug report, so here I am.  
I got this message - "Fail with error 'UniswapV2Router: INSUFFICIENT_OUTPUT_AMOUNT'
<img width="1053" alt="Screen Shot 2563-09-13 at 12 24 10" src="https://user-images.githubusercontent.com/32172657/93011019-e0a83c00-f5bc-11ea-8f7b-cb450755cec5.png">

<img width="1053" alt="Screen Shot 2563-09-13 at 12 24 10" src="https://user-images.githubusercontent.com/32172657/93010981-7b544b00-f5bc-11ea-98f0-f5ff986ee5af.png">

**Bug Description**
A clear and concise description of the bug.

**Steps to Reproduce**
1. Go to ...
2. Click on ...
...

**Expected Behavior**

**Additional Context**
Add any other context about the problem here (screenshots, whether the bug only occurs only in certain mobile/desktop/browser environments, etc.)

**Comment by moodysalem** [comment]
This is not a bug, Uniswap transactions fail if the price moves against you (called slippage) by more than your slippage tolerance. Please seek support in the Discord!
