### ISSUE TITLE
ERR_SSL_PROTOCOL_ERROR on app.uniswap.org using trust wallet on android, google chrome, safari on mac book pro 2019

### ISSUE THREAD

**Issue by xiankaing** [Uniswap/uniswap-interface#1108]
**Bug Description**
ERR_SSL_PROTOCOL_ERROR on app.uniswap.org using trust wallet on android, google chrome, safari on mac book pro 2019

**Steps to Reproduce**
1. app.uniswap.org on trust wallet on android, or google chrome or safari on mac
2. see it return ERR_SSL_PROTOCOL_ERROR or "Unable to establish secure connection"

**Expected Behavior**
It should load the page, and not give ERR_SSL_PROTOCOL_ERROR.

**Additional Context**
<img width="1144" alt="Screen Shot 2020-09-15 at 10 40 49 PM" src="https://user-images.githubusercontent.com/22782357/93296659-81a51b80-f7a4-11ea-8919-a68cd08c771a.png">

**Comment by moodysalem** [comment]
Did refreshing the page resolve your error?

**Comment by xiankaing** [comment]
@moodysalem no
Nor did incognito 
Curling app.uniswap.org also gives me a similar error
Suggesting that the server needs to upgrade its TLS

**Comment by moodysalem** [comment]
I don't think that is the issue. The Cloudflare IPFS gateway serves the files. It is probably an issue with proxies or firewalls on your network.

**Comment by moodysalem** [comment]
You can try the IPFS gateway links from the latest release
https://github.com/Uniswap/uniswap-interface/releases/tag/v2.6.5

**Comment by xiankaing** [comment]
The other links like https://bafybeibc43yurnkut5lkj2yrvpanbbi26scx5mgvsxqxi3zd4povwzq6ge.ipfs.dweb.link/#/swap work for me

**Comment by moodysalem** [comment]
Don't think we can do anything here.
