### ISSUE TITLE
Tokens not being displayed

### ISSUE THREAD

**Issue by chaitanyapotti** [Uniswap/uniswap-interface#1115]
**Bug Description**
Tokens in wallet not being displayed on uniswap. Hence, i'm unable to swap.

**Steps to Reproduce**
- Connect any provider
- Click dropdown to see token balances.
- Nothing is visible except eth

**Expected Behavior**
To see tokens

**Additional Context**
Looks like the issue is because of defi prime api failing
![image](https://user-images.githubusercontent.com/1688380/93546851-5550f100-f996-11ea-9a5d-49e260a46f9c.png)

**Comment by moodysalem** [comment]
You must select a list. The solution here is to default to a list when there is no list selected on startup.

**Comment by chaitanyapotti** [comment]
Please do that or atleast prompt to select a list. it's not intuitive.

**Comment by yangli1990** [comment]
@moodysalem whilst after some usage I know that I need to select a list, I'm not entirely sure why I need to. Why can't we have a one list with everything that Uniswap offers rather than have users test around and select the list that includes their target token?

**Comment by moodysalem** [comment]
> @moodysalem whilst after some usage I know that I need to select a list, I'm not entirely sure why I need to. Why can't we have a one list with everything that Uniswap offers rather than have users test around and select the list that includes their target token?

The rationale for lists is explained here:

https://uniswap.org/blog/token-lists/

**Comment by moodysalem** [comment]
A list should always be selected now.
