### ISSUE TITLE
Unable to process ETH-DAI Liquidity Mining

### ISSUE THREAD

**Issue by vikiival** [Uniswap/uniswap-interface#1117]
**Bug Description**
When I want to deposit WETH:DAI to ETH-DAI Liquidity Mining I get error

```
TypeError: Cannot read property '_hex' of undefined
    at Function.value (bignumber.ts:236)
    at r.<anonymous> (4.292c8984.chunk.js:2)
    at c (runtime.js:63)
    at Generator._invoke (runtime.js:293)
    at Generator.next (runtime.js:118)
    at a (4.292c8984.chunk.js:2)
```

**Steps to Reproduce**
1. Go to [ETH-DAI Liquidity Mining](https://app.uniswap.org/#/uni/ETH/0x6B175474E89094C44Da98b954EedeAC495271d0F)
2. Click on `Deposit UNI-V2 LP tokens`
3. Select amount (e.g MAX)
4. Click apporove (used walletconnect on argent)
5. Click submit
...

**Expected Behavior**
I expect that submit would be created successfully

**Additional Context**
<img width="1519" alt="Screen Shot 2020-09-20 at 02 31 31" src="https://user-images.githubusercontent.com/22471030/93691763-3e231800-faea-11ea-97bb-975e15c68ee5.png">

**Comment by moodysalem** [comment]
Usually has to do with a failure to estimate gas IME. What is the wallet you are using? If argent, this is an issue with Argent's signature not being supported by UNI-V2 LP tokens.
