### ISSUE TITLE
Uniswap Interface unresponsive after connecting metamask

### ISSUE THREAD

**Issue by RikaSukenik** [Uniswap/uniswap-interface#1123]
**Bug Description**
After connecting metamask, the "Claim Uni" box persistently flashes and the site is unresponsive

**Steps to Reproduce**
1. Go to app.uniswap.org
2. Connect metamask
3. Metmask connected
4. "Claim Uni" box persistently flashes & site is unresponsive
...

**Expected Behavior**
Should be able to go to next step after connecting wallet to claim UNI

**Additional Context**
Add any other context about the problem here (screenshots, whether the bug only occurs only in certain mobile/desktop/browser environments, etc.)
Google Chrome, Mac

**Comment by JhonnyJason** [comment]
Can confirm the issue also on Firefox Developer Edition 81.0b9 (64-bit)

**Comment by mplanes** [comment]
Can confirm the issue on up to date Google Chrome and Firefox, normal mode and incognito mode, no additional extensions.

**Comment by JhonnyJason** [comment]
Very interesting bug, because I managed to claim mine earlier today, with Chomium on Linux - later I tried with a friend to claim theirs and the problem occured. On Mac-Chrome, Mac-Firefox and my Linux FirefoxDevEdition later.

So it must've been one of the most recent updates.

**Comment by JhonnyJason** [comment]
Interesting now somebody must've fixed it.^^ Hurray!

Also interesting that not the most update code is here on github ^^...

**Comment by moodysalem** [comment]
I've fixed it. Code for app.uniswap.org is currently in a separate repo.

**Comment by JhonnyJason** [comment]
Thank you very much, sir! :D
