### ISSUE TITLE
Error setting up new liquidity pool

### ISSUE THREAD

**Issue by TModMarco** [Uniswap/uniswap-interface#1125]
Hi all, writing this bug report after briefly speaking with Noah & after having reported my issue in the Discord over three times within the past two months, unfortunately without successfully fixing it.

**Bug Description**
When trying to set up a new liquidity pool for PRE/(w)ETH, an error occurs at the last stap of setting up the pool.
When hitting 'Create Pool & Supply' no transaction pops up, which should happen to approve the pool.

I've set up pools for other projects and have never experienced this. I've also tried manually setting one up via Etherscan, the transaction was approved ($100 tx fee) but it doesn't seem it fixed the issue.

PRE smart contract address: https://etherscan.io/address/0x88a3e4f35d64aad41a6d4030ac9afe4356cb84fa
Transaction on dummy account to set up pool manually via Etherscan: https://etherscan.io/tx/0xf65bc6e9227f7536bb491ba7e384698f1d67e7435648c2615ee9ae5908018131

**Steps to Reproduce**
1. Go to https://app.uniswap.org/#/add/ETH/0x88A3E4F35D64aAD41A6d4030ac9AFE4356cB84fA
2. Click on Supply & then click on 'Create Pool & Supply'.

The following errors occur:
https://imgur.com/FrYx8g0 < See image: no transaction pops up in Metamask. Not on other browsers either. Dev tools shows this error.

**Expected Behavior**
I'm expecting a transaction/smart contract to pop up, which I then approve to provide the liquidity as usual.

**Additional Context**
I've tried through a dummy account, as well as I've had our CEO try setting up a pool via the owner address. Unfortunately, without success. I'll happily provide answers to any questions.

I looked up all the errors on the internet and it seems like it refers back to something with our smart contract, I'm uncertain what. Our developers haven't been able to find the issue yet either.

Hoping to get some support here to finally be able to get PRE listed on Uniswap, as Uniswap rocks! ;)

**Comment by MicahZoltu** [comment]
Issue was a bug in the token.  It will always fail on `.transferFrom` due to the modifier being setup incorrectly.  It asserts that there are only 72 bytes of calldata, but for `.transferFrom` there will always be 104 bytes of calldata.
