### ISSUE TITLE
ETH:WBTC Liquidity Mining Signature Broken

### ISSUE THREAD

**Issue by cazala** [Uniswap/uniswap-interface#1127]
**Bug Description**
I tried to deposit [UNI-V2 LP](https://etherscan.io/address/0xbb2b8038a1640196fbe3e38816f3e67cba72d940) tokens into the [ETH:WBTC Liquidity Mining](https://app.uniswap.org/#/uni/ETH/0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599) both with plain MetaMask and with Ledger + MetaMask and both fail when providing the signature for the `Approve` step.

**Steps to Reproduce**
1. Go to https://app.uniswap.org/#/uni/ETH/0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599
2. Click on Deposit UNI-V2 LP Tokens
3. Set maximum amount of LP tokens available to deposit
4. Click on Approve
5. MetaMask pops up prompting for a signature:

<img width="355" alt="Screen Shot 2020-09-23 at 17 30 30" src="https://user-images.githubusercontent.com/2781777/94066356-c3484e80-fdc2-11ea-9f0d-bf9d0d0c5c42.png">

6. Click on `Sign`
7. Nothing happens. An error shows on the console:

```MetaMask Message Signature: Error: Argument is not a number```

When using MetaMask + Ledger the error is:

```MetaMask Message Signature: Error: Not supported on this device```

**Expected Behavior**
When using with Ledger i was expecting at that point to have to confirm the signature on my Ledger but nothing happened. After clicking on `Sign` I expect to continue with the `Deposit` transaction.

**Comment by moodysalem** [comment]
Thank you for the report, I found the bug in staking. I have just pushed a fix and it should be available in 10 minutes.
