### ISSUE TITLE
Cant deposit UNI-V2 LP tokens in ETH-USDT Liquidity Mining when connected via WalletConnect

### ISSUE THREAD

**Issue by DevAlexey** [Uniswap/uniswap-interface#1130]
**Bug Description**
Cant deposit UNI-V2 LP tokens in ETH-USDT Liquidity Mining when connected via WalletConnect

**Steps to Reproduce**
0. Have some ETH-USDT UNI-V2 LP tokens
1. Open https://app.uniswap.org/#/uni/ETH/0xdAC17F958D2ee523a2206206994597C13D831ec7
2. Connect to account via WalletConnect.
3. Press deposit.
4. Max amount and approve.

**Expected Behavior**
Should get prompt for tx sign in the wallet, but nothing happens

**Additional Context**
Using coinomi wallet and chrome browser.

**Comment by moodysalem** [comment]
I've never used this wallet, it's possible it doesn't support message signing?

**Comment by DevAlexey** [comment]
I was able to use it for staking ETH-USDT on near tab, so it`s working in other cases.

**Comment by moodysalem** [comment]
> I was able to use it for staking ETH-USDT on near tab, so it`s working in other cases.

What do you mean by near tab? If you try again does it work?

**Comment by DevAlexey** [comment]
> > I was able to use it for staking ETH-USDT on near tab, so it`s working in other cases.
> 
> What do you mean by near tab? If you try again does it work?

I was able to deposit funds for liquidity here
https://app.uniswap.org/#/add/ETH/0xdAC17F958D2ee523a2206206994597C13D831ec7
But I still can`t do it here
https://app.uniswap.org/#/uni/ETH/0xdAC17F958D2ee523a2206206994597C13D831ec7

**Comment by moodysalem** [comment]
Probably a wallet issue given the description, but liquidity mining is no longer active.
