### ISSUE TITLE
error: UniswapV2: K

### ISSUE THREAD

**Issue by busytoby** [Uniswap/uniswap-interface#1133]
**Bug Description**
I have attempted to sell any of these three tokens:
FIRE: 0x3F8A2f7bcD70e7F7Bdd3FbB079c11d073588DEA2
AST: 0xa872E0a44BBd66c1486a756CB5BD3F0bEEC4e32e
PAMP: 0xF0FAC7104aAC544e4a7CE1A55ADF2B5a25c65bD1

For any sale of these tokens the UI is reporting:
The transaction cannot succeed due to error: UniswapV2: K. This is probably an issue with one of the tokens you are swapping.

This is prior to any confirmation popup from metamask, no confirmation ever pops.

If I continue to try over an hour or more I can eventually get a transaction to initiate but then the error returns some short time later.

**Steps to Reproduce**
1. Attempt to sell any of the 3 tokens above, or presumedly any token which is deflationary on transfer
2. Notice the error popup on the website, the transaction never makes it to metamask
...

**Comment by busytoby** [comment]
This appears to be a Uniswap UI bug.
If I try to sell any deflationary token for a specific amount of ETH ie: Sell from wallet balance for 0.25 ETH, the UI computes an invalid digit length and the transaction fails.

If I instead try to sell an exact number from the deflationary token balance ie: 1000 AST for whatever amount of ETH, the transaction is posted to MetaMask and succeeds as expected.

**Comment by ragle** [comment]
Right. I was likewise able to get around this by just using a round number for the deflationary token I wanted to swap for ETH.

**Comment by moodysalem** [comment]
It depends on the token. If the token has rebases similar to how AMPL works, it may cause the pair to break and throw this error, until someone calls `sync` on the pair contract.

**Comment by CryptoGnome** [comment]
I have seen this error as well more than once, here is a example TX:
https://etherscan.io/tx/0x4754dd19fe79179d5e0e511fa90311f6b1141eed62d4eee55d617d6932245ee3

**Comment by pplonski** [comment]
I've got this error without using UI.

I want to manually swap exact token (6d6506e6f438ede269877a0a720026559110b7d5) to token (f0fac7104aac544e4a7ce1a55adf2b5a25c65bd1)

The function that I call:
```
swapExactTokensForTokens(uint256 amountIn, uint256 amountOutMin, address[] path, address to, uint256 deadline)
```

input data used:
```
# | Name | Type | Data
-- | -- | -- | --
0 | amountIn | uint256 | 737594127022435509
1 | amountOutMin | uint256 | 1
2 | path | address[] | 6d6506e6f438ede269877a0a720026559110b7d5f0fac7104aac544e4a7ce1a55adf2b5a25c65bd1
3 | to | address | 89797ff78cd4f1a0a6ded5ea7b389ed414e108db
4 | deadline | uint256 | 4901989959
```

Transaction: https://etherscan.io/tx/0x2d366f44aba71e0d76e54e1701c4bde2cbd8e17c4422ef99f17cbc921860d801

It would be nice to know which tokens can be used in the swap and which can not. How to check that?

**Comment by VanijaDev** [comment]
Same issue here. Using Uniswap API

**Comment by dmamira** [comment]
Same issue.

**Comment by CryptoGnome** [comment]
Attempt to raise gas limit on pairs with burn or other weird functions..

**Comment by fernandezpaco** [comment]
Any update on this? I'm getting same error.

If i call getAmountOut i get:
`[ '2000000000000000000',
  '8929646551579217460990',
  '260279713853141966224',
  '2012937985424733095' ]`

But if i try the swap (swapExactETHForTokens) i get:
`{ Error: Returned error: execution reverted: UniswapV2: K }`

My example path:
`0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2,0xD04785C4d8195e4A54d9dEc3a9043872875ae9E2,0x1f9840a85d5af5bf1d1762f925bdaddc4201f984,0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2`

Thanks

**Comment by jitendermalik** [comment]
got same issue , any help on this is appreciated

**Comment by tokyo786** [comment]
@jitendermalik @fernandezpaco @pplonski 
Have you guys tried the `swapExactTokensForETHSupportingFeeOnTransferTokens` [or similar functions instead?] - since the token is collecting a fee on transfer, you may want to try those functions. Probably enabling supporting fee on transfer tokens might help.

https://uniswap.org/docs/v2/smart-contracts/router02 

![image](https://user-images.githubusercontent.com/19167384/99196309-9d7f6a80-27b1-11eb-93c9-611a1f00e01d.png)

**Comment by sabotagebeats** [comment]
found this error with rebasing token, calling `poolContract.sync()` fixed it.

**Comment by jitendermalik** [comment]
> found this error with rebasing token, calling `poolContract.sync()` fixed it.

Is this fixed deployed in production ?

**Comment by jitendermalik** [comment]
> https://uniswap.org/docs/v2/smart-contracts/router02
@tokyo786 I am writing proxy contract which will be used for multiple tokens.  I do not think all pairs support this 
swapExactTokensForETHSupportingFeeOnTransferTokens , How to identify which token support fee on transfer

**Comment by firstprimecrypto** [comment]
> 
> 
> > https://uniswap.org/docs/v2/smart-contracts/router02
> > @tokyo786 I am writing proxy contract which will be used for multiple tokens.  I do not think all pairs support this
> > swapExactTokensForETHSupportingFeeOnTransferTokens , How to identify which token support fee on transfer

I want to do the same. Did you already find a solution for this?

**Comment by tokyo786** [comment]
@firstprimecrypto @jitendermalik I think (most probably) all uniswap v2 pairs would support that function.

**Comment by firstprimecrypto** [comment]
> 
> 
> @firstprimecrypto @jitendermalik I think (most probably) all uniswap v2 pairs would support that function.

Tx!

I tried USDT to ETH with swapExactTokensForETHSupportingFeeOnTransferTokens(), and that worked! So it might be used as an alternative.
Out of curiosity, one day I would like to figure out how a contract is registered in Uniswap supporting "FeeOnTransferTokens".  I expect to find it in contract source, but I'm not sure.

**Comment by wuhengzhi** [comment]
> found this error with rebasing token, calling `poolContract.sync()` fixed it.

Could you share the code please? thanks.

**Comment by sabotagebeats** [comment]
> > found this error with rebasing token, calling `poolContract.sync()` fixed it.
> 
> Is this fixed deployed in production ?

i needed to call the sync function on the pool contract

**Comment by wuhengzhi** [comment]
@busytoby I have tried to invoke poolContract.sync() on etherscan(write contract: sync), but still failed.
swap FRI to WETH.
Could you give some advices? Thanks.

**Comment by wuhengzhi** [comment]
> > > found this error with rebasing token, calling `poolContract.sync()` fixed it.
> > 
> > 
> > Is this fixed deployed in production ?
> 
> i needed to call the sync function on the pool contract

I have tried to invoke poolContract.sync() on etherscan(write contract: sync), but still failed.
swap FRI to WETH.
Could you give some advices? Thanks.

**Comment by sabotagebeats** [comment]
> > > > found this error with rebasing token, calling `poolContract.sync()` fixed it.
> > > 
> > > 
> > > Is this fixed deployed in production ?
> > 
> > 
> > i needed to call the sync function on the pool contract
> 
> I have tried to invoke poolContract.sync() on etherscan(write contract: sync), but still failed.
> swap RFI to WETH.
> Could you give some advices? Thanks.

I don't know that token but it could be one of a few things,
if it is a rebasing (elastic supply) token try using the sync command before making your swap
if it is a fee token then try using the swapExactTokensForETHSupportingFeeOnTransferTokens() instead
if it is a normal erc20 token try using swapExactTokensForETH() instead

**Comment by wuhengzhi** [comment]
Thanks @sabotagebeats 
1. I have tried sync command, the steps: etherscan--pair contract--write contract--sync, then swap, but failed.

2. The token is in my contract, so I can not use swapExactTokensForETHSupportingFeeOnTransferTokens(), from the transactions of the token, there are no burns. It should be not a fee token.

3. I have tried swapExactTokensForETH(), or swap RFI to other tokens, it also failed with "execution reverted: UniswapV2: K", since the pool is only RFI -- ETH.

**Comment by sabotagebeats** [comment]
@wuhengzhi 
> 3. I have tried swapExactTokensForETH(), or swap RFI to other tokens, it also failed with "execution reverted: UniswapV2: K", since the pool is only RFI -- ETH.
I'm not sure why you're getting the K error, but you should be able to swap to other tokens through eth with `router.swapExactTokensForTokens(amountIn,amountOut,[token1,router.WETH(),token2],receiver,deadline)`

**Comment by sabotagebeats** [comment]
@wuhengzhi 
> 2. The token is in my contract, so I can not use swapExactTokensForETHSupportingFeeOnTransferTokens(), from the transactions of the token, there are no burns. It should be not a fee token.

if this is the correct one then it looks like it is a fee token
[https://reflectfinance.medium.com/introducing-reflect-rfi-362b97e3670d](https://reflectfinance.medium.com/introducing-reflect-rfi-362b97e3670d )

`At its core, RFI charges a 1% transaction fee and re-distributes that fee to existing RFI holders instantly and automatically at the time of each transaction.`

**Comment by sabotagebeats** [comment]
I think the issue here is that uniswap goes to transact a certain number of tokens but that number of tokens doesn't come out properly so uniswap fails. 

Either because of 

1. rebase has changed the amount of tokens within the uniswap LP which then changes the amount of tokens outputted in the transaction 

or 

2. because of fee has changed the amount of tokens outputted in the transaction. 

The error message should be more descriptive.

**Comment by wuhengzhi** [comment]
> @wuhengzhi
> 
> > 1. I have tried swapExactTokensForETH(), or swap RFI to other tokens, it also failed with "execution reverted: UniswapV2: K", since the pool is only RFI -- ETH.
> 
> I'm not sure why you're getting the K error, but you should be able to swap to other tokens through eth with `router.swapExactTokensForTokens(amountIn,amountOut,[token1,router.WETH(),token2],receiver,deadline)`

Many Thanks @sabotagebeats , for other tokens, I can swap tokens with `router.swapExactTokensForTokens(amountIn,amountOut,[token1,router.WETH(),token2],receiver,deadline)`, but failed with RFI: still K error.

**Comment by Raytlty** [comment]
> > @wuhengzhi
> > > 1. I have tried swapExactTokensForETH(), or swap RFI to other tokens, it also failed with "execution reverted: UniswapV2: K", since the pool is only RFI -- ETH.
> > 
> > 
> > I'm not sure why you're getting the K error, but you should be able to swap to other tokens through eth with `router.swapExactTokensForTokens(amountIn,amountOut,[token1,router.WETH(),token2],receiver,deadline)`
> 
> Many Thanks @sabotagebeats , for other tokens, I can swap tokens with `router.swapExactTokensForTokens(amountIn,amountOut,[token1,router.WETH(),token2],receiver,deadline)`, but failed with RFI: still K error.

same to me, any solutions?

**Comment by firstprimecrypto** [comment]
> 
> 
> > > @wuhengzhi
> > > > 1. I have tried swapExactTokensForETH(), or swap RFI to other tokens, it also failed with "execution reverted: UniswapV2: K", since the pool is only RFI -- ETH.
> > > 
> > > 
> > > I'm not sure why you're getting the K error, but you should be able to swap to other tokens through eth with `router.swapExactTokensForTokens(amountIn,amountOut,[token1,router.WETH(),token2],receiver,deadline)`
> > 
> > 
> > Many Thanks @sabotagebeats , for other tokens, I can swap tokens with `router.swapExactTokensForTokens(amountIn,amountOut,[token1,router.WETH(),token2],receiver,deadline)`, but failed with RFI: still K error.
> 
> same to me, any solutions?

Yes, you need to do a 2 hop swap instead of a direct swap.
- First get the 2 trading pairs (like ETH->USDC ad RFI->USDC)
- Then put add those pairs as an array to the route (in the right order)
- And lastly add the 3 token contract addresses to the path object (in the right order)

For ETH->RFI it's something like this. For a sell it's the opposite.
        route = new Route([pair, pair2], weth);
        path = [weth.address, usdc.address, token.address];

**Comment by Raytlty** [comment]
> > > > @wuhengzhi
> > > > > 1. I have tried swapExactTokensForETH(), or swap RFI to other tokens, it also failed with "execution reverted: UniswapV2: K", since the pool is only RFI -- ETH.
> > > > 
> > > > 
> > > > I'm not sure why you're getting the K error, but you should be able to swap to other tokens through eth with `router.swapExactTokensForTokens(amountIn,amountOut,[token1,router.WETH(),token2],receiver,deadline)`
> > > 
> > > 
> > > Many Thanks @sabotagebeats , for other tokens, I can swap tokens with `router.swapExactTokensForTokens(amountIn,amountOut,[token1,router.WETH(),token2],receiver,deadline)`, but failed with RFI: still K error.
> > 
> > 
> > same to me, any solutions?
> 
> Yes, you need to do a 2 hop swap instead of a direct swap.
> 
> * First get the 2 trading pairs (like ETH->USDC ad RFI->USDC)
> * Then put add those pairs as an array to the route (in the right order)
> * And lastly add the 3 token contract addresses to the path object (in the right order)
> 
> For ETH->RFI it's something like this. For a sell it's the opposite.
> route = new Route([pair, pair2], weth);
> path = [weth.address, usdc.address, token.address];

thx，I will have a try

**Comment by moodysalem** [comment]
https://github.com/Uniswap/uniswap-interface/issues/1291 would help with this, I don't see anything specific to address for the interface though since it is usually caused by unexpected behavior in the tokens
