### ISSUE TITLE
src/connectors/NetworkConnector.ts:71 error in production

### ISSUE THREAD

**Issue by AJONCODE** [Uniswap/uniswap-interface#1134]
68 | }
  69 | 
  70 | if (!response.ok) {
> 71 |   batch.forEach(({ reject }) => reject(new RequestError(`${response.status}: ${response.statusText}`, -32000)))
     | ^  72 |   return
  73 | }
  74 |

**Comment by moodysalem** [comment]
This needs more information @AJONCODE 

It seems like there was an error from infura that caused the promise to reject
