### ISSUE TITLE
The transaction cannot succeed due to error: UniswapV2Router: INVALID_PATH. This is probably an issue with one of the tokens you are swapping.

### ISSUE THREAD

**Issue by biume** [Uniswap/uniswap-interface#1137]
**Bug Description**
when i swap the prompt come and show 'UniswapV2Router: INVALID_PATH'

**Additional Context**
i had change the ROUTER_ADDRESS, but the error still prompt , how to resolve it

**Comment by kitchenbeats** [comment]
How did you resolve this?
