### ISSUE TITLE
 problem add token

### ISSUE THREAD

**Issue by MainerAlex** [Uniswap/uniswap-interface#1139]
Hello
problem add token
here is the link to the contract
https://gist.githubusercontent.com/MainerAlex/0506777e1a380808d115404ac318c47a/raw/cfcdd8248bd38fbc478ea7cb53d51f25509ec863/gistfile1.txt

I get the following message in response
Token list failed validation: .tokens[0].address should match pattern "^0x[a-fA-F0-9]{40}$"

how can i add token???

**Comment by MainerAlex** [comment]
https://gist.githubusercontent.com/MainerAlex/b63af8c00aec227885569618a9311a51/raw/73b3456a36d986c2b33072c3f4a0132abcadb9c6/gistfile1.txt

**Comment by moodysalem** [comment]
Address is the token address, not an etherscan url. The message says exactly what the format should be. Please ask in support next time.
