### ISSUE TITLE
RBF transactions are never cleared from the pending transaction queue.

### ISSUE THREAD

**Issue by JFrankfurt** [Uniswap/uniswap-interface#1141]
**Bug Description**
If a user replaces a transaction with a higher fee, the queue of transactions that the UI keeps will not update when the tx nonce is completed by another transaction.

**Steps to Reproduce**
1. broadcast a transaction and don't mine it
2. broadcast a second transaction with the same nonce and mine it
3. observe continually pending tx

**Expected Behavior**
I would expect the UI to realize the user had RBF'd and show the transaction as complete.

**Comment by heyJonBray** [comment]
Looks like the UI should check the transaction with etherscan.io at certain intervals and adjust accordingly.

**Comment by moodysalem** [comment]
Duplicate of https://github.com/Uniswap/uniswap-interface/issues/1016

**Comment by CivelXu** [comment]
I have same issue， How to solve it ?

**Comment by moodysalem** [comment]
> I have same issue， How to solve it ?

Hit `(clear)` in the recent transactions dialog
