### ISSUE TITLE
Unexpected error Please contact support: none  of the calls threw an error 

### ISSUE THREAD

**Issue by kennyfat** [Uniswap/uniswap-interface#1148]
Please how can I solve this.

**Comment by moodysalem** [comment]
Need more information

**Comment by kenniemc** [comment]
I have the exact same problem. What is causing this? And why is the topic closed?

**Comment by amateurCrypt** [comment]
Hey I keep getting this message when i try to swap tokens.
<img width="484" alt="Screen Shot 2020-12-08 at 11 42 05 PM" src="https://user-images.githubusercontent.com/31401279/101586033-09b74d80-39af-11eb-9151-97e8473be072.png">
any idea what could be the issue?

**Comment by moodysalem** [comment]
> Hey I keep getting this message when i try to swap tokens.
> <img alt="Screen Shot 2020-12-08 at 11 42 05 PM" width="484" src="https://user-images.githubusercontent.com/31401279/101586033-09b74d80-39af-11eb-9151-97e8473be072.png">
> any idea what could be the issue?

This can happen when the gas estimation fails, but the interface can't figure out why. Is it reproducible, or sporadic?

**Comment by amateurCrypt** [comment]
it is reproducible, continuously happening on uni v1. What can i do so that gas estimation does not fail?
even tried to increase the slippage to 5%.

**Comment by kenniemc** [comment]
I have read that uni v1 is highly manipulated..? Fake coin liquidity?

ons. 9. dec. 2020 06.47 skrev amateurCrypt <notifications@github.com>:

**Comment by amateurCrypt** [comment]
Is it dangerous to use Uni v1 then?
