### ISSUE TITLE
If any call in the multicall fails, all other calls fail

### ISSUE THREAD

**Issue by moodysalem** [Uniswap/uniswap-interface#1151]
If any call in the multicall fails, all other calls fail. This can cause many issues in the Uniswap interface. E.g. a bad token on the token list can cause balances not to load for many other tokens.

First complete this PR:
https://github.com/makerdao/multicall/pull/7
Then deploy the multicall v2 to all networks
Then update the addresses in the Interface
Then update how we interact with multicall to use this new multicall v2 never-failing call

**Comment by JFrankfurt** [comment]
https://github.com/makerdao/multicall/pull/18/files
