### ISSUE TITLE
Token list updates are too much noise not enough information

### ISSUE THREAD

**Issue by BOR4** [Uniswap/uniswap-interface#1161]
**Is your feature request related to a problem? Please describe.**
Token list updates are not too valuable piece of information as anyone is able to import and edit lists how ever they like. 

**Describe the solution you'd like**
Maybe make "hide token list updates" dialogue and if user selects it never show them again.

**Describe alternatives you've considered**
Remove these updates all together.

**Additional context**
I saw that both twitter and Discord community are not too thrilled about token list updates.

**Comment by moodysalem** [comment]
If someone wanted to disable popups for this, they would just send a PR to remove the add popup lines from here:
https://github.com/Uniswap/uniswap-interface/blob/7cf25ac7c8e2969381ebe71e9a24140902204784/src/state/lists/updater.ts#L57

Major updates would have to be accepted via the manage lists UI
