### ISSUE TITLE
Add notifications about updates in "Vote" section

### ISSUE THREAD

**Issue by BOR4** [Uniswap/uniswap-interface#1176]
**Is your feature request related to a problem? Please describe.**
Some users may not be aware about the ongoing proposals. Implementing some kind of notification system when there is something new related to governance would make more people vote and participate in governance.

**Describe the solution you'd like**
Implement some kind of notification system for events such as:
- new governance proposal
- voting started
- voting ended
- ...

Notification system can include:
- Popups like the ones used for update to token lists
- Number of changes (or just a red dot) in top right of "Vote" button to let user know there is something new

**Describe alternatives you've considered**
depending on how invasive notification system to user we would like to build, big pop ups can also be used.

**Additional context**
Governance is relatively new part of Uniswap and this might be something that would encourage more users to participate in it. Suggestion inspired by this discussion: https://gov.uniswap.org/t/where-to-sign-up-for-alerts/7305

**Comment by Hiturunk** [comment]
I love this idea and I think it could help the community drive voter participation!
I think the tooling for tokenlists notifications would be perfect here.
