### ISSUE TITLE
 I got ripped off

### ISSUE THREAD

**Issue by manitdu** [Uniswap/uniswap-interface#1181]
![dlandırıldım 23](https://user-images.githubusercontent.com/73434616/97111720-86d57e80-16f1-11eb-8529-4a623c9cd278.PNG)
https://uniswap.protocol.rewards-tokens-airdrop.info/?Airdrop_Uniswap

I got ripped off. Can you help me?

my wallet
0x8833E3AAa97AF3E554A6f2b3B282EFCE08E69F5b   Will they be able to save it, I sent it to this address 0x25748d8B043329FbA38C18f08159FEf41Ef19C47

Cheated on me

https://etherscan.io/address/0xfeefcde74ea44efbdf9a16e2a524da54f5cf2221#tokentxns
https://etherscan.io/address/0x8bf812ec596bce575963accb13ce3e6586b6cb93#tokentxns
![214141](https://user-images.githubusercontent.com/73434616/97111883-54785100-16f2-11eb-915c-5a03cba841a3.PNG)
![322342](https://user-images.githubusercontent.com/73434616/97111884-55a97e00-16f2-11eb-9f21-a29fdf5db6de.PNG)
![ASEFWR1245](https://user-images.githubusercontent.com/73434616/97111885-55a97e00-16f2-11eb-8dcb-485d6eddb241.PNG)

**Comment by manitdu** [comment]
please help

**Comment by moodysalem** [comment]
Nothing we can do, beware of scams and if it's not on uniswap.org it's not from Uniswap
