### ISSUE TITLE
Absolute imports

### ISSUE THREAD

**Issue by anxolin** [Uniswap/uniswap-interface#1184]
**Is your feature request related to a problem? Please describe.**
The app doesn't support absolute imports. Within a componentents directories can be nice, but for importing components or utils, you need to include the `../../` in the path.

**Describe the solution you'd like**
Add `baseUrl` in the `compilerOptions` in `tsconfig.js`

```js
{
  "compilerOptions": {
    ...,
    "baseUrl": "src"
  },
...
}
```

More info in https://create-react-app.dev/docs/importing-a-component

I've made this PR #1185 with the suggestion

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by anxolin** [comment]
@moodysalem when do you think my PRs can be reviewed?

**Comment by moodysalem** [comment]
I'm not opposed but also don't necessarily see the benefit if you are using automatic imports in your IDE. And it creates 2 different ways of importing which means we should be consistent.

**Comment by anxolin** [comment]
Thanks for the reply. I think it makes refactors easier. Also, easier to copy paste some imports between files. 
Looks simpler too, so easier to read.

I think within a component, if it has its own directory, is good to use relative to import the subcomponent parts. 

But to import stuff the `constants`, the `theme`,  or some components, it makes it a bit inconvenient to import using `../.../` or `../.../..` depending where you are.

**Comment by moodysalem** [comment]
QQ, what happens if there is a conflict between an absolute import and a node_module import?

**Comment by anxolin** [comment]
I think `src` will take precedence on a conflict. 

Normally there won't be conflicts, since imports will be like `hook/aaaa`, or `data/yyyy`

If you want to do a quick test, you can create the file `src/lodash.ts` with this content:

```ts
export interface Cancelable {
  cancel(): void
  flush(): void
}
```

Then, you can see how src code gets picked first:
```js
import { Cancelable } from 'lodash'
```
