### ISSUE TITLE
Broken trading pair (no liquidity and price is too far gone to rescue the pool cost efficently)

### ISSUE THREAD

**Issue by json10169** [Uniswap/uniswap-interface#1187]
The trading pair for ARM/ETH (https://info.uniswap.org/pair/0x07778771B4972646A3f5Bf0AA7f657026454aEAD) is totally messed up. I was intending on starting the pool as ARM is a very small value token however a legacy pool already exists with no almost ETH left in it and only 90 ARM remaining giving a price per ETH of 90 Quintilian ARM tokens. The price on a centralised exchange would be a few million ARM tokens per ETH. So as far as i can see It would cost thousands of dollars to buy enough ARM tokens to bring the Liquidity up to a reasonable level that would allow the pool to be used and probably a few thousand dollars to buy the ARM tokens out of it to bring the price back in line with the market.

Is there any way to delete this pool so I can start it up with a clean slate and a realistic price? At the moment this pool cannot be used and will not be used ever, even if the ARM token takes off. In fact the higher the price of ARM gets, the more expensive it becomes to rescue the pool from its current condition.

**Comment by moodysalem** [comment]
> Is there any way to delete this pool so I can start it up with a clean slate and a realistic price? At the moment this pool cannot be used and will not be used ever, even if the ARM token takes off. In fact the higher the price of ARM gets, the more expensive it becomes to rescue the pool from its current condition.

No.
You can compute the exact amount in to swap to price using the math from here
https://github.com/Uniswap/uniswap-v2-periphery/blob/master/contracts/examples/ExampleSwapToPrice.sol
