### ISSUE TITLE
bug | claim UNI for liquidity pool

### ISSUE THREAD

**Issue by Kwaskoff** [Uniswap/uniswap-interface#1189]
**Bug Description**
Claim button don't claim UNI

**Steps to Reproduce**
1. Open https://app.uniswap.org/#/uni
2. select UNI 
![image](https://user-images.githubusercontent.com/15308024/97584967-a62e1d80-1a09-11eb-85fb-c2a59bb1d06f.png)
3. Push claim
![image](https://user-images.githubusercontent.com/15308024/97585365-205ea200-1a0a-11eb-8a6d-1d4762cd2095.png)
4. Metamask nothing todo

**Expected Behavior**
Claim button - claim my UNI!!

**Additional Context**
- *test platform 1*
Brave 1.15.76 Chromium: 86.0.4240.111
Metamask 8.0.10
win10
- *test platform 2*
Chromium: 83.0.4103.116 (Debian build)
Metamask 8.0.10
Linuxmint 20

**Comment by moodysalem** [comment]
It should link you to the UNI page where you can claim your UNI and close the modal

**Comment by Kwaskoff** [comment]
> It should link you to the UNI page where you can claim your UNI and close the modal

If I have several pools with UNI rewards - can I make united one transaction for claiming?
