### ISSUE TITLE
Add the ability for custom LP tokens withdraw

### ISSUE THREAD

**Issue by molecula451** [Uniswap/uniswap-interface#1191]
**Is your feature request related to a problem? Please describe.**

It would be nice to have a custom LP Tokens withdraw instead of using the <code> withdraw </code> and take out the whole pools tokens when need

**Describe the solution you'd like**

Add the ability for custom LP tokens withdraw as a long as it is teachable feasible, which it should

**Comment by moodysalem** [comment]
We allow more granular withdrawal than % based, if you click Detailed in the withdraw form. Withdrawing in only one or the other token is not currently planned, if that is what you mean by custom
