### ISSUE TITLE
Proposal page is not responsive

### ISSUE THREAD

**Issue by moodysalem** [Uniswap/uniswap-interface#1192]
**Bug Description**
The proposal page causes horizontal scrolling on small pages

**Steps to Reproduce**
1. Go to https://app.uniswap.org/#/vote/2
2. Make screen small, it scrolls horizontally

**Expected Behavior**
Should not scroll the whole page horizontally, responsive in some way

**Comment by kevinmachstudio** [comment]
I couldn't reproduce this in Brave or Safari browser, which browsers did you see this bug in? Could you take a screenshot?

**Comment by moodysalem** [comment]
![image](https://user-images.githubusercontent.com/7897876/99573587-ea269980-299b-11eb-9de6-e0e19707e6fe.png)

**Comment by WeiLi512** [comment]
Hi @moodysalem 
Could I take this issue to resolve?
The responsive issue is caused by the proposer's address style. setting the word-break property as 'break-all' solved the issue. 
![image](https://user-images.githubusercontent.com/50083174/100764587-9a8ba780-344a-11eb-9e63-524ec1a9d845.png)

**Comment by moodysalem** [comment]
> Hi @moodysalem
> Could I take this issue to resolve?
> The responsive issue is caused by the proposer's address style. setting the word-break property as 'break-all' solved the issue.

Feel free to send a PR!
