### ISSUE TITLE
EasySwap token is showing with incorrect decimal places

### ISSUE THREAD

**Issue by kodekeep4r** [Uniswap/uniswap-interface#1199]
**Bug Description**
EasySwap ($ESWA) token is a 8 decimal places token which was listed in June-14 on Uniswap. When it was listed the decimal places were correctly displayed.

Lately some of our customers have reported that when they want to swap EasySwap, their balances are displayed with more decimal positions than it should be. The error doesn't impact calculated of output coin though.

Contract: 0xA0471cdd5c0dc2614535fD7505b17A651a8F0DAB

**Steps to Reproduce**
1. Go to https://app.uniswap.org/#/swap?outputCurrency=0xA0471cdd5c0dc2614535fD7505b17A651a8F0DAB
2. On field "From"  write the desired amount of Ethereum to simulate a swap (example 1 ETH)

**Expected Behavior**
At current price, expected amount of ESWA to be obtained would be 10,3146 ESWA
In fact, this is the figure presented on the info page:
https://info.uniswap.org/pair/0x8C0e876F1da58140695673D07FF42D4786207D1B

Actual behavior:
Displayed amount of ESWA is: 0.00000103146

**Additional Context**
The issue is reproduceable on all browsers tried so far : Edge and Chrome.

Thanks and kind regards,
EasySwap.

**Comment by moodysalem** [comment]
ESWA is not on the uniswap default token list. If the decimals are incorrect on other token lists, please reach out to those token list maintainers.
