### ISSUE TITLE
When adding list using ENS domain it should allow domains with dashes

### ISSUE THREAD

**Issue by gkucmierz** [Uniswap/uniswap-interface#1200]
**Bug Description**

When adding list using ENS domain it should allow domains with dashes

**Steps to Reproduce**
1. Go to Manage List
2. Click on Add a List
...

**Expected Behavior**

Add button should not be `disabled`

**Additional Context**

<img width="467" alt="Screenshot 2020-11-07 at 07 12 41" src="https://user-images.githubusercontent.com/739084/98433581-ae9ced00-20c8-11eb-9a93-db7c17383bb3.png">

<img width="453" alt="Screenshot 2020-11-07 at 07 12 52" src="https://user-images.githubusercontent.com/739084/98433583-b2c90a80-20c8-11eb-8fb2-9982dbd876cb.png">

**Comment by moodysalem** [comment]
PR will be in the next release
