### ISSUE TITLE
Keep all liquidity pools in sync instead of just hardcoded ones

### ISSUE THREAD

**Issue by 1blockologist** [Uniswap/uniswap-interface#1216]
In reference to this mechanism

https://github.com/Uniswap/uniswap-interface/blob/7fd4005154fbdc8f66f889379c46cf5ba5a3973a/src/constants/index.ts#L15

as reported here:

https://medium.com/dfohub/a-black-hole-in-uniswap-v2s-front-end-router-is-draining-the-value-of-tokens-26f5a459b5d7

all liquidity pools should route against each other. 

Perhaps users can pay in UNI to add additional liquidity pools to routes for specific chosen or user added tokens, which means that you don't have to worry about having your price oracles keep track of every possible combination but just the ones that people care enough about, that liquid enough people care enough about, and you get a subsidy in case there were actual computational costs associated, and you get some consumptive utility of the UNI token which supports your ecosystem.

ka-ching, you're welcome.

**Comment by moodysalem** [comment]
The article's premise doesn't make much sense. If arbitrage between Uniswap pools causes the price of tokens to fall, then so does arbitrage between Uniswap and other exchanges.

The current routing creates small arbitrage opportunities. Arbitrageurs are incentivized by these differences to keep the pair prices in sync. Arbitrageurs pay fees just like everyone else, and this arbitrage opportunity is available if the price moves in either direction.

If you want to improve the routing to make use of more pairs, you can contribute to this PR:  https://github.com/Uniswap/uniswap-interface/pull/1060

The routing in general in the Uniswap interface needs work: https://github.com/Uniswap/uniswap-interface/issues/1071

It also does not aggregate liquidity across different routes (e.g. 50% USDC/ETH + 50% USDC/DAI/ETH), so with perfect routing a large trade will still create arbitrage opportunities.
