### ISSUE TITLE
Adding Cenfura XCF to Uniswap

### ISSUE THREAD

**Issue by jussi01** [Uniswap/uniswap-interface#1223]
Hi All, 

Please add the XCF token to uniswap! :) Web addresses are https://cenfura.com/ and https://xcf-token.io/ and you can find the token currently listed on Liquid (https://app.liquid.com/exchange/XCFUSDC ) and Bilaxy. 

Thanks in advance!

Jussi Schultink
PR and Communications Manager
Cenfura Ltd

**Comment by moodysalem** [comment]
Not the right place for it. See readme.
