### ISSUE TITLE
Uniswap Default List 

### ISSUE THREAD

**Issue by Piechoco** [Uniswap/uniswap-interface#1224]
Hello, 
We have asked several times for our token to be displayed on the Uniswap Default List 
but we haven't heard back from your team. 

Please include TMTG and LBXC in your Default List. 
Currently we have to put the contract address to find the above coins. 
If listing on default list is not possible at least allow it to be searched with the initial TMTG and LBXC. 

Hope to hear back from you soon. 
Thank you.

**Comment by moodysalem** [comment]
This is not the right place for this.

**Comment by moodysalem** [comment]
Please create an issue on the Uniswap default list repository if you have not already.
