### ISSUE TITLE
Remove a token

### ISSUE THREAD

**Issue by ZzikoWang** [Uniswap/uniswap-interface#1226]
Hello there! We have added a few tokens before, and now we want to remove it, can I do this? So that uniswap no longer trades these coins.

zbtoken：0xbd0793332e9fb844a52a205a233ef27a5b34b927
qc:0xe74b35425fe7e33ea190b149805baf31139a8290

**Comment by moodysalem** [comment]
The interface does not whitelist or blacklist any tokens
