### ISSUE TITLE
remove a token

### ISSUE THREAD

**Issue by ZzikoWang** [Uniswap/uniswap-interface#1228]
Hello! We have added a few tokens before, and now we want to remove it, can I do this?
So that uniswap no longer trades these coins.

zbtoken：0xbd0793332e9fb844a52a205a233ef27a5b34b927
qc:0xe74b35425fe7e33ea190b149805baf31139a8290

**Comment by moodysalem** [comment]
You've asked this question before, I closed and deleted the issue. Uniswap does not whitelist or blacklist tokens.

**Comment by moodysalem** [comment]
Furthermore Uniswap _cannot_ do this at the protocol level
