### ISSUE TITLE
Negative commissions on Uniswap liquidity

### ISSUE THREAD

**Issue by Qworum** [Uniswap/uniswap-interface#1236]
Hello. I can't figure it out, can anyone help ... I created a BASE-WETH pair on Uniswap, and the commissions for it went into negative values. And I can't understand how, in general, the exchange fees can go to a negative value. Can someone please explain?
![BASE-WETH](https://user-images.githubusercontent.com/76055242/102229347-5a213480-3ef4-11eb-91ad-f8e47ec5daf4.JPG)

**Comment by callil** [comment]
BASE is a rebasing token and odd things can happen due to its mechanism. This issue is best for the uniswap-info repo.
