### ISSUE TITLE
Old OCEAN token still in uniswap interface

### ISSUE THREAD

**Issue by Schwartz10** [Uniswap/uniswap-interface#1240]
**Bug Description**
I believe the interface is displaying an older version of the ocean token, if so, it should be removed to avoid confusion.

**Steps to Reproduce**
Go to the interface, search for OCEAN, look at the contract address vs `0x967da4048cD07aB37855c090aAF366e4ce1b9F48`

**Comment by moodysalem** [comment]
This issue belongs in default token lists
