### ISSUE TITLE
Noise background image is heavy

### ISSUE THREAD

**Issue by rigwild** [Uniswap/uniswap-interface#1243]
Hi!

When loading Uniswap, a noise background image is loaded: https://github.com/Uniswap/uniswap-interface/blob/master/src/assets/images/noise.png
This image is huge: 1.32MB. A simple compression would make the page load a lot faster.

It is used in this component: https://github.com/Uniswap/uniswap-interface/blob/e835a34d0d53b56b839fa27bc63616a5389fe2e5/src/components/earn/styled.ts#L56-L68

I can do a PR to replace with a compressed version.

**Comment by moodysalem** [comment]
It would be appreciated!

**Comment by moodysalem** [comment]
Better yet, add compression to the build pipeline (if it can be done without ejecting). I'm surprised create-react-app doesn't already do image compression.

**Comment by rigwild** [comment]
Unfortunately I don't know React so I can't help with th	t 😅

**Comment by tylr-r** [comment]
If this still need help I can make a PR
