### ISSUE TITLE
Remove liquidity confirm button does not show any indication of errors

### ISSUE THREAD

**Issue by BOR4** [Uniswap/uniswap-interface#1257]
**Bug Description**
We have increased reports of confirm button doing nothing from time to time. @callil is familiar with the case.

**Steps to Reproduce**
1. Go to remove liquidity
2. Click Confirm
3. *circket sounds*

**Expected Behavior**
Wallet opens to confirm the transaction

**Additional Context**
![image](https://user-images.githubusercontent.com/40821065/103621713-e80d9f80-4f35-11eb-81d9-1b7efcb8d5cc.png)
Here is console log. Hopefully it helps out

**Comment by BOR4** [comment]
Maybe it is not correct reproduction of bug due to user trying to remove CORE liquidity (CORE has some liquidity lock logic in it) ... however I am still posting screenshot for chance it is useful:
![image](https://user-images.githubusercontent.com/40821065/103623433-71be6c80-4f38-11eb-849a-122c45de2aac.png)

**Comment by moodysalem** [comment]
Marked p2 because it is an issue with the `CORE` token specifically

**Comment by Rema161** [comment]
I have had a similar, but I found a way out
Consider increasing the token allowance and slippage by 49% if it doesn't work, follow this video https://www.youtube.com/watch?v=dXsZWbppoSA it helped me a lot

**Comment by CryptoAgents** [comment]
Recently encountered the same problem, cant remove liquidity (v2), found a video in google https://www.youtube.com/watch?v=W22-RuO_iso, it helped me

**Comment by pancakeswap-Uniswap** [comment]
Hi, there was the same error at the moment, I found an up-to-date solution to the problem - https://medium.com/@argentosalick/confirm-not-working-uniswap-be866d4d6400
