### ISSUE TITLE
UI not consistent when coming back to LP screen

### ISSUE THREAD

**Issue by asood123** [Uniswap/uniswap-interface#1268]
**Bug Description**
If you hit back in the LP screen and come back to it, it shows you the amount from the previous screen but not the token. And button shows "Invalid pair"

**Steps to Reproduce**
1. Visit app.uniswap.org and click "Pool"
2. Click "Add Liquidity"
3. Select a second token and hit max (or enter any number on that token)
4. Hit the back arrow on top left and then hit "Add Liquidity" again. 
5. The second token shows "Select a token" but the value is from the previous screen. 

**Expected Behavior**
It should either rest both token choice and amount or remember both

**Additional Context**
![image](https://user-images.githubusercontent.com/6106941/104467789-b96e7500-5584-11eb-9878-6cae112b23ca.png)

**Comment by robert-he** [comment]
was able to reproduce this. bug only appears when clicking "MAX" on second token. of note is when clicking "MAX" on first token and then hitting left arrow, the quantity of the first token does not reset but the token type defaults to ETH. Tested on UNI-ETH pair, clicking "MAX" on UNI as first token, hitting back arrow and "add liquidity" again.

**Comment by callil** [comment]
fixed in https://github.com/Uniswap/uniswap-interface/pull/1237
