### ISSUE TITLE
failed trasaction: bad jump destination

### ISSUE THREAD

**Issue by demibased** [Uniswap/uniswap-interface#1271]
**Bug Description**
Failed transaction bad jump destination during swap lost my coins.

**Steps to Reproduce**
1. Go to ...
2. Click on ...
...

**Expected Behavior**
tried to swap my tokens but transaction failed
![Screen Shot 2021-01-18 at 4 31 03 PM](https://user-images.githubusercontent.com/77645259/104966995-dd2c2380-59a7-11eb-9d3e-239b76ce3b0f.png)

**Additional Context**
Add any other context about the problem here (screenshots, whether the bug only occurs only in certain mobile/desktop/browser environments, etc.)

**Comment by moodysalem** [comment]
Please ask for support in Discord--a bad jump destination is likely an issue with one of the tokens you were swapping
