### ISSUE TITLE
Importing tokens dialogue sometimes too large to show button

### ISSUE THREAD

**Issue by BOR4** [Uniswap/uniswap-interface#1272]
**Bug Description**
Importing tokens sometimes too large to show button

**Steps to Reproduce**
![image](https://user-images.githubusercontent.com/40821065/105186655-3a53e080-5b32-11eb-8625-48d14a9f3f27.png)

**Comment by JFrankfurt** [comment]
@ianlapham did cc2218338873a6ce99f84bec2c962f73ae26a829 fix this?
