### ISSUE TITLE
Token listing

### ISSUE THREAD

**Issue by DJones68** [Uniswap/uniswap-interface#1274]
Hi 

We would like to request that our token JILT (see address below) be listed on Uniswap. We are on Trust wallet and the Saturn exchange. We want to attract users again as we start our new use cases. Thank you for your time. 

https://etherscan.io/token/0xb6957bf56805faed7f1bae30eaebe918b8baff71

**Comment by moodysalem** [comment]
wrong repo
![image](https://user-images.githubusercontent.com/7897876/105422092-c46e7880-5c08-11eb-9650-103c7fb3d47b.png)
