### ISSUE TITLE
No chain id defined

### ISSUE THREAD

**Issue by tatmatt** [Uniswap/uniswap-interface#1283]
**Bug Description**
When I confirm a swap an error message pops up stating no chainid defined.

**Steps to Reproduce**
1. Go to ...swap token
2. Click on ...enter eth amount click confirm
...

**Expected Behavior**
Won’t allow swapping of tokens

**Additional Context**
Happens every time every token

**Comment by Digitalindia001** [comment]
> **Bug Description**
> When I confirm a swap an error message pops up stating no chainid defined.
> 
> **Steps to Reproduce**
> 
> 1. Go to ...swap token
> 2. Click on ...enter eth amount click confirm
>    ...
> 
> **Expected Behavior**
> Won’t allow swapping of tokens
> 
> **Additional Context**
> Happens every time every token

I m facing same problem since yesterday evening with no solution

**Comment by fmrta** [comment]
Same

**Comment by stefanasd** [comment]
I have the Exact issue. 
please What is the solution ?

**Comment by stefanasd** [comment]
![Uploading 00F4AF7F-7E2F-4459-991D-3F373B8969F3.png…]()

**Comment by fmrta** [comment]
![image](https://user-images.githubusercontent.com/77938333/105731384-a61dbb00-5f2f-11eb-9863-4d1a7f380672.png)

**Comment by fmrta** [comment]
Works!

**Comment by callil** [comment]
See comment above - this is a metamask issue, not a uniswap issue.

**Comment by fmrta** [comment]
Still works, and its an uniswap issue also.

**Comment by callil** [comment]
Sorry, but no. It's not. The issue is due to a recent change in Metamask and cannot be fixed in the Uniswap interface.

**Comment by fmrta** [comment]
Anyway, this is the solution to the problem of above.
