### ISSUE TITLE
Uniswap trade status "success" but in Portis wallet still pending?

### ISSUE THREAD

**Issue by breseeg** [Uniswap/uniswap-interface#1284]
Looking for help in solving my issue

I made a trade in uniswap Eth -> Pols using my Portis wallet. Seems like Portis do not support Pols.
Since status is succes in uniswap while pending in Portis im looking to find a way to retrieve my etheriums.

how can I move forward?

Thanks
duda

**Comment by callil** [comment]
@breseeg please contact Portis wallet for support. You may have to add POLS as a custom token but it's better to direct the question to them.
