### ISSUE TITLE
I tried Zapper.fi and I see the liquidity, but it is view only. I can't remove any of it. It says I need to verify the rest of the LP contracts on the blockchain and then burn the tokens to ETH.

### ISSUE THREAD

**Issue by ColetteXArt** [Uniswap/uniswap-interface#1288]
I tried Zapper.fi and I see the liquidity, but it is view only. I can't remove any of it. It says I need to verify the rest of the LP contracts on the blockchain and then burn the tokens to ETH. 

Same thing on APY.vision I also recreated the remove liquidity button in the code. But the LPs show up and when I go to remove them they show 0. it is UNI-CRV pair CRV-CRO UNI-USDC and UNI-ETH they were record high the other day. I have been trying to get help from @uniswap @haydenadams for months. You would think with 1 Billion a day an dependence on a community the people at @uniswap would care more about their community. Or else they will get forked by someone who hires really smart customer service. Seriously guys. I have all the hashes and swaps and LP contracts, can someone please email me back from info@uniswap.org? And not just tell me to go on discord (where people are all asking the same question). Somehow my liquidity was sent to the pool and it is being tracked and I can see it on Etherscan etc, but I think there is a loop in the script, someone at Uni will probably need to help me reassign the liquidity to my address.. I have all the info. I'll try Zapper.fi or the other sites like that, but it doesn't seem to work. Thank you in advance for your help @haydenadams

_Originally posted by @ColetteXArt in https://github.com/Uniswap/uniswap-interface/issues/1259#issuecomment-768099276_

**Comment by moodysalem** [comment]
> And not just tell me to go on discord (where people are all asking the same question).

@ColetteXArt this is the wrong channel to get help, please keep support requests to the Discord. You should be able to find a lot of help in the Discord support channel (including from the developers that use this GitHub). If you cannot withdraw your LP tokens in either zapper.fi or app.uniswap.org, it's likely to be user error--we do not maintain or build zapper.fi. In addition, no one at Uniswap can 'reassign' liquidity to an address. If the liquidity is not at your address and you did not transfer it to another address, then I would recommend you reach out to support to confirm whether your private key has been compromised, but either way there is nothing we can do to help with that specific problem.
