### ISSUE TITLE
Add Rubic $RBC to the default list

### ISSUE THREAD

**Issue by asdener123** [Uniswap/uniswap-interface#1289]
Hi!
My name is Andrey, and I am part of Rubic's marketing team.
Rubic is a multichain DeFi ecosystem, which features cross-chain, P2P, and instant swaps across multiple blockchains, aiming to deliver a complete ONE-STOP decentralized platform.

Our project was created in September 2020 and we are adding new features and improve our platform everyday.  From the start of 2021 $RBC hit the TOP20 tokens on Uniswap (№17 during last week). Rubic's team is in crypto since 2017. We have delivered several successful projects and worked with Binance, TRON, NEO and others.

Our marketing team would like you to add $RBC to the defult search list. RBC$ is already added logo to Uniswap throught TrustWallet. 

By following links you can find more information about our project and tokenomics. 
 
You can read more about our project on the following links:
Rubic: https://rubic.exchange/
Team:https://rubic.exchange/team
One Pager: https://rubic.finance/assets/pdf/OnePager.pdf
White Papper: https://rubic.finance/assets/pdf/WhitePaper.pdf
 
Our social media channels:
Twitter https://twitter.com/CryptoRubic
Telegram https://t.me/cryptorubic_chat
Medium https://cryptorubic.medium.com/
Discord https://discord.gg/zmf9QF2Vuh

**Comment by moodysalem** [comment]
wrong repo, when you create an issue there's a list a token link.
