### ISSUE TITLE
Mobile bottom panel buttons lack margin

### ISSUE THREAD

**Issue by callil** [Uniswap/uniswap-interface#1298]
**Bug Description**
The account and UNI button in the mobile view lack margin. Might be an iOS issue.
To replicate open app.uniswap.org on a mobile browser.

![IMG_10ED96A90417-1](https://user-images.githubusercontent.com/1355319/106359241-5fd5ac80-62df-11eb-9188-6f045e80372c.jpeg)

**Comment by JFrankfurt** [comment]
The css `gap` property (and row/column variants) is not supported in the `display: flex` context by safari. 

I'm fixing this instance here, but there are others. I'll take a look at automated solutions for fixing this that will work w/ `styled-components`.
