### ISSUE TITLE
View Pair Analytics link still redirects to old Uniswap website.

### ISSUE THREAD

**Issue by MicahZoltu** [Uniswap/uniswap-interface#1299]
**Bug Description**
If you click on the View Pair Analytics link at the bottom of a swap, it will take you to https://uniswap.info rather than the new info.uniswap.org.

**Steps to Reproduce**
1. Open the swap interface.
2. Choose two tokens.
3. Click on the View Pair Analytics link.
4. Notice you are taking to a different domain, uniswap.info.

**Expected Behavior**
You are sent to the analytics site hosted by uniswap.org (unsurprising behavior).

**Additional Context**
I was against moving uniswap.info to info.uniswap.org for security reasons, but since that has already been done it no longer makes sense to send users to the external site.

**Comment by moodysalem** [comment]
> I was against moving uniswap.info to info.uniswap.org for security reasons, but since that has already been done it no longer makes sense to send users to the external site.

Not sure why that would be, given consolidating around a single domain is good to condition users against phishing. Agree links should be fixed though.

**Comment by MicahZoltu** [comment]
I was against it because access control of app.uniswap.org (domain name, deployments, etc.) needs to be *far* tighter controlled than to the analytics site.  If someone were to maliciously gain access to app.uniswap.org (via DNS takeover or publishing), the damage they can cause would be orders of magnitude greater than if they gained control of uniswap.info.

By having separate domains, you could allow more people access to .info with less worry, and management could be done more simply (no need for multisigs and such).

**Comment by moodysalem** [comment]
> I was against it because access control of app.uniswap.org (domain name, deployments, etc.) needs to be _far_ tighter controlled than to the analytics site. If someone were to maliciously gain access to app.uniswap.org (via DNS takeover or publishing), the damage they can cause would be orders of magnitude greater than if they gained control of uniswap.info.
> 
> By having separate domains, you could allow more people access to .info with less worry, and management could be done more simply (no need for multisigs and such).

We can just have the same _far tighter_ access control for all our properties and we don't have any scaling issues with that yet. If you want to delegate a subdomain you can do that with NS records.

**Comment by gigilove2001** [comment]
Cheers
