### ISSUE TITLE
Tooltip Performance Optimization 

### ISSUE THREAD

**Issue by WeiLi512** [Uniswap/uniswap-interface#1302]
**Bug Description**
https://github.com/Uniswap/uniswap-interface/blob/9175dd10ccfcdd781a52872642ba0f926741470d/src/components/Popover/index.tsx#L100
Tooltip rerenders every 100ms. Why use the useInterval hook instead of the useTimeout hook? 

**Steps to Reproduce**
https://github.com/Uniswap/uniswap-interface/blob/9175dd10ccfcdd781a52872642ba0f926741470d/src/components/Popover/index.tsx#L100

**Expected Behavior**
I think Tooltip doesn't need to rerender every 100ms.
 
**Additional Context**
Please let me know the reason for using the useInterval hook.

**Comment by moodysalem** [comment]
It only triggers if the popover is rendered, and it's because we use a `'fixed'` strategy which means the position of the popover is not fixed to the element by CSS/HTML but via JavaScript, and the longer this delay the choppier the tracking

**Comment by moodysalem** [comment]
I don't think this causes performance issues atm, most performance issues are related to rendering tokens and other token list state
