### ISSUE TITLE
Trasaction help needed. 

### ISSUE THREAD

**Issue by montechristo55** [Uniswap/uniswap-interface#1309]
Hi,
I used UNISWAP to make two transection using Portis external wallet. Unfortunately I bought issue that are not in Portis range of currencies. I can proof transaction using ethernet. Is there a chance to redirect transaction to new wallet which will service crypto I bought? Any other chance to save that money?
Kind regards,
Christopher

**Comment by moodysalem** [comment]
Please reach out in Discord support.
