### ISSUE TITLE
Portis wallet connection not working

### ISSUE THREAD

**Issue by BOR4** [Uniswap/uniswap-interface#1317]
**Bug Description**
We have lot of users reporting that they can't connect Portis wallet.
Link to reddit post: https://www.reddit.com/r/UniSwap/comments/lhqjo4/portis_wallet_problem/
We had more in Discord as well

It is potentially Portis wallet issues. 1 user wrote:
"I spoke with support finally...

Said they're so overwhelmed with people buying and that the wallet would work eventually and to try again tomorrow. Not much help at all.
"

This is how it looks:
![image](https://user-images.githubusercontent.com/40821065/107744481-09229680-6d13-11eb-91ee-13982a50ec6d.png)
![image](https://user-images.githubusercontent.com/40821065/107744492-0fb10e00-6d13-11eb-8893-4c7040f224e6.png)

On app.uniswap it just keeps loading however Portis itself is unable to show me balance as well.

**Comment by moodysalem** [comment]
Appears to be working now in chrome/mac os for me
