### ISSUE TITLE
UniSwap trade status "success"，balance changed，UI still show pending progress? 

### ISSUE THREAD

**Issue by CivelXu** [Uniswap/uniswap-interface#1340]
**Bug Description**

UniSwap trade status "success"，balance changed，UI still show pending progress? 

**Steps to Reproduce**
1. I tested "https://app.uniswap.org/#/swap" in my DApp broswer
2. I sign and send Tx, and send result to browser  
3. then，UniSwap webpage show transcation submitted.
4. later account balance changed, but bottom still show 1 Pending，until clear it manual。

**Expected Behavior**
1. could receive transcation success
2. pending status could disappear

**Comment by moodysalem** [comment]
Duplicate of https://github.com/Uniswap/uniswap-interface/issues/1016
