### ISSUE TITLE
qubcoins.world and MetaMask problem. Need help.

### ISSUE THREAD

**Issue by githubDen777** [Uniswap/uniswap-interface#1350]
qubcoins.world and MetaMask problem. Need help.

Can not withdraw or unstake my coins.

https://etherscan.io/tx/0x913d14fdf605188ad51fb408b190070c830c36f000ce4e4d13b5bc0d1ede8c14

https://ibb.co/VvJbCVB
https://ibb.co/2PcStJB
https://ibb.co/ByD4M0f
https://ibb.co/4TgZLGR
https://ibb.co/qMV13LJ

Help please!

**Comment by githubDen777** [comment]
Status: **Fail with error 'SafeERC20: low-level call failed'**

Contract 0x6db2819f6882e58552cc94858b707e9d574a77bb 
 **Warning! Error encountered during contract execution [Reverted]**

**Comment by moodysalem** [comment]
That website is not Uniswap, and the smart contract is not Uniswap's either.
