### ISSUE TITLE
Incorrect target amount in swap functionality

### ISSUE THREAD

**Issue by vbhangui** [Uniswap/uniswap-interface#1354]
**Bug Description**
In swap function, the target amount is incorrect for stablecoins.

**Steps to Reproduce**
1. Go to https://app.uniswap.org/#/swap
2. No need to connect wallet
3. Select (say) 2000 LINK as source currency.
4. Select a stablecoin (say) USDC as target currency.
5. Notice the target amount is too low. Screenshot attached.

<img width="1143" alt="Screen Shot 2021-04-02 at 5 41 05 PM" src="https://user-images.githubusercontent.com/16007470/113456387-2b639700-93db-11eb-93d1-c4987c7f7c15.png">

**Expected Behavior**
Correct amount. Currently, its calculating using $0.5 for LINK (when it should be $31)

**Additional Context**
Chrome (v89)
Wallet disconnected

**Comment by moodysalem** [comment]
You must have disable multihop toggled, in the settings

The most liquid route is LINK -> ETH -> USDT
![image](https://user-images.githubusercontent.com/7897876/113592788-398ffe00-95fb-11eb-97a1-48f5e3b79394.png)
