### ISSUE TITLE
Fail with error 'UniswapV2Router: INSUFFICIENT_OUTPUT_AMOUNT'

### ISSUE THREAD

**Issue by Protonumerique** [Uniswap/uniswap-interface#1365]
I had a very normal transaction fail with that message.Fail with error 'UniswapV2Router: INSUFFICIENT_OUTPUT_AMOUNT'.
 Gas Price was charged. What happened? The second time I've had failed transactions with no apparent reason and it's super frustrating... Afraid to use Uniswap again. Just tried to swap Ether with MRCH on https://app.uniswap.org/#/swap. Tr. Hash: 0x8f34fdc6bf7f2a3c87c92a5b26e7b8b4aba3b23cc07b03d96cd3c716d0f13d46

**Comment by sshuyn** [comment]
The same happened to me
0x3642ffe5052811ae08b6a6739eeb0f44dc993e681a11982a12c79cb79eac32f6

**Comment by cryptobull7791** [comment]
i have the same problem using metamask ...
Try to read this:
https://medium.com/dexible/why-do-my-uniswap-txns-keep-failing-1f4f12accd04#:~:text=In%20short%20Uniswap%20transactions%20fail,too%20low%20(leading%20to%20timeout)

**Comment by moodysalem** [comment]
That link provides a good answer, thanks @cryptobull7791 

Please direct support questions like this to the Discord support channel
