### ISSUE TITLE
Worker URL error

### ISSUE THREAD

**Issue by oknoorap** [Uniswap/uniswap-interface#1366]
**Bug Description**
I can't submit approval transaction, when I check dev console, uniswap can't request to worker URL

**Steps to Reproduce**
I just submit transaction, I check the dev console, and it gives me error.

![image](https://user-images.githubusercontent.com/247018/115126877-852fa800-9ffc-11eb-86f2-d01f4bceeaa5.png)

**Expected Behavior**
It should be no error.

**Additional Context**
Here is the screenshot:

![image](https://user-images.githubusercontent.com/247018/115126849-5580a000-9ffc-11eb-9ed2-e0457912dc19.png)

**Comment by moodysalem** [comment]
The error in console is not related. Need more information and screenshots about how the transaction cannot be submitted. Closing until more information is provided.
