### ISSUE TITLE
Issue uniswap web 3 wallet

### ISSUE THREAD

**Issue by Simo0o0** [Uniswap/uniswap-interface#1371]
**Bug Description**
A clear and concise description of the bug.
when opening the uniswap app in web3 especially in coinbase wallet environment via the link below https://app.uniswap.org/#/swap hits the whole web 3 browser in freezing mode. sometimes it takes about few seconds t / m to rule
**Steps to Reproduce**
1. Go to  wallet open interface 
2. Click on  of navigatie to app.uniswap.org of to the new versieon
3. Go to swap of pool. Specifically by swap
4. Try to choose a crypto of coin to swap. The problem will appear. Take long time to load and sometimes freezing. 

...

**Expected Behavior**

**Additional Context**
Add any other context about the problem here (screenshots, whether the bug only occurs only in certain mobile/desktop/browser environments, etc.)

**Comment by moodysalem** [comment]
Which operating system (Android, iOS) and what device?

**Comment by Simo0o0** [comment]
Hi Moody,

It is aan Android samsung s10.

Thank u

Groeten,
Wasim

**Comment by asood123** [comment]
This should be fixed. Please reopen if not.
