### ISSUE TITLE
Coingecko list issue 

### ISSUE THREAD

**Issue by cyruschima** [Uniswap/uniswap-interface#1380]
I went on uniswap recently and my Coingecko list disappeared from uniswap out of the blue. I went on token lists to get the source code to reimport the list and I was met with the error below : "Error importing list".

I checked on reddit and I'm not the only person having this issue

![image](https://user-images.githubusercontent.com/63787483/116813428-b86d4d80-ab4b-11eb-8aae-ce7f884d80a4.png)

**Comment by jochenboesmans** [comment]
This is an issue that only the maintainers of the list can fix:

`Error: Token list failed validation: .tokens[383].symbol should NOT be longer than 20 characters; .tokens[659].symbol should NOT be longer than 20 characters; .tokens[670].symbol should NOT be longer than 20 characters; .tokens[673].symbol should NOT be longer than 20 characters; .tokens[813].symbol should match pattern "^[a-zA-Z0-9+\-%/\$]+$"; .tokens[1765].symbol should NOT be longer than 20 characters; .tokens[2212].symbol should NOT be longer than 20 characters; .tokens[3008].symbol should NOT be longer than 20 characters
    at getTokenList (getTokenList.ts:64)`

**Comment by cyruschima** [comment]
Ok thank you I will try and contact the maintainers of the list and see if they can amend the bug.
