### ISSUE TITLE
"Duplicate Token" error L65 "lists/hooks" - crashes app on duplicate token

### ISSUE THREAD

**Issue by W3stside** [Uniswap/uniswap-interface#1383]
**Bug Description**
As seen today with the WETH duplicate token in the coingecko list, any duplicate token not caught in validation can essentially crash the entire app.

`L65` > `lists/hooks`
```ts
...
const map = list.tokens.reduce<TokenAddressMap>(
    (tokenMap, tokenInfo) => {
      const tags: TagInfo[] =
        tokenInfo.tags
          ?.map(tagId => {
            if (!list.tags?.[tagId]) return undefined
            return { ...list.tags[tagId], id: tagId }
          })
          ?.filter((x): x is TagInfo => Boolean(x)) ?? []
      const token = new WrappedTokenInfo(tokenInfo, tags)
      if (tokenMap[token.chainId][token.address] !== undefined) throw Error('Duplicate tokens.')   <------- Here
      return {
        ...tokenMap,
        [token.chainId]: {
          ...tokenMap[token.chainId],
          [token.address]: {
            token,
            list: list
          }
        }
      }
    },
    { ...EMPTY_LIST }
  )
...
```
`L65`, marked with the comment `<---- Here` should probably just return the `tokenMap` instead, skipping the duplicate token.
I'm aware that there are potential security concerns involved e.g  scam tokens being named differently using another address, but the current solution is a broken app.

**Steps to Reproduce**
1. Checkout d425ff64b44ab4a46df1a9117d885620af6f179a (latest commit as of this writing in `main`)
2. Mainnet
3. App is broken (assuming coingecko list hasn't been auto updated outside of this)
  - broken meaning: slow, trading almost, if not impossible
...

**Expected Behavior**
Shouldn't be broken. Dup tokens should be skipped and app goes on with an error logged in console

**Comment by W3stside** [comment]
I'm doing this with minimal testing but something inside of the `lists.tokens.reduce(...)` above on `L65` could look like:
```ts
...
if (tokenMap[token.chainId][token.address] !== undefined) {
  console.error(new Error(`Duplicate token! ${token.address}`))
  return tokenMap
}
...

which would then log nicely:
![Screenshot from 2021-05-03 17-13-32](https://user-images.githubusercontent.com/21335563/116902344-ebd6d780-ac32-11eb-8c74-e0cb48701c34.png)

Let me know if I should just submit a PR.

**Comment by ianlapham** [comment]
This seems to work - thanks a bunch for checking on this @W3stside
