### ISSUE TITLE
Position list item breaks with long strings

### ISSUE THREAD

**Issue by callil** [Uniswap/uniswap-interface#1393]
If the token symbol is long, the position list item UI will break.

<img width="952" alt="Screen Shot 2021-05-05 at 3 11 50 PM" src="https://user-images.githubusercontent.com/1355319/117196411-70049880-adb4-11eb-8b0f-8269d5fe9767.png">

**Comment by asood123** [comment]
Long names turn into ... and onHover shows you full name
