### ISSUE TITLE
v2 to v3 migration signing failing (Metamask + ledger)

### ISSUE THREAD

**Issue by chtmorris** [Uniswap/uniswap-interface#1396]
This may be a Metamask issue, but I am getting the below signing error as I try to sign to migrate:

_MetaMask Message Signature: Error: Not supported on this device_

Things I have tried:
- I do have contract data set to "Allowed" on the Ledger
- I have updated to the latest version of the app on the Ledger
- I have tried running from different browsers

**Comment by NoahZinsmeister** [comment]
@chtmorris should be fixed by #1397 , feel free to try the deploy preview there, fix will be merged into the main app soon™️
