### ISSUE TITLE
Collecting fees is always initiated with very low gas in Metamask

### ISSUE THREAD

**Issue by BOR4** [Uniswap/uniswap-interface#1417]
**Bug Description**
I tried this twice. Both times in Metamask gas fee was set below 10 which is very low. Not sure if MM or app bug.

**Steps to Reproduce**

1. Go to Pool
2. Click on Collect Fees
3. Suggested gas price is very low

![image](https://user-images.githubusercontent.com/40821065/117115978-17220980-ad8e-11eb-91c0-83fba82eb940.png)

   (this is how it popped up I just screenshotted what it used)

**Expected Behavior**
Have gas price to something reasonable at least

**Comment by moodysalem** [comment]
Given this is a MetaMask issue, and we don't set gas prices from the app (ethers might do something to guess a gas price though), I think it can be closed in favor of a cross-app transaction speed setting
