### ISSUE TITLE
"Unlock Voting" can't display all decimals

### ISSUE THREAD

**Issue by BOR4** [Uniswap/uniswap-interface#1429]
**Bug Description**
Tried to self delegate. Had dust of UNI from adding liquidity. Dialogue couldn't handle the dust

**Steps to Reproduce**

1. Go to "Vote"
2. Click on "Unlock Voting"
3. Self Delegate

![image](https://user-images.githubusercontent.com/40821065/117082810-81fa2300-ad43-11eb-9e7d-7883271b053c.png)

**Expected Behavior**
All decimals fit in.

**Comment by asood123** [comment]
Another number formatting issue
