### ISSUE TITLE
make v3 routes look better

### ISSUE THREAD

**Issue by moodysalem** [Uniswap/uniswap-interface#1430]
![image](https://user-images.githubusercontent.com/7897876/116951144-c22aaa00-ac4c-11eb-8ed5-423deff55c7f.png)

gotta represent the pool fee somehow

**Comment by asood123** [comment]
Closing - already updated. Reopen if more complaints show up.

**Comment by moodysalem** [comment]
we dont show pool fees at all, shouldnt we?
