### ISSUE TITLE
Price inconsistent across Position/AddLiquidity/AddLiquidityToPosition pages

### ISSUE THREAD

**Issue by willpote** [Uniswap/uniswap-interface#1432]
**Bug Description**
Looks like we have different rounding for current price for each of the following pages:

For DAI/ETH 0.3% I'm seeing:
View position page: 3371
Add Liquidity: 3370
Add Liquidity to Existing Position Page: 3371.05

**Steps to Reproduce**
Create a position in one tab.
Click Add Liquidity to that position in another tab.
Create a new position in another tab.

Compare prices

**Expected Behavior**
Same price shown across all screens

**Additional Context**
<img width="674" alt="Screen Shot 2021-05-04 at 6 28 48 PM" src="https://user-images.githubusercontent.com/81638931/117077915-f06cc000-ad06-11eb-998b-ab1706f8cb19.png">
<img width="459" alt="Screen Shot 2021-05-04 at 6 31 15 PM" src="https://user-images.githubusercontent.com/81638931/117077916-f1055680-ad06-11eb-87d6-bf6a4ce39290.png">
<img width="467" alt="Screen Shot 2021-05-04 at 6 31 18 PM" src="https://user-images.githubusercontent.com/81638931/117077917-f1055680-ad06-11eb-9e09-55c346c086e8.png">

**Comment by ianlapham** [comment]
Fixed here 
https://github.com/Uniswap/uniswap-interface/commit/c67e57505acaada8e9ffe5ad5732eb1604cd60b5
