### ISSUE TITLE
Truncate token balances in cases where there is dust

### ISSUE THREAD

**Issue by callil** [Uniswap/uniswap-interface#1434]
Let's truncate to six sig figs. I.e.

`.00000000001123 ETH` should become `< .000001 ETH`

<img width="536" alt="Screen Shot 2021-05-04 at 6 28 21 PM" src="https://user-images.githubusercontent.com/1355319/117078555-16df2b00-ad08-11eb-8511-187399d4143f.png">

**Comment by asood123** [comment]
Another number formatting
