### ISSUE TITLE
Wizard Icon for expert mode missing

### ISSUE THREAD

**Issue by BOR4** [Uniswap/uniswap-interface#1437]
**Bug Description**
A clear and concise description of the bug.

**Steps to Reproduce**

1. Turn on expert mode
2. Wizard Icon is missing

![image](https://user-images.githubusercontent.com/40821065/117070171-ae0aa980-ad2d-11eb-9448-ef66609a38be.png)

**Expected Behavior**
A wise wizard appears that approves of your expert Uniswap skills.

**Comment by ianlapham** [comment]
Okay. Looked into it and wasnt obvious why it wouldnt be happening to you. Gunna close for now but can re-open if more people experience it. Thanks
