### ISSUE TITLE
Source maps don't line up.

### ISSUE THREAD

**Issue by MicahZoltu** [Uniswap/uniswap-interface#1448]
**Bug Description**
When debugging a crash in production, the source maps don't appear to line up properly.

**Steps to Reproduce**

1. Reproduce a crash in production.
2. Notice that when debugging it, the code for each stack line doesn't seem to line up at all with available variables or locations.

**Expected Behavior**
Source maps help, rather than hurt.

**Additional Context**
This is probably just an issue of your build pipeline not properly updating the sourcemaps in the production build.

**Comment by moodysalem** [comment]
we just use create-react-app, but i've noticed this as well debugging dependencies. were you debugging code in the interface or a dependency of the interface?

**Comment by MicahZoltu** [comment]
I don't remember unfortunately.  It was one of the bugs I reported here, and I think I saw you indicate the root cause was a problem with ethers, so maybe a dependency is what I was looking at?

**Comment by moodysalem** [comment]
> I don't remember unfortunately.  It was one of the bugs I reported here, and I think I saw you indicate the root cause was a problem with ethers, so maybe a dependency is what I was looking at?

yep, that's where i was having issues with source maps too. probably an issue with the ethers source maps i think

**Comment by moodysalem** [comment]
closing unless we discover it's an issue with all source maps
