### ISSUE TITLE
Poor Firefox performance

### ISSUE THREAD

**Issue by brockelmore** [Uniswap/uniswap-interface#1449]
**Bug Description**
First paint occurs 5 seconds after going to the site

**Steps to Reproduce**
Im on arch linux firefox, v88

**Expected Behavior**
I wanna go fast Ricky Bobby

**Additional Context**
Here is the network trace:
![image](https://user-images.githubusercontent.com/31553173/117234968-f5f40400-adf3-11eb-86f9-c8d1f5de40d6.png)

Here is a call tree from a performance recording:
![image](https://user-images.githubusercontent.com/31553173/117235148-2c318380-adf4-11eb-9d06-6480b55f0084.png)

Here is a ~300ms GC call on loading the page caused by Too Many Allocations:
![image](https://user-images.githubusercontent.com/31553173/117235290-7450a600-adf4-11eb-97cc-e67ac955abd4.png)

Here is a ~450ms Dom event:
![image](https://user-images.githubusercontent.com/31553173/117235669-24beaa00-adf5-11eb-875d-30f3f5d1a1b9.png)

Mostly caused by this Event handler (but sourcemappings aren't working for me):
![image](https://user-images.githubusercontent.com/31553173/117235898-9991e400-adf5-11eb-8064-2dcd1208ec30.png)

Here is a function call that took 5.3 seconds, mostly with a ton of GC:
![image](https://user-images.githubusercontent.com/31553173/117236159-2d63b000-adf6-11eb-8c91-bc8ad86bb679.png)

**Comment by brockelmore** [comment]
Looks like its coming from this function:
```js
export default function _objectSpread2(target) {
  for (var i = 1; i < arguments.length; i++) {
    var source = arguments[i] != null ? arguments[i] : {};

    if (i % 2) {
      ownKeys(Object(source), true).forEach(function (key) {
        defineProperty(target, key, source[key]);
      });
    } else if (Object.getOwnPropertyDescriptors) {
      Object.defineProperties(target, Object.getOwnPropertyDescriptors(source));
    } else {
      ownKeys(Object(source)).forEach(function (key) {
        Object.defineProperty(target, key, Object.getOwnPropertyDescriptor(source, key));
      });
    }
  }

  return target;
}
``` 
in https://app.uniswap.org/static/node_modules/babel-preset-react-app/node_modules/@babel/runtime/helpers/esm/objectSpread2.js & a similar function in https://app.uniswap.org/static/node_modules/babel-preset-react-app/node_modules/@babel/runtime/helpers/esm/defineProperty.js

**Comment by piavgh** [comment]
@brockelmore : I met this issue yesterday, 

After debugging, I also found this function `listToTokenMap`, but I thought (maybe I was wrong) that what causes the performance overhead is:

```
export function validateAndParseAddress(address: string): string {
  try {
    const checksummedAddress = getAddress(address) <== I thought it's because of this line
    warning(address === checksummedAddress, `${address} is not checksummed.`) 
    return checksummedAddress
  } catch (error) {
    invariant(false, `${address} is not a valid address.`)
  }
}
```

Someone also had this issue https://github.com/Uniswap/uniswap-interface/issues/1466

**Comment by moodysalem** [comment]
> @brockelmore : I met this issue yesterday, 
> 
> 
> 
> After debugging, I also found this function `listToTokenMap`, but I thought (maybe I was wrong) that what causes the performance overhead is:
> 
> 
> 
> ```
> 
> export function validateAndParseAddress(address: string): string {
> 
>   try {
> 
>     const checksummedAddress = getAddress(address) <== I thought it's because of this line
> 
>     warning(address === checksummedAddress, `${address} is not checksummed.`) 
> 
>     return checksummedAddress
> 
>   } catch (error) {
> 
>     invariant(false, `${address} is not a valid address.`)
> 
>   }
> 
> }
> 
> ```
> 
> 
> 
> Someone also had this issue https://github.com/Uniswap/uniswap-interface/issues/1466
> 
> 

i will look into this today, it is likely from our parsing of token list data into tokens instances. we could do this conversion lazily

**Comment by piavgh** [comment]
@moodysalem : Hi, I see your PR here: https://github.com/Uniswap/uniswap-interface/pull/1472/files

Is it finalized?

**Comment by moodysalem** [comment]
@brockelmore please let me know if you are still seeing performance issues, they should be mostly resolved
