### ISSUE TITLE
Connecting a Coinbase Wallet results in a blank page

### ISSUE THREAD

**Issue by edwardpassagi** [Uniswap/uniswap-interface#1450]
**Bug Description**
Connecting Coinbase Wallet to Uniswap leads to a blank page.

Reproduce:
1. Go to: https://app.uniswap.org/#/swap
2. Click "Connect Wallet"
3. Select "Coinbase Wallet"
4. _If it shows the QR:_ scan the QR code. Upon successful load, it still redirects to a blank page still

**Expected Behavior**
First time using Uniswap with Coinbase Wallet.

**Additional Context**
Bug occurs in Windows 10 Chrome, Mozilla, Edge. Safari for iOS also shows the same bug.

**Comment by moodysalem** [comment]
fixed for now in https://github.com/Uniswap/uniswap-interface/releases/tag/v3.2.23
