### ISSUE TITLE
when the interface crashes, show a link to report the crash to github instead of a whitescreen

### ISSUE THREAD

**Issue by moodysalem** [Uniswap/uniswap-interface#1452]
when the app crashes the screen goes white because react unmounts the entire app

https://reactjs.org/docs/error-boundaries.html

we should instead handle the error at least at the top level and show a link to report the issue to github with some pre-filled in details about where the crash happened and the stack trace

**Comment by AbstractAlao** [comment]
Yeah I'm getting the same issue on the v3 version

**Comment by jochenboesmans** [comment]
It's probably also a good idea for the sake of UX to have lower level error boundaries as well so that if, for example, an error is thrown inside some swap UI component, the user is still able to use header navigation etc. to interact with the working parts of the application.
