### ISSUE TITLE
Is the quote/base display in reverse in add position page?

### ISSUE THREAD

**Issue by callmewhy** [Uniswap/uniswap-interface#1453]
When set price range or display current range, the price seems wrong.
Take ETH/USDT as an example. 

![image](https://user-images.githubusercontent.com/6276527/117333109-2f4b7300-aecb-11eb-8751-9591d83b92cb.png)

As the ETH is base token and USDT is quote token, should the value be 1 ETH = ? USDT instead of 1 USDT = ? ETH?

For ETH/USDT, the value should be 3590 instead of 0.000279.

Can I create a PR to fix that? Or is that by design?

**Comment by jochenboesmans** [comment]
This notation is correct. It essentially tells you you get 0.000279 ETH per USDT. The inverse price would be 3590 USDT per ETH.

**Comment by callmewhy** [comment]
Oh it means 0.000279 ETH per USDT. Make sense to me. Just inverse compared with common usage, such as what we see in Binance:
 
![image](https://user-images.githubusercontent.com/6276527/117343955-6fb0ee00-aed7-11eb-9b09-a168b0f1280f.png)

**Comment by callmewhy** [comment]
Should we swap the quote and base token to follow most common practice?

**Comment by asood123** [comment]
This is interesting - we looked around and realize how this can be confusing. Will clarify on the UI.

**Comment by asood123** [comment]
One proposal:
- Change TOKEN_1 / TOKEN_2 => TOKEN_1 per TOKEN_2 (like in v2)
- In titles, flip to TOKEN_2 / TOKEN_1

Downsides of introducing "per" is potentially translation issues and how it appears in different languages

**Comment by callmewhy** [comment]
It looks good. flip to TOKEN_2 / TOKEN_1 is much better for title. And Xxxx Token1 per Token2 is more readable if it's in one row. Hope we can align the naming with common convention :)
