### ISSUE TITLE
Header tabs misaligned on medium screens

### ISSUE THREAD

**Issue by callil** [Uniswap/uniswap-interface#1455]
<img width="432" alt="Screen Shot 2021-05-06 at 2 48 22 PM" src="https://user-images.githubusercontent.com/1355319/117350101-28e0db00-ae7a-11eb-87e8-89dcd1ebd50b.png">

**Comment by justindomingue** [comment]
@callil Obsolete after #1505?

The HeaderLinks bar was moved to the flex-end.

Of note, we could have used grid-template-columns: 1fr auto 1fr to always keep the bar centered.
