### ISSUE TITLE
WETH not in "common bases" tokens

### ISSUE THREAD

**Issue by zimbabwean-inflation** [Uniswap/uniswap-interface#1465]
**Is your feature request related to a problem? Please describe.**
WBTC, ETH, USDC, DAI, USDT but not WETH
Weth, at least in V2, saves like 20% on gas

**Describe the solution you'd like**
Add WETH... 

**Describe alternatives you've considered**
typing weth manually
![Capture d’écran de 2021-05-06 21-42-08](https://user-images.githubusercontent.com/77246349/117385932-fe137880-aeb3-11eb-8664-65fa567907a4.png)

**Additional context**

**Comment by asood123** [comment]
This is by design - we think adding WETH can be confusing. We plan to change this to favorites: https://github.com/Uniswap/uniswap-interface/issues/1474
