### ISSUE TITLE
NFT SVG animation hogs CPU

### ISSUE THREAD

**Issue by zimbabwean-inflation** [Uniswap/uniswap-interface#1466]
**Bug Description**
The SVG NFT (liq. position) is very nice but it's heavy on CPU usage !
Hogs like 60% of CPU on latest Firefox/OS X MacBook Air M1 (!!!!)
and most of CPU under an older Ubuntu laptop on a 4th gen i5....

**Steps to Reproduce**

   ...

**Expected Behavior**
Make it optional

**Additional Context**
I really had to block it manually using a plugin. It would make my laptop overheat.

**Comment by piavgh** [comment]
I also have high CPU usage, but not sure if it's because of the NFT SVG or not.
CPU goes up to more than 100%, especially when I open the browser's developer console

I'm using Macbook pro 16 inch

**Comment by moodysalem** [comment]
we should disable animation unless user is hovering the svg. the issue is likely the multiple layer effects combined with the 60 fps animation
