### ISSUE TITLE
Unable to create liquidity pair in V2 after launching V3 pair first

### ISSUE THREAD

**Issue by mikyjo** [Uniswap/uniswap-interface#1473]
**Bug Description**

I'm unable to provide liquidity for a new pair in V2 after I have previously supplied the said pair in V3.

To illustrate with an example:

1. Go to Uniswap V3 and add liquidity for your new pair (ETH-TOKEN) which didn't exist on V2 and V3
2. After the V3 liquidity has been successfully added, go to Uniswap V2 and add liquidity for the same pair (ETH-TOKEN)

**Expected behavior**

I should be able to successfully create liquidity for my new pair in V2.

**Actual behavior**

Unexpected slippage error is shown.

**Additional Context**

Manually specifying the slippage percentage from the settings in V2 pool doesn't resolve the issue.
The amount of tokens that are being supplied, or price range is not relevant.

Here are a few screenshots from the Dev tools on V2:

![Slippage error](https://user-images.githubusercontent.com/80850454/117466929-e42d7080-af5b-11eb-86ad-97bfff314fa6.png)

![Liquidity console error](https://user-images.githubusercontent.com/80850454/117466951-e98abb00-af5b-11eb-9c96-b3f14e8253dd.png)

**Comment by allianceblock-max** [comment]
I think the error is unrelated to having liquidity in the V3 pair first.
This is reproducible when trying to add liquidity to a new V2 pair, regardless of whether it's been registered through V3.

**Comment by moodysalem** [comment]
looks like it's probably the denominator check. we should check the actual bounds not the values of the denominator/numerator. my error when refactoring i think

**Comment by mikyjo** [comment]
> What token are you trying to add?

Sorry for the delayed response. The pair is ETH-ISP (Ispolink).
But, judging from the other replies, you guys probably have an idea where the problem might be.
Thanks!
