### ISSUE TITLE
Viewing ATARI/ETH pool causes a white screen

### ISSUE THREAD

**Issue by AbstractAlao** [Uniswap/uniswap-interface#1486]
**Bug Description**
The UI crashes and goes to a white screen when viewing [ATARI/ETH Pool](https://app.uniswap.org/#/pool/4494)
I was able to initially add liquidity but when trying to view the position it errors out and fails on https://app.uniswap.org/static/js/state/claim/hooks.ts
It fails on the fetchClaim

**Steps to Reproduce**
This might be related to this specific pool
1. Go to [ARARI/ETH Pool](https://app.uniswap.org/#/pool/4494)
2. Page errors out
   ...

**Expected Behavior**
Should be able to see a current position in the pool and other stats.

**Additional Context**
![image](https://user-images.githubusercontent.com/58517851/117589101-98aeca00-b0f5-11eb-8f62-cc0465140e19.png)

**Comment by ianlapham** [comment]
fixed in https://github.com/Uniswap/uniswap-interface/commit/b6bd59f2b1373ee0b39e29d82feb374724509c25
