### ISSUE TITLE
Cant add liqudity on Unisawp V2 

### ISSUE THREAD

**Issue by Daniel28127** [Uniswap/uniswap-interface#1487]
**Bug Description**
i can't add liquidity on uniswap v2. (Kovan testnet)

**Steps to Reproduce**

1. Go to ...
2. Click on ...
   ...

**Expected Behavior**
I would like to add liquidity normally, but its stops on confirm button, on Uniswap. cant even switch to Metamask for confirmation. 

**Additional Context**
its stops here, 
![test](https://user-images.githubusercontent.com/70231013/117617946-8ec8ad80-b16d-11eb-8fd0-fa7c532331b0.jpg)

**Comment by NoahZinsmeister** [comment]
should be fixed in 57786335df45ce384a38ea9c6046e2b6a0ad2115
