### ISSUE TITLE
Wallet Connect "copy to clipboard" not working

### ISSUE THREAD

**Issue by Hephyrius** [Uniswap/uniswap-interface#1488]
**Bug Description**
When you click "copy to clipboard" the wallet connect URI is not copied.

**Steps to Reproduce**

1. Go to app.uniswap.com
2. Click on "connect wallet"
3. Click "wallet connect"
4. Click "copy to clipboard"

**Expected Behaviour**
The wallet connect URI should be copied to the clipboard.

**Additional Context**
The correct URI is printed in the browser console, which can be used in a wallet connect enabled app.

Attempted on multiple devices and confirmed not working on:
Chrome Android
Chrome Windows
Firefox Windows
Microsoft Edge Windows

**Comment by moodysalem** [comment]
p0 since it prevents use by gnosis safe

**Comment by ianlapham** [comment]
@moodysalem Think this is some iframe permissions thing going on within the Wallet Connect provider?

**Comment by willhennessy** [comment]
Checking on p0s - can we squash this today or tomorrow?
