### ISSUE TITLE
Approve button text overflows on smaller screens

### ISSUE THREAD

**Issue by callil** [Uniswap/uniswap-interface#1496]
We will need to adjust the copy on these buttons for smaller screens.

![image](https://user-images.githubusercontent.com/1355319/117707226-4e345880-b19c-11eb-821c-eddca012e320.png)

**Comment by OMGspidertanx** [comment]
Would it be sufficient to just prevent the tooltip icon from wrapping, like below? Though as it currently is it is tricky to trigger the tooltip on mobile without also triggering the swap.
![uniswap](https://user-images.githubusercontent.com/81343175/118067103-e897c600-b36d-11eb-9054-ce9877bd604e.png)

**Comment by nailordeanna** [comment]
Sent from Yahoo Mail on Android 
 
  On Wed, May 12, 2021 at 10:05 PM, ***@***.***> wrote:   


Would it be sufficient to just prevent the tooltip icon from wrapping, like below? Though as it currently is it is tricky to trigger the tooltip on mobile without also triggering the swap.
