### ISSUE TITLE
Swap error message is too verbose

### ISSUE THREAD

**Issue by callil** [Uniswap/uniswap-interface#1507]
![image](https://user-images.githubusercontent.com/1355319/117859544-235e0900-b25d-11eb-8779-ede38a9dd0bc.png)

I know we are aware of this issue but wanted to track it. See also #1330

**Comment by justindomingue** [comment]
is the solution to remove everything inside the parens?

**Comment by moodysalem** [comment]
> is the solution to remove everything inside the parens?

in the swap callback code we should be parsing this error and returning a better string. search for "Uniswap: K"

**Comment by moodysalem** [comment]
this error work is being tracked here https://github.com/Uniswap/uniswap-interface/issues/1560
