### ISSUE TITLE
Bring back expected output

### ISSUE THREAD

**Issue by asood123** [Uniswap/uniswap-interface#1535]
Currently showing minimum output. 

Bring back expected output for the main number and rework confirm screen. 

For example, the negative number in green is confusing.

![image](https://user-images.githubusercontent.com/6106941/118017973-389e6a80-b325-11eb-966a-403994b88526.png)

**Comment by moodysalem** [comment]
that negative number being green is just a bug

**Comment by moodysalem** [comment]
> that negative number being green is a separate bug

i just addressed it in https://github.com/Uniswap/uniswap-interface/commit/27094c87f28bed497edc3f7838833e8209a4e945

**Comment by asood123** [comment]
Why is the difference so large for such a small trade?

**Comment by moodysalem** [comment]
> Why is the difference so large for such a small trade?

in the screenshot it's a multihop bc arbitrage and the fees added up
