### ISSUE TITLE
yarn start fails on Windows 10 with "Command failed with exit code 255"

### ISSUE THREAD

**Issue by GiorgiSheklashvili** [Uniswap/uniswap-interface#1542]
**Bug Description**
When I'm trying to run the project on Windows 10, I'm receiving this error - "'v3-periphery)' is not recognized as an internal or external command,"

**Steps to Reproduce**
On Windows 10 machine
1. run yarn
2. run yarn start

**Expected Behavior**
Project running successfully

**Additional Context**
I've tried on Mac OS and it's running there without a problem

**Comment by lukedonato** [comment]
Windows doesn't like the single quotes in the typechain commands.

Change 
`"compile-external-abi-types": "npx typechain --target ethers-v5 --outDir src/abis/types './src/abis/**/*.json'",` 
to 
`"compile-external-abi-types": "npx typechain --target ethers-v5 --outDir src/abis/types \"./src/abis/**/*.json\"",`

and

`"compile-v3-contract-types": "npx typechain --target ethers-v5 --outDir src/types/v3 './node_modules/@uniswap/?(v3-core|v3-periphery)/artifacts/contracts/**/*.json'",` 
to 
`"compile-v3-contract-types": "npx typechain --target ethers-v5 --outDir src/types/v3 \"./node_modules/@uniswap/?(v3-core|v3-periphery)/artifacts/contracts/**/*.json\"",`

**Comment by moodysalem** [comment]
Please send a PR! I would recommend using WSL though

**Comment by GiorgiSheklashvili** [comment]
Yes, I think I will switch to WSL or use VirtualBox.
So changing single quotes worked but then other problem came up on windows
`Delete `␍`  prettier/prettier for .tsx and .ts files.` 
I tried this answer [Link](https://stackoverflow.com/a/53769213) but it didn't work.
Should I create PR without fixing this problem?

**Comment by moodysalem** [comment]
sounds like a linting error with whatever file you changed

**Comment by GiorgiSheklashvili** [comment]
![image](https://user-images.githubusercontent.com/9293826/118298013-967ab000-b4e7-11eb-8b01-2ef6ff3536bb.png)
It complains about .ts and .tsx files, I changed only package.json and it didn't raise an error about it.

**Comment by moodysalem** [comment]
ah CR, for carriage return. sounds like a line endings thing with windows.

https://prettier.io/docs/en/options.html#end-of-line

I prefer:

> Add * text=auto eol=lf to the repo’s .gitattributes file. You may need to ask Windows users to re-clone your repo after this change to ensure git has not converted LF to CRLF on checkout.

**Comment by GiorgiSheklashvili** [comment]
Actually, it will be way easier to use WSL or VirtualBox for the long term, thanks

**Comment by Times125** [comment]
> "npx typechain --target ethers-v5 --out-dir src/types/v3 \"./node_modules/@uniswap/?(v3-core|v3-periphery)/artifacts/contracts/**/*.json\""

it works! thanks!
