### ISSUE TITLE
Initiate Trade Animation

### ISSUE THREAD

**Issue by MAkzent** [Uniswap/uniswap-interface#155]
I'm working with @chikeichan on the frontend and have a UX improvement suggestion:

When a user successfully initiated a trade, the only indication is the 'pending' box on the top-right: 
![image](https://user-images.githubusercontent.com/8077131/49137632-639ccb80-f330-11e8-80cf-f5b428196b02.png)

It took me 3-5s to find the pending box while thinking 'did it work?'.

To reduce noise in the user's head, I think we should add a little animation / modal once a user successfully initiated a trade. Instead on the sidebars, the animation / modal should cover the input section of the app. Since the user's eyes are on this part of the page, it makes more sense imo to give visual feedback there.

**Comment by chikeichan** [comment]
I think having the CTA button turning green with a white check mark would be pretty nice. It catches the user's attention since they just clicked on the button, and it's less intrusive than a modal

**Comment by callil** [comment]
I like that idea a lot @chikeichan
