### ISSUE TITLE
App crashes when selecting "shibaken" token

### ISSUE THREAD

**Issue by jab416171** [Uniswap/uniswap-interface#1551]
**Bug Description**
App crashes when selecting [shibaken](https://etherscan.io/address/0xa4cf2afd3b165975afffbf7e487cdd40c894ab6b) token

**Steps to Reproduce**

1. Go to uniswap
2. Have shibaken in your wallet
3. Enter shibaken for the token and try to swap
   ...

**Expected Behavior**
App lets you swap

**Additional Context**
See examples here:
![image](https://user-images.githubusercontent.com/345752/118047719-66d97580-b338-11eb-8594-307e52d157dd.png)
![image](https://user-images.githubusercontent.com/345752/118047733-6e008380-b338-11eb-942d-32ddba73a979.png)

**Comment by jab416171** [comment]
Same issue with mshib:
![image](https://user-images.githubusercontent.com/345752/118049439-f8e27d80-b33a-11eb-8131-02e2272858d2.png)

**Comment by jab416171** [comment]
Same issue with "smooth love" (0xcc8fa225d80b9c7d42f96e9570156c65d6caaa25)

**Comment by moodysalem** [comment]
fixed by https://github.com/Uniswap/uniswap-interface/commit/7d45ff5ca8fb3c512d89875ba97d1c57e7a72219 releasing now
