### ISSUE TITLE
Sort and hide inactive positions by default in pools overview

### ISSUE THREAD

**Issue by callil** [Uniswap/uniswap-interface#1564]
Add a toggle on the top right of the positions list that hides/shows inactive positions.

Additionally, add a small button on the bottom of the list if there are hidden positions that says `N more inactive positions` that when clicked also expand the list to include those inactive positions.

**Comment by willhennessy** [comment]
this is released and we're tracking UX polish in https://github.com/Uniswap/uniswap-interface/issues/1705
