### ISSUE TITLE
Unclaimed fees reduced 

### ISSUE THREAD

**Issue by BOR4** [Uniswap/uniswap-interface#1581]
**Bug Description**
User noticed his unclaimed fees reduced in v3. As far as I see he didn't claim any of them so it is really strange.

**Steps to Reproduce**

previous day screenshot:
![image](https://user-images.githubusercontent.com/40821065/118339879-79aba000-b51a-11eb-8151-a85d0c887531.png)

screenshot day after:
![image](https://user-images.githubusercontent.com/40821065/118339900-8b8d4300-b51a-11eb-8d1e-75b032265636.png)

NFT id: 621
address: https://etherscan.io/address/0x3ebbc23c762a032a90f7bdcba5840df063aed60e

**Expected Behavior**
Fees only go up!

**Additional Context**
escalated ticket in Discord #ticket-kameronov

**Comment by NoahZinsmeister** [comment]
fixed by https://github.com/Uniswap/uniswap-interface/commit/f5fc5da34123f7dd7f41f978bb8c79d193f289ca
