### ISSUE TITLE
Why not anymore using IPFS' DNSLink?

### ISSUE THREAD

**Issue by DaniellMesquita** [Uniswap/uniswap-interface#1598]

**Comment by DaniellMesquita** [comment]
I'm using IPFS Companion and app.uniswap.org isn't anymore redirecting to DNSLink.

**Comment by DaniellMesquita** [comment]
Its still on IPFS, through IPNS: http://uniswap.eth.ipns.localhost:8080/#/swap

**Comment by willhennessy** [comment]
Hi Daniell, we are still using DNSLink: https://github.com/Uniswap/uniswap-interface/blob/897f3542022d2a02839552923be941c19df8b2aa/.github/workflows/release.yaml#L71

**Comment by feld** [comment]
Can I reopen this? **_dnslink.app.uniswap.org** has had no published TXT record for quite a while now and your ENS record still has the ContentHash
