### ISSUE TITLE
UI displaying wrong share of liquidity pool

### ISSUE THREAD

**Issue by jab416171** [Uniswap/uniswap-interface#1612]
**Bug Description**
UI displaying wrong share of liquidity pool
**Steps to Reproduce**

Add more than 1% liquidity to an existing pool, ui will say <0.01%

**Expected Behavior**
UI correctly shows the share

**Additional Context**
 https://gyazo.com/2812f22a490c4f092ef67b07c668e1a3 https://gyazo.com/dfef30fb7bfac1adb080c61b590e2194

**Comment by justindomingue** [comment]
Doesn't the second screenshot say 1.99 ETH ? 2 ETH <<< 716K liquidity. Seems WAI?

**Comment by jab416171** [comment]
My rough math (2/161 and 22395/1470357) says they should own around 1.2-1.5% of the liquidity

**Comment by jab416171** [comment]
https://v2.info.uniswap.org/token/0x0e58ed58e150dba5fd8e5d4a49f54c7e1e880124

**Comment by folkdeezy** [comment]
Hi, i am the guy who sent jab this data.  i never confirmed adding the LP because of this UI issue, i was concerned it would glitch and id take a 99% loss on my LP right away.  can you please advise?  should i not confirm a tx that says this?  does it pose a risk to my funds?

**Comment by amenomurakumo0401** [comment]
The following screen was displayed when the metamask was connected. How is this situation?
![image](https://user-images.githubusercontent.com/79516731/118662798-407d7380-b82b-11eb-8409-c31dd3dfbd8a.png)

**Comment by jab416171** [comment]
@amenomurakumo0401 this is unrelated to this issue, please open a new ticket
