### ISSUE TITLE
Making adding liquidy UI more intuitive.

### ISSUE THREAD

**Issue by chitranjanbaghi** [Uniswap/uniswap-interface#1640]
#FeatureRequest
![ui change](https://user-images.githubusercontent.com/11886307/118734843-db427600-b85c-11eb-8653-a1c558f1eb5f.png)

can you guys show the liquidity graph right where the option to add liquidity is?

and the pink color bar which shows the current price, can we have different color bars which show at which point does the bar exists for the liquidity provider, so he sees the range graphically?

because this new update has messed up intuitive interaction with the uni swap.

**Comment by willhennessy** [comment]
yes! we're designing a new flow for this right now. stay tuned and thank you for the feedback chitran :)
