### ISSUE TITLE
Unable to add liquidity in Uniswap V2 

### ISSUE THREAD

**Issue by Daniel28127** [Uniswap/uniswap-interface#1660]
**Bug Description**
Unable to add liquidity in Uniswap v2, its start today, yesterday i normaly make some test on kovan, today i cant. 

**Steps to Reproduce**

**Expected Behavior**
Expect to add them, but i cant, i try make some testo on kovan and nothing, everythins show img bellow. 

**Additional Context**

https://ibb.co/QpXfqrH

**Comment by justindomingue** [comment]
most likely due to this https://github.com/Uniswap/uniswap-interface/pull/1652

**Comment by justindomingue** [comment]
#1662
