### ISSUE TITLE
insufficient input amount when adding liquidity to v2 for a new token

### ISSUE THREAD

**Issue by jab416171** [Uniswap/uniswap-interface#1662]
**Bug Description**
User is unable to add liquidity to v2

**Steps to Reproduce**

1. Go to https://app.uniswap.org/#/add/v2/ETH
2. Try to add liquidity with a new token (not sure if it's specific to certain tokens or not, the two users are using different tokens)

**Expected Behavior**
Liquidity is able to be added

**Additional Context**
I see there was a fix put in with 307a995, I had the two users test with https://uniswap-interface-git-main-uniswap.vercel.app/ and they still get the insufficient input amount error.
![image](https://user-images.githubusercontent.com/345752/119018644-8b95a480-b959-11eb-9a9e-b4a1dad167d4.png)
![image](https://user-images.githubusercontent.com/345752/119018658-8e909500-b959-11eb-90e0-4a7e53ec6488.png)

**Comment by moodysalem** [comment]
Can you try yesterday's release to confirm it was a bug in the latest changes?
https://github.com/Uniswap/uniswap-interface/releases/tag/v3.3.5

**Comment by sunrisepopov** [comment]
@moodysalem , `v3.3.5` - this version seems working fine.

**Comment by jab416171** [comment]
Confirmed that it works with the previous release

**Comment by vaxo-gg** [comment]
> Can you try yesterday's release to confirm it was a bug in the latest changes?
> https://github.com/Uniswap/uniswap-interface/releases/tag/v3.3.5

yes, it's working fine with previous release

**Comment by Daniel28127** [comment]
> > Can you try yesterday's release to confirm it was a bug in the latest changes?
> > https://github.com/Uniswap/uniswap-interface/releases/tag/v3.3.5
> 
> yes, it's working fine with previous release

We need to wait for new release, or?

**Comment by justindomingue** [comment]
Reverting a PR committed yesterday to unblock prod.

Should still not work: https://uniswap-interface-git-revert-add-liquidity-uniswap.vercel.app
Should now work: https://uniswap-interface-git-revert-307a995-uniswap.vercel.app

@Daniel28127 You could use any release that works to provide liquidity in the meantime.

**Comment by Daniel28127** [comment]
> Reverting a PR committed yesterday to unblock prod.
> 
> Should still not work: https://uniswap-interface-git-revert-add-liquidity-uniswap.vercel.app
> Should now work: https://uniswap-interface-git-revert-307a995-uniswap.vercel.app
> 
> @Daniel28127 You could use any release that works to provide liquidity in the meantime.

@justindomingue  Thanks a lot, its working this way

**Comment by justindomingue** [comment]
tracked in #1358
