### ISSUE TITLE
Re-enable internationalization of the UI

### ISSUE THREAD

**Issue by ChristophSiegenthaler** [Uniswap/uniswap-interface#1672]
I would like to provide help in translating the UI to german and I've seen other people with similar ideas in the PRs (chinese, arabic, persian, ...). While the translation for UI v1 was quite good/complete for some languages, the translation efforts seem to have mostly stopped with v2 and v3. Currently, a lot of text is "hardcoded" in english and the translation files in public/locales are out of date. Providing an updated en.json in locales and "refactoring" the code to reintroduce translations would provide a proper base for easier translations through volunteers.

**Comment by ChristophSiegenthaler** [comment]
I would personally favor to change the translation files to a more structured scheme. I started playing with some ideas here: https://github.com/ChristophSiegenthaler/uniswap-frontend/tree/pr_i18n_refactor

i18next supports nested keys if one disables the "keySeparator" line in the i18n init.

de.json:
```
{
  "wallet": {
      "connect": "Wallet verbinden",
      "connect_long": "Mit einer Wallet verbinden",
      "no": "Keine Wallet gefunden"
  },
  "token": {
      "select": "Token auswählen"
  }
}
```
and to call it:
`{t('wallet.connect')}`

**Comment by justindomingue** [comment]
Thanks @ChristophSiegenthaler ! I'm currently going over all of our strings and making sure they are in the locale file. After that I was planning on restructuring the locale to support nesting like you have above. Will update early next week.
