### ISSUE TITLE
Interface behaves like a normal swap when wrapping/unwrapping ETH

### ISSUE THREAD

**Issue by InvisibleSymbol** [Uniswap/uniswap-interface#1674]
**Bug Description**
The interfaces shows swap related information when trying to wrap/unwrap ETH. Route shown gets never used, as the Wrap button directly calls the Wrapped ETH contract, as intended, which results in a perfect 1:1 conversion. 

Please hide all Swap related information when trying to wrap/unwrap as users will think they will have to pay a Liquidity Provider Fee or will experience slippage even if that is not the case.
![](https://url.invis.cloud/fvh20K)
![](https://url.invis.cloud/bDk2OD)
**Steps to Reproduce**

- Incorrect No Liquidity Error: https://app.uniswap.org/#/swap?outputCurrency=ETH&inputCurrency=0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2&exactAmount=100000&exactField=Input

- Incorrect and non-existent Price Impact shown: https://app.uniswap.org/#/swap?outputCurrency=ETH&inputCurrency=0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2&exactAmount=10&exactField=Input

**Expected Behavior**
No swap related information is shown.

**Comment by moodysalem** [comment]
Thanks, I think I fully fixed this in https://github.com/Uniswap/uniswap-interface/commit/3aaa3fef89a30ce30c358460a621d6071b83fe45

You can try at https://uniswap-interface-git-main-uniswap.vercel.app/
