### ISSUE TITLE
USDC price not loading for some people.

### ISSUE THREAD

**Issue by Marc477** [Uniswap/uniswap-interface#1682]
Price refreshing issue at https://app.uniswap.org/#/pool/[any_pool_id]
So in my browser, when I look at any pool that includes USDC in the pair, the price in $ (total value of the pool and total value of the fees) is not loading and instead it shows a dash "-". When USDC is not in the pair, the display works perfectly.

I did not manage to find exactly what causes the issue because it is working fine for some people. But me im on Chrome + Windows 10 and with metamask extension.

Since im a developer i did a bit of debugging in chrome and found that the issue seems to be with this function:

PositionPage.tsx
const price0 = useUSDCPrice(token0 ?? undefined)
  const price1 = useUSDCPrice(token1 ?? undefined)
  
  So price0 is undefined,  price1 is the correct value.  Token0 is USDC while token1 is WETH. So it seems that useUSDCPrice doesnt always work on USDC token for some browsers configuration.

**Comment by justindomingue** [comment]
Can you send the id of a pool that doesn't show the price for you?

https://app.uniswap.org/#/pool/2 this one for example shows the price and fees.

**Comment by Marc477** [comment]
The one you sent is also not loading for me. And has the same null value returned by useUSDCPrice on the USDC token.

**Comment by justindomingue** [comment]
are you able to debug this?

https://github.com/Uniswap/uniswap-interface/blob/main/src/hooks/useUSDCPrice.ts#L41

I'm assuming v2USDCTrade/v3USDCTrade will always be undefined for you (we use hooks so could be undefined for a few execution).

We could probably handle the special case of USDC by returning new Price(USDC, USDC, '1', '1') when currency is USDC.

**Comment by Marc477** [comment]
v2USDCTrade is NULL when that function is called for the USDC token.  It seems correct when its called for the other coin (DAI or ETH).

**Comment by justindomingue** [comment]
Hm.. strange.. I would expect that to be a consistent repro. I think hardcoding price for usdc will be a good next step (should be done regardless of this bug).

**Comment by Marc477** [comment]
Hum sorry i debugged on the wrong browser. When i test in the browser with the issue the variable that is null is this one:
v3USDCTrade.trade     so v3USDCTrade is defined but not   trade.

**Comment by Marc477** [comment]
Ok its not minimized finally, it was bringing me to a temporary file, but i managed to go deeper into the debuging.

useAllV3Routes function inside file useBestV3Trade.ts
There is a line
const { routes, loading: routesLoading } = useAllV3Routes(currencyIn, amountOut?.currency)
This functions returns  an empty array for USDC, so routes array length is 0 for USDC, but for other coins its not empty.

**Comment by justindomingue** [comment]
v3usdctrade.trade can be undefined when the routing api is loading. I'm assuming in your case v3usdctrade.state is not equal to valid (=3) [state](https://github.com/Uniswap/uniswap-interface/blob/9822e68d5afb7d87e1d9b09c27a1150dca302341/src/hooks/useBestV3Trade.ts#L13). 

I have a [PR](https://github.com/Uniswap/uniswap-interface/pull/1683) out to handle usdc directly. Can you try visiting a pool page with usdc with this url?

https://uniswap-interface-git-handle-usdc-uniswap.vercel.app

**Comment by Marc477** [comment]
Ok I went even deeper into debuging inside file useAllV3Routes.ts function computeAllRoutes

```
const outputToken = pool.token0.equals(tokenIn) ? pool.token1 : pool.token0
    if (outputToken.equals(tokenOut)) {
      allPaths.push(new Route([...currentPath, pool], startCurrencyIn, currencyOut))
    } else if (maxHops > 1) {
      computeAllRoutes(
        outputToken,
        currencyOut,
        pools,
        chainId,
        [...currentPath, pool],
        allPaths,
        startCurrencyIn,
        maxHops - 1
      )
    }
```

Here nothing gets added to allPaths, allPaths array is always empty for USDC.
outputToken is NOT equal to tokenOut and maxHops  is 1

**Comment by justindomingue** [comment]
Gotcha, sort of makes sense? USDC->USDC doesn't find a path.. although would need to look why it doesn't work on my end.

Does the url i sent earlier work for you then? I handle USDC separately.

**Comment by Marc477** [comment]
Damn i know the problem
const outputToken = pool.token0.equals(tokenIn) ? pool.token1 : pool.token0

This is a check to know if we are currently processing token1 or token2 so it checks if boths are equal then it takes the other. but since the VALUE is calculated in USDC then it takes the wrong one, on that line outputToken should be token0 but it takes token1 which is ETH, but at this moment its processing USDC price.

**Comment by Marc477** [comment]
Your link https://uniswap-interface-git-handle-usdc-uniswap.vercel.app is working

**Comment by Marc477** [comment]
The weirdest thing is that its working for other people or on other browser? Do i have an old version cached or something?
Or maybe its in my other browser that i have a working version cached? its a bit weird
