### ISSUE TITLE
Listing New Token

### ISSUE THREAD

**Issue by highflertoken** [Uniswap/uniswap-interface#1685]
Hi,

I have  just created my this ERC20 token and I was trying to list it on uniswap however I was unsuccessful be can when I paste my contract code shown below, my token isn't displayed (no results found. Could you be so kind to help me out?
0x99AC2CA4761ea323c5cFBe903f5106219c90b486

**Comment by moodysalem** [comment]
Please ask for help in the Discord. The address on Etherscan looks like you deployed a library, not a token contract.
