### ISSUE TITLE
Tried to create new ERC20 pool ETH - DOG but stuck in approve

### ISSUE THREAD

**Issue by lendtrain** [Uniswap/uniswap-interface#1686]
I tried to create a new pool yesterday for ETH - DOG but it never showed up in Uniswap. I reset my MetaMask account and tried again, but now there is only an Add button instead of an approve button in Uniswap. When I click Add, it opens an informational window and nothing happens. 

What would you need from me to look into this?

**Comment by justindomingue** [comment]
Do you have the approve transaction hash? There may be console.log() statements that could be useful if you know how to access those.

Can you also share the address of DOG?
That's Uniswap v3?

**Comment by lendtrain** [comment]
I believe the hash is
0x1cf1e5612c2cfbde6ae10a6f5b17d5ae81d5b2e65bf0b9ff9f3ea03454926567

Address for DOG is 0xf9319024d494c8e51a2cda1ea84e95e33c332e81

Yes it’s uniswap V3. Thanks for your help.

Log is attached.

**Comment by justindomingue** [comment]
Sorry, don't think the log file was attached to the issue since you replied via email. Can you send as a gist?

> I reset my MetaMask account and tried again, but now there is only an Add button instead of an approve button in Uniswap.

The approve txn was successful so that makes sense.

**Comment by lendtrain** [comment]
I'm sorry, I don't know how to do that. Are you able to see what happened
by viewing the transaction on Etherscan?

Here is a copy/paste from the log section of Etherscan for that transaction:

Transaction Receipt Event Logs
177
Address0xf9319024d494c8e51a2cda1ea84e95e33c332e81
<https://etherscan.io/address/0xf9319024d494c8e51a2cda1ea84e95e33c332e81>
Name

Approval (index_topic_1 address tokenOwner, index_topic_2 address spender,
uint256 tokens)View Source
Topics

   - 0 0x8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925
   - 1 Dec 0x642b654b4323af10e0bb67fdc10b3f0eab578ac7
   <https://etherscan.io/address/0x642b654b4323af10e0bb67fdc10b3f0eab578ac7>
   - 2 Dec 0xc36442b4a4522e871399cd717abdd847ab11fe88
   <https://etherscan.io/address/0xc36442b4a4522e871399cd717abdd847ab11fe88>

Data

   - tokens :
   115792089237316195423570985008687907853269984665640564039457584007913129639935
   DecHex

**Comment by lendtrain** [comment]
Good evening,

Following up on this. Any update?

**Comment by justindomingue** [comment]
> When I click Add, it opens an informational window and nothing happens.

There should be an 'Add' button at the bottom of the window, are you not seeing it? We've seen a report recently that on desktop the modal was cut off. If that's the case, you can resize the browser window or zoom out on the page. On mobile you should be able to scroll.

Or are you saying after clicking 'Add' in the confirmation modal nothing happens?

**Comment by lendtrain** [comment]
That’s correct, the window opens but there is no button. I’ll try zooming
out to see if the button got cut off.

**Comment by justindomingue** [comment]
Should be related to #1691

**Comment by justindomingue** [comment]
Please reopen if that's not the issue @lendtrain
