### ISSUE TITLE
Responsive UI Hiding add button

### ISSUE THREAD

**Issue by Rachel-Eichenberger** [Uniswap/uniswap-interface#1691]
**Bug Description**
Found some users with a responsive ui issue, where they could not see the buttons in the pop ups (verification non expert mode)
Zooming out allows user to see and click button. One user zooming out to 80% solved.

**Steps to Reproduce**

1. Go to app.uniswap.org/pool
2. Click on desired pool and increase Liquidity
3.  after entering pool info clicking add gives pop up
4. when pop up shows you can not see add button
   ...

**Expected Behavior**
When clicking add in the non expert mode pop up should resize to users screen size and show the add button on the confirmation pop up 

**Additional Context**
Had a few users with this issue, one responded with more info, I will add more if I receive. 

Users system
- Google Chrome 90.0.4430.85 
- Mac OS 10.14.2
- Display size 2560 x 1600

![image](https://user-images.githubusercontent.com/60412342/119299585-0853a780-bc14-11eb-829f-f4ddf6acc6cf.png)
![image](https://user-images.githubusercontent.com/60412342/119299598-0f7ab580-bc14-11eb-9c7f-a44c9c5b9ecd.png)

100%_Display_Add_Liquidity 
![image](https://user-images.githubusercontent.com/60412342/119328084-96418980-bc38-11eb-9873-06b2efcd0556.png)

90%_Display_Add_Liquidity 
![image](https://user-images.githubusercontent.com/60412342/119328099-9a6da700-bc38-11eb-9784-e448e745f1a7.png)

80%_Display_Add_Liquidity 
![image](https://user-images.githubusercontent.com/60412342/119328108-9cd00100-bc38-11eb-998e-08ebde5d5bd6.png)

100%_Display_Swap
![image](https://user-images.githubusercontent.com/60412342/119328118-9f325b00-bc38-11eb-9e51-31f7d496efd6.png)

90%_Display_Swap
![image](https://user-images.githubusercontent.com/60412342/119328125-a194b500-bc38-11eb-92cf-3a27d1b86e59.png)

**Comment by willhennessy** [comment]
Thanks for picking this up justin! I wasn't able to reproduce. Are you?

**Comment by justindomingue** [comment]
@Rachel-Eichenberger I'm surprised the user had an issue at 2560 x 1600. Couldn't they resize the window?

Right now, we support content overflow in the popup on mobile but not desktop (I'm assuming we expect users to resize the window).

https://github.com/Uniswap/uniswap-interface/blob/main/src/components/Modal/index.tsx#L34

We could consider hiding some of the content at small heights or adding the scrollbar on overflow on desktop, but I'm not sure it's necessary.

**Comment by Rachel-Eichenberger** [comment]
@justindomingue  I agree I was surprised with that screen size, had another user mention this from a 14" laptop in the feedback section of discord. No response yet on computer info...   Unfortunately my new computer only has onboard gpu, and none of mine go up to that resolution :) , I am able to see the same positioning and hiding of the buttons on my ipad, 768 X 1024 Ipad air 12.5.3.  But of course the mobile options kick in and I'm able to scroll it..

**Comment by justindomingue** [comment]
@callil Do you know why we prevent overflow on desktop? I don't see a downside to adding it on dekstop.

**Comment by Rachel-Eichenberger** [comment]
From the User
Regular screen 100% (not in max screen)
![image](https://user-images.githubusercontent.com/60412342/119923413-82db3a80-bf26-11eb-936e-94957c9468dc.png)

Full Screen 100%
![image](https://user-images.githubusercontent.com/60412342/119923418-866ec180-bf26-11eb-8e86-225edf00d41a.png)

It seems like, with 100% with no full screen, the Add button showing up half button at the bottom of the overlay
The full screen one, it shows perfectly
-----------------------------
Perhaps it's tied to a computer screen resolution size rather than browser... (tbh I don't know your code sorry)

**Comment by Rachel-Eichenberger** [comment]
@justindomingue  @callil 
Found a way to replicate on my computer, With advanced mode off (so you get second confirmation) with that up hitting the dev console (mine is on the bottom rather than side)  the button will cut off...

**Comment by justindomingue** [comment]
> @callil Do you know why we prevent overflow on desktop? I don't see a downside to adding it on dekstop.

@callil
