### ISSUE TITLE
Missing padding when market price outside range

### ISSUE THREAD

**Issue by willhennessy** [Uniswap/uniswap-interface#1693]
**Bug Description**
In the add liquidity UI, when the market price is outside of your specific range, we show a text field in the Deposit Amounts box. The text field needs more padding.

**Steps to Reproduce**

1. Go to /add/
2. Entire a price range that is entirely above or below the market price
3. Check the Deposit Amounts field below

<img width="1021" alt="Screen Shot 2021-05-24 at 11 44 25 AM" src="https://user-images.githubusercontent.com/5455577/119373077-062a3100-bc86-11eb-9124-a81d7f825a12.png">

**Comment by payupsucker** [comment]
Nice
