### ISSUE TITLE
Increase liquidity in WETH

### ISSUE THREAD

**Issue by reuptaken** [Uniswap/uniswap-interface#1702]
**Is your feature request related to a problem? Please describe.**
There's no easy way to add liquidity in WETH instead of ETH

**Describe the solution you'd like**
While one can create position in WETH and then, later, remove liquidity or collect fees in WETH, there's no way to add more liquidity in WETH (or I just haven't found any which may mean it's not intuitive).

Maybe using WETH instead of ETH could be a global setting for the user? If someone uses WETH he probably wants to do it on all positions.

**Comment by Jorropo** [comment]
Duplicates of #1480 may this be closed ? :)
