### ISSUE TITLE
Hide closed positions toggle UX love

### ISSUE THREAD

**Issue by willhennessy** [Uniswap/uniswap-interface#1705]
Give some love to the "Hide closed positions" toggle on /pool page

Can we also consider how the page adapts to the new content? When I toggle on/off, the page header appears/disappears because the height of the page changes.

Mock
<img width="1432" alt="Screen Shot 2021-05-25 at 3 37 23 PM" src="https://user-images.githubusercontent.com/5455577/119558268-2e418f00-bd6f-11eb-8384-354cd52e7b6c.png">

**Comment by willhennessy** [comment]
hi maggie, is the UX ready for engineering handoff? I think this looks great: https://www.figma.com/file/51D19BGIbo7Q3tzqwDqTEj/LP-Templates-and-Strategies-Exploration?node-id=240%3A0

when you're ready, let's assign to @justindomingue

**Comment by maggievalentine** [comment]
https://www.figma.com/file/aIAWQB6RTJ7bLiK4u8jtlX/LP-Templates-and-Strategies-Exploration-Copy?node-id=240%3A0 -- any preference on design here?

**Comment by willhennessy** [comment]
I would trust your gut more than mine! all three look nice
