### ISSUE TITLE
v3-only token showing completely wrong price (ropsten)

### ISSUE THREAD

**Issue by jab416171** [Uniswap/uniswap-interface#1706]
**Bug Description**
This token (which only has an eth pair and only on v3) is showing a price that makes no sense, making swaps impossible without expert mode

**Steps to Reproduce**

1. Go to https://app.uniswap.org/#/swap on ropsten
2. Add 0x77c26cfb47aa12212859ec84ad002a94c6328128 as a custom token
3. Try to swap

**Expected Behavior**
The price should match, since the only pair is with eth

**Additional Context**
![image](https://user-images.githubusercontent.com/345752/119577370-c0e62c00-bd77-11eb-9e6a-29e87c19a79d.png)
![image](https://user-images.githubusercontent.com/345752/119577377-c2afef80-bd77-11eb-87ee-ab3a374efd7d.png)
![screenshot_20210525163926](https://user-images.githubusercontent.com/345752/119577390-cb082a80-bd77-11eb-93df-e2340dcfb816.png)

**Comment by justindomingue** [comment]
That's expected. We just fake prices for non-mainnet. @moodysalem can you comment on why we're doing this?

**Comment by moodysalem** [comment]
> That's expected. We just fake prices for non-mainnet. @moodysalem can you comment on why we're doing this?

Just so we can see something in the UI for dollar value on testnets. We can use a different token as 'USDC' on testnets which would be a small improvement

**Comment by jab416171** [comment]
This fake price makes testing tokens on testnet very difficult, as you can see in the screenshots: "price impact too high"

**Comment by moodysalem** [comment]
you can switch to expert mode to ignore the warning

**Comment by willhennessy** [comment]
thanks all! closing this out because it seems WAI
