### ISSUE TITLE
Back arrow on v2 remove liquidity page links to v3 pools page

### ISSUE THREAD

**Issue by reuptaken** [Uniswap/uniswap-interface#1724]
**Bug Description**

<img width="323" alt="Zrzut ekranu 2021-05-27 o 20 45 29" src="https://user-images.githubusercontent.com/26765602/119880806-e700fd00-bf2c-11eb-8f72-c970d3c14b74.png">

**Comment by willhennessy** [comment]
this was fixed on the v2 migrate page: https://github.com/Uniswap/uniswap-interface/pull/1700#event-4833032484

but remains to be fixed on the v2 add liquidity and remove liquidity pages. Let's slot it in next week.
