### ISSUE TITLE
Preload font (woff2) files to avoid LayoutShift on load

### ISSUE THREAD

**Issue by zzmp** [Uniswap/uniswap-interface#1730]
**Bug Description**
Font files are loaded by the css chunk, but are known at compile time. The Inter font files (woff2) should be preloaded from the initial HTML so that they are fetched immediately (at low priority this should not negatively impact other loads). This will either make the layout shift occur sooner or (luckily, if they are downloaded first) eliminate the layout shift completely by having the font ready before the first render.

**Steps to Reproduce**

1. Go to http://uniswap.exchange.
2. Use the Chrome DevTools performance pane to record the load. You may need to throttle network and disable cache.
2. Note a LayoutShift when the fonts first load, after the first render.

**Expected Behavior**
Fonts should be preloaded using a <link rel="preload"> tag on the served HTML.

**Comment by moodysalem** [comment]
kinda hard to do because we need to bundle all the fonts, and importing `inter-ui` from the js allows create-react-app to bundle it all appropriately. the only alternative i can imagine would be copying the font files to the assets directory and copying the css into a style tag in the head of index.html

can we avoid the layout shift by using font-display?

**Comment by zzmp** [comment]
[font-display](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display) looks like it would block rendering, but that would just delay the UI until fonts have loaded. I think the better option would be to copy the font files to assets and load it in the <head>, either as a <style> element or as a <preload> element. I _think_ different fonts are used on different pages, so <preload> is probably more appropriate so that the variants of the font family aren't loaded as aggressively.

**Comment by moodysalem** [comment]
is there a good way to know how much better the first load performance would be? a pr is welcome

**Comment by SirJosh1987** [comment]
Not when you bug out

**Comment by zzmp** [comment]
Time to display content should be unaffected. Fixing this would just prevent a flash of unstyled text (FOUT), making this an aesthetic issue more than anything else.
