### ISSUE TITLE
Etherscan links using ENS names are broken

### ISSUE THREAD

**Issue by ErikBjare** [Uniswap/uniswap-interface#1731]
**Bug Description**

When "View on Etherscan" (see screenshot) is clicked while using an ENS address, it leads to a broken page: https://etherscan.io/address/erik.bjareholt.eth

![image](https://user-images.githubusercontent.com/1405370/119965323-6c76c280-bfaa-11eb-877a-c50d24266356.png)

**Expected Behavior**

Either point the link to the address-resolved etherscan URL, or to the ENS lookup: https://etherscan.io/enslookup-search?search=erik.bjareholt.eth

**Additional Context**

I'll look into making a PR with a fix. The relevant pieces of code are:

 - https://github.com/Uniswap/uniswap-interface/blob/5e30a4b4ad9c2c1027ea513e6cf654fbfd8589e7/src/components/AccountDetails/index.tsx#L357
 - https://github.com/Uniswap/uniswap-interface/blob/7f1def300d3d036555bcc2e2b2368b9aeb373b8f/src/utils/getExplorerLink.ts#L22

**Comment by moodysalem** [comment]
The link works for my ENS name. The issue with your ENS name is that the reverse resolution is set (address -> name) but not the forward mapping (name -> address). I think this is a pretty rare edge case

**Comment by ErikBjare** [comment]
Ah gotcha, probably just going to close this then. The URL works now that I set the ENS record correctly.
