### ISSUE TITLE
Wallet balance conflicts with app header

### ISSUE THREAD

**Issue by willhennessy** [Uniswap/uniswap-interface#1735]
1. Connect a wallet
2. Shrink the window horizontally

Observe the wallet balance overlaps with the action links in the header

Connecting to a testnet makes it worse

<img width="989" alt="Screen Shot 2021-05-28 at 1 51 13 PM" src="https://user-images.githubusercontent.com/5455577/120025847-460f5200-bfbf-11eb-9003-27c6622c4248.png">

**Comment by willhennessy** [comment]
@callil the testnet badge is an edge case for now, but when we add the network selector for Layer 2 many users will be affected

**Comment by moodysalem** [comment]
i'm trying to make the header more responsive rn with the l2 stuff

**Comment by justindomingue** [comment]
This was working pretty well. https://github.com/Uniswap/uniswap-interface/pull/1574

**Comment by moodysalem** [comment]
we probably need a bigger change especially given the each of the localized translations has different widths (getting rid of all absolute/fixed positioning and using more automatic wrapping)
