### ISSUE TITLE
en-US.po is missing in source tree and/or steps in CONTRIBUTING.md

### ISSUE THREAD

**Issue by jab416171** [Uniswap/uniswap-interface#1791]
**Bug Description**
Application is broken until you create a en-US.po file

**Steps to Reproduce**

1. Make a clean clone of the repo
2. Run it: `yarn install && yarn start`
3. Notice that you get a blank page and an error in the console that en-US.po is missing

**Expected Behavior**
Application should work normally

**Additional Context**
Talking to @justindomingue it sounds like this file is generated in the github workflow, and it's in the .gitignore, so however it's generated could just be added to [CONTRIBUTING.md](https://github.com/Uniswap/uniswap-interface/blob/main/CONTRIBUTING.md)
As a workaround I can just copy another file to en-US.po
![screenshot_20210601203417](https://user-images.githubusercontent.com/345752/120416431-5d7d7080-c31a-11eb-922b-c0c90c4854b5.png)

**Comment by justindomingue** [comment]
in this case, I think we just need to make sure that devs run `yarn i18n:extract` at least once since we don't check in the english po file.

**Comment by justindomingue** [comment]
Added note in `CONTRIBUTING`. We can consider making that flow easier if there's a need.

**Comment by NoahZinsmeister** [comment]
we could make `yarn i18n:extract` a `postinstall` maybe?
