### ISSUE TITLE
missing translation when adding custom token

### ISSUE THREAD

**Issue by jab416171** [Uniswap/uniswap-interface#1792]
**Bug Description**
Translations for custom token dialog are missing

**Steps to Reproduce**

1. Switch locale to something other than en-US (I used ca-ES)
2. Add a custom token, notice the warning dialog is in English
   ...

**Expected Behavior**
Dialog should be translated

**Additional Context**
I was just going to add a PR to localize these strings but it wasn't obvious how to do that (without editing every single .po file), maybe something that could be scripted in the future (or if it is already, instructions on how to run the script)

**Comment by moodysalem** [comment]
fixed in https://github.com/Uniswap/uniswap-interface/pull/1798
