### ISSUE TITLE
Add Liquidity UX - buttons and liquidity distribution chart

### ISSUE THREAD

**Issue by willhennessy** [Uniswap/uniswap-interface#1810]
Add a liquidity distribution chart with range sliders to the Add Liquidity UI

- [x] Maggie to deliver UX by 6/13
- [x] Justin to implement

**Comment by willhennessy** [comment]
Teo and I will lock the (a) metric for auto-selecting fee tier and (b) % buttons per fee tier today or tomorrow

**Comment by willhennessy** [comment]
Polish doc: https://docs.google.com/document/d/1bjy7EjFM_w4XmqzzLGoqO-DTE6GiXUbiC6ZOG8aTqhw/edit

**Comment by justindomingue** [comment]
Closing feature. Fast-follows:
#1836 
#1831
