### ISSUE TITLE
Coin exchanged not reflecting.

### ISSUE THREAD

**Issue by Inomaciti** [Uniswap/uniswap-interface#1820]
Dear uniswap,
I exchanged 9ZCN (ochain) and 1SNX (synthex) to Etherum on 04/06/2021 up till now it has not reflected on my wallet here are the transaction ID
![Screenshot_2021-06-07-17-04-07](https://user-images.githubusercontent.com/36166378/121052869-b2096b80-c7b2-11eb-98d7-324052354fc3.png)
![Screenshot_2021-06-07-17-03-18](https://user-images.githubusercontent.com/36166378/121052907-b9c91000-c7b2-11eb-91b6-09ab86400d67.png)
Kindly assist me 
Thank you

**Comment by moodysalem** [comment]
Please ask for support in the Discord.
