### ISSUE TITLE
String needs clarity for translation

### ISSUE THREAD

**Issue by asood123** [Uniswap/uniswap-interface#1857]
Translators asking about this string (mentioned several times [here](https://github.com/Uniswap/uniswap-interface/blob/4b72d757c5bd8e1800248cb34c6d2622f0ca11ce/src/hooks/useSwapCallback.ts#L218)):

`This transaction will not succeed due to price movement. Try increasing your slippage tolerance. Note fee on transfer and rebase tokens are incompatible with Uniswap V3.`

Specifically, how to translate `Note fee...` . I can understand their confusion the way it's written. Either we should say, `Note that fee...` or `Note: fee... `

**Comment by justindomingue** [comment]
Added context on Crowdin.

**Comment by asood123** [comment]
Even for the EN version, we should update the string?

**Comment by justindomingue** [comment]
Just added the `:` to our strings. It will sync with Crowdin.
