### ISSUE TITLE
Windows machine build is falied

### ISSUE THREAD

**Issue by arulananth** [Uniswap/uniswap-interface#1865]
**Bug Description**
I am installing script Windows and Mac. Both OS have React,NPM,NODEJS all are same version. 
Working well MAC. 

**Steps to Reproduce**

1. We get error in Windows PC follow the error.
2. we facing issue in index.ts file inside abis/types folder in MAC PC.
3. This file created during ether v5 running and No import or export method in index.ts file @abis/types.

We need to create any additonal settings or need to change anything specific for Windows OS?

![image](https://user-images.githubusercontent.com/2954403/122158361-29fa2480-ce8a-11eb-8c75-e38d622c9033.png)

**Comment by arulananth** [comment]
![image](https://user-images.githubusercontent.com/2954403/122158356-26ff3400-ce8a-11eb-940e-58c2023809ce.png)

**Comment by willhennessy** [comment]
Hi arulananth, thanks for developing on v3! This type of question can be best answered in the dev-chat channel of our Discord: https://discord.gg/TtqXF4NQ
