### ISSUE TITLE
reverse order of `GOVERNANCE_ADDRESSES`

### ISSUE THREAD

**Issue by NoahZinsmeister** [Uniswap/uniswap-interface#1871]
To ensure URL consistency for `/vote/:governorIndex/:id`, we should index `GOVERNANCE_ADDRESSES` in reverse, i.e. newest at the end, see https://github.com/Uniswap/uniswap-interface/commit/b763659788c0847aa7b7dd58508fb7258e427ccd#r52260616

**Comment by moodysalem** [comment]
this is now fixed as of the logs hook refactor
