### ISSUE TITLE
Connect GA to Search Console

### ISSUE THREAD

**Issue by willhennessy** [Uniswap/uniswap-interface#1872]
Connect Google Analytics to the Search Console so we can gain SEO insights to drive discovery of uniswap

I believe the steps are
1. Go [here](https://search.google.com/search-console/associations/analytics-property-selection?hl=en_US&ga_property_id=232099914&continue=https%3A%2F%2Fanalytics.google.com%2Fanalytics%2Fweb%2F%23%2Fa128182339w232099914p218018572%2Fadmin%2Fintegrations%2Fwmx)
2. Add the TXT record into our DNS config to [verify site ownership](https://support.google.com/webmasters/answer/9008080#domain_name_verification&zippy=%2Cdomain-name-provider)
3. Complete any other steps after that in the flow

We do not expect or intend this action to record any new user data. Please let me know if you learn otherwise during the process.

Note: per Uniswap/uniswap-interface@8d90bb7 and Uniswap/uniswap-interface@bdcb9a8 we are anonimyzing IP address and not setting cookies to preserve user privacy.

**Comment by moodysalem** [comment]
It seems like all I had to do was type app.uniswap.org in step 1 and it auto verified
