### ISSUE TITLE
ETH on Arbitrum does not implement full ERC20 spec

### ISSUE THREAD

**Issue by asood123** [Uniswap/uniswap-interface#1874]
**Bug Description**
![image](https://user-images.githubusercontent.com/6106941/122445615-b6cade00-cf6f-11eb-8db4-7c16f3cc3e13.png)

Screenshot above should show 0.1... ETH (instead it's multiplied by 10^18)

**Steps to Reproduce**

1. Go to ...
2. Click on ...
   ...

**Expected Behavior**

**Additional Context**
Add any other context about the problem here (screenshots, whether the bug only occurs only in certain mobile/desktop/browser environments, etc.)

**Comment by willhennessy** [comment]
Issues:
- the ETH token does not report decimals
- token name is missing in #1875 and #1876

Offchain Labs said they will make the WETH system migration work with the existing WETH contract so that address and the periphery contracts won't need to change at all.

**Comment by moodysalem** [comment]
it appears to be fixed now
