### ISSUE TITLE
Failed to activate locale en-US Error: Cannot find module './en-US.po'

### ISSUE THREAD

**Issue by AstinAshler** [Uniswap/uniswap-interface#1901]
**Bug Description**
after yarn start there's only blank page
```
Failed to activate locale en-US Error: Cannot find module './en-US.po'
    at  groupOptions: {} namespace object:126
    at async dynamicActivate (i18n.tsx:79)
```

**Comment by justindomingue** [comment]
run `yarn i18n:extract`

**Comment by justindomingue** [comment]
Curious, where did you get the instruction to run `yarn start`? [`CONTRIBUTING.md`](https://github.com/Uniswap/uniswap-interface/blob/main/CONTRIBUTING.md) mentions `yarn i18n:extract`.

**Comment by AstinAshler** [comment]
@justindomingue thank you very much, problem solved
