### ISSUE TITLE
Teach people what you guys used in this repo

### ISSUE THREAD

**Issue by cesarvspr** [Uniswap/uniswap-interface#1908]
I see in this project a lot of integration of web3 with react that I never saw in the documentation. This is gold. 

If this already exists, where can I found documentation on web3 + react + .ts or .js?

**Comment by moodysalem** [comment]
Not really appropriate as an issue for this repo, but if you want to learn more about web3-react, you can look at its repo and repo docs
https://github.com/NoahZinsmeister/web3-react
