### ISSUE TITLE
Crowdin: Exclude user "Tomedes" from translating

### ISSUE THREAD

**Issue by ChristophSiegenthaler** [Uniswap/uniswap-interface#1913]
I've provided the German translation on crowdin and recently saw that user Tomedes changed some of my translations to a more literal translation that is sometimes way too long for the UI or plain wrong. This and the fact that my sentences in those cases have been removed without comment/discussion etc leads me to request that write access of user Tomedes should probably be removed from the German translation of uniswap. According to Yijin this could be done if it hasn't already happened? (In that case please close the issue)

**Comment by justindomingue** [comment]
Thanks for bringing it up @ChristophSiegenthaler . Tomedes is a third-party vendor that was hired to complete translations, especially for languages with no community support. As you can tell, they don't have as much context as the community which means translations are sometimes less accurate. I've deleted/reverted their translations.

Can you take a look and let me know if there are more issues with the German translations?
