### ISSUE TITLE
Optimism downtime behavior

### ISSUE THREAD

**Issue by willhennessy** [Uniswap/uniswap-interface#1937]
1. Monitor Optimism block updates. (note: we've decided not to routinely poll optimism.io/status because it might leak IPs)

2. If we have not received a new block in X seconds update network status in the bottom right corner to yellow

3. After Y seconds
    - update network status to red
    - disable all buttons that would submit a transaction:  swap, add liquidity, etc. Also disable buttons confirmation modals because it's possible that Optimism goes down while the user in a middle of reviewing & confirming their tx.

Design:  let's use the disabled state button and text "Optimism is experiencing downtime"

**Comment by willhennessy** [comment]
@callil when the OP network is down, in addition to disabling buttons should we display a message like "Optimism may be experiencing downtime. You can check network status here." (optimism.io/status)

@moodysalem @JFrankfurt  what block update time periods are reasonable for yellow and red network status?

**Comment by JFrankfurt** [comment]
Optimism transactions are looking pretty sparse right now. Totally unscientific, but in the last hour there were ≈200 transactions. How comfortable are we with a potential false alarm to all visitors because there hasn't been a transaction in `n` minutes, when `n` could be large (5?) w/o things actually being broken?

**Comment by willhennessy** [comment]
Not very comfortable. We should try hard to avoid false alarms because it
will trigger negative reaction for Uniswap and optimism

Options?
A. Long waiting period. During true downtime, users will submit tx and
fail. Also possibility of false alarms remains if no tx arrive for a long
time.
B. Short waiting period, but check if it's a false alarm by pinging
optimism.io/status

Any others? Of the two, I prefer B but curious to hear other opinions
