### ISSUE TITLE
Multicall2Optimism failures

### ISSUE THREAD

**Issue by NoahZinsmeister** [Uniswap/uniswap-interface#1939]
**Bug Description**
When 1 (?) child call in a single call to `tryBatchAndAggregate` fails, all fail. Right now only repro'd on Optimistic Kovan, but might be the case for other networks as well.

**Steps to Reproduce**

On Optimistic Kovan, `useSingleContractMultipleData(quoter, 'quoteExactInput', quoteExactInInputs)` in `useBestV3TradeExactIn` errors when quoting against both the .05% and .3% pools when both pools exist, the .05% pool has no liquidity, and the .3% pool does. However, when there's liquidity in the .05% pool, both calls succeed. In the no liquidity case, when calls are sent separately, one call fails but the other succeeds (as expected).

**Comment by ben-chain** [comment]
I am very curious to know whether there is returndata showing all the calls failing, or no returndata at all.  If you manage to repro this, please make sure to note this and LMK :)

**Comment by moodysalem** [comment]
I believe this is no longer happening/related to the gas limit change
