### ISSUE TITLE
Typescript Error: /src/abis/types/index.ts(undefined,undefined):

### ISSUE THREAD

**Issue by InuCash** [Uniswap/uniswap-interface#1940]
**Bug Description**
TypeScript error in B:/OneDrive/Documents/Work/inucash/exchange/src/abis/types/index.ts(undefined,undefined):
'index.ts' cannot be compiled under '--isolatedModules' because it is considered a global script file. Add an import, export, or an empty 'export {}' statement to make it a module.  TS1208

**Steps to Reproduce**

1. Download Repo
2. Install Repo
3. Run Repo
4. Error outputs

**Additional Context**
This happens when I first download the project. I haven't done any customization, this is an initial error when trying to run it.
This file is auto-generated on its own 'types/index.ts';

Also, isolatedModules to false doesn't work and it required in tsconfig, it changes back to true.

**Comment by moodysalem** [comment]
maybe has something to do with a) windows or b) storing it on onedrive. atm we haven't put any effort to support windows as a dev environment

**Comment by InuCash** [comment]
I am surprised that would an issue.

**Comment by supermars01** [comment]
$ yarn compile-external-abi-types && yarn compile-v3-contract-types
$ npx typechain --target ethers-v5 --out-dir src/abis/types "./src/abis/**/*.json"
'typechain' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
