### ISSUE TITLE
compile  under '--isolatedModules'

### ISSUE THREAD

**Issue by my-Gem** [Uniswap/uniswap-interface#1978]
![123](https://user-images.githubusercontent.com/26290087/124778724-c38d9100-df73-11eb-806a-6af2c7e197ac.jpg)

**Comment by moodysalem** [comment]
Are you trying to run on windows?

**Comment by my-Gem** [comment]
yes

**Comment by my-Gem** [comment]
> 你想在 Windows 上运行吗？

是的

**Comment by moodysalem** [comment]
Not sure what is going on here. Sorry.
