### ISSUE TITLE
balance text is broken in the header

### ISSUE THREAD

**Issue by moodysalem** [Uniswap/uniswap-interface#1982]
**Bug Description**
<img width="351" alt="Screen Shot 2021-07-07 at 10 46 39 AM" src="https://user-images.githubusercontent.com/7897876/124790408-c014ee00-df10-11eb-8c38-eea5c5034cdf.png">

**Steps to Reproduce**
connect a wallet in app.uniswap.org

think this is due to the recent header changes, but not sure exactly how it happened since i'm using the english locale which should be extracted from the app at build time

**Comment by shebeengs** [comment]
A user also reported seeing no values when adding liquidity 

![image](https://user-images.githubusercontent.com/54754746/124795136-546b6900-df82-11eb-8add-dc81e14ba1fa.png)
![image](https://user-images.githubusercontent.com/54754746/124795164-59301d00-df82-11eb-91ed-dd4a16754c13.png)

Link to existing ticket: https://discord.com/channels/597638925346930701/862346481103798282/862346482464063509

**Comment by justindomingue** [comment]
#1981
