### ISSUE TITLE
Discussion: Reusable component location

### ISSUE THREAD

**Issue by rossbulat** [Uniswap/uniswap-interface#200]
Discussion: Where would be the best place to begin on-boarding reusable components into the project.

Right now Uniswap's `src/components/<component>/index.js` format works well for separating sections of the site.

However, let's take a hypothetical  reusable component case: The balance display. Token balance is displayed in `Swap`, `Send`, `AddlLiquidity` and `RemoveLiquidity`.

Now, where would the hypothetical `<Balance />` component reside? It would not be a duck, and as more reusable components are added, ducks would get overloaded.

I see the following solutions: 

Option 1: Adding an additional folder in components - perhaps named `Base` or `Abstract`, and start to populate that with higher level component files, such as `tokens.js` - where `<Balance />` would reside.

Option 2: Restructure component folders within  new abstract folders that group existing component folders together, and also house abstracted components.

E.g.:  
```
components/
   Tokens/ (new abstract folder)
        Swap/ (existing folders...)
        Send/
        AddLiquidity/
        RemoveLiquidity/
        tokens.js (abstract components file)
```

tokens.js housing the abstract reusable components for that folder. However there is no guarantee other parts of the project will not be requiring them (but a long import statement would solve that).

Perhaps option 1 would be the most viable at this stage as reusable components are introduced.

Any thoughts?

**Comment by moodysalem** [comment]
Think this is fairly outdated, closing. Feel free to open a new discussion about the latest directory structure (which admittedly is not the most organized)
