### ISSUE TITLE
Can't add custom tokens on optimism

### ISSUE THREAD

**Issue by Jorropo** [Uniswap/uniswap-interface#2008]
**Bug Description**
When trying to add a custom token either through the token tab in the token list or just by pasting the EIP-55 formated address in the search list, nothing happen.

**Steps to Reproduce**

Open https://app.uniswap.org/ with optimism mainnet selected in metamask.
Press select a token.
Paste `0x8c6f28f2F1A3C87F0f938b96d27520d9751ec8d9` (EIP-55 for sUSD for optimism mainnet).
Nothing happen

**Expected Behavior**
Uniswap should propose to add the token.

**Credit**
First reported by @melenxyz in the uniswap discord.

**Comment by Jorropo** [comment]
BTW, likely just https://github.com/Uniswap/uniswap-interface/issues/1993#issuecomment-876650320 (sorry I've missed it before openning this)

**Comment by willhennessy** [comment]
Thanks Jorropo! Indeed optimism is till in progress but I appreciate you filing this. @JFrankfurt do you expect token list support to fix this issue?

**Comment by moodysalem** [comment]
This is the same as the multicall bug, should already work on uniswap-interface-uniswap.vercel.app
