### ISSUE TITLE
Adding liquidity fails on Uniswap V3 for a token that performs a burn during a transfer

### ISSUE THREAD

**Issue by NeoXtreem** [Uniswap/uniswap-interface#2010]
**Bug Description**
Unable to add liquidity on Uniswap V3 for a token that performs a burn during a transfer.

**Steps to Reproduce**

1. Go to [Uniswap V3 Pool](https://app.uniswap.org/#/pool).
2. Add liquidity for a token matching the code below (requires OpenZeppelin Contracts):

```
pragma solidity ^0.8.0;

import "@openzeppelin/contracts/token/ERC20/presets/ERC20PresetFixedSupply.sol";

contract Foo is ERC20PresetFixedSupply {
    constructor() ERC20PresetFixedSupply("Foo", "FOO", 100 * 10 ** decimals(), _msgSender()) {
    }

    function _transfer(address sender, address recipient, uint256 amount) internal virtual override {
        super._transfer(sender, recipient, amount);
        _burn(recipient, 1);
    }
}
```
A deployment of this code is [here](https://rinkeby.etherscan.io/address/0xB50F87A4257e54e6e291d7c1B787577200F5F01a).

The following error shows in the dev tools console when the 'Add' button is pressed:
```
Error: cannot estimate gas; transaction may fail or may require manual gas limit (error={"code":-32603,"message":"execution reverted: M0","data":{"originalError":{"code":3,"data":"0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000024d30000000000000000000000000000000000000000000000000000000000000","message":"execution reverted: M0"}}}, method="estimateGas", transaction={"from":"0x78FC40ca8A23cf02654d4A5638Ba4d71BAcaa965","to":"0xC36442b4a4522E871399CD717aBDD847Ab11FE88","value":{"type":"BigNumber","hex":"0x7e38605822f1"},"data":"0xac9650d8000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000030000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000012000000000000000000000000000000000000000000000000000000000000002c0000000000000000000000000000000000000000000000000000000000000008413ead562000000000000000000000000b50f87a4257e54e6e291d7c1b787577200f5f01a000000000000000000000000c778417e063141139fce010982780140aa0cd5ab0000000000000000000000000000000000000000000000000000000000000bb8000000000000000000000000000000000000000019994616fedc43f56bf519a100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000016488316456000000000000000000000000b50f87a4257e54e6e291d7c1b787577200f5f01a000000000000000000000000c778417e063141139fce010982780140aa0cd5ab0000000000000000000000000000000000000000000000000000000000000bb8ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff4c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008ac7230489e7b44200000000000000000000000000000000000000000000000000007e38605822f100000000000000000000000000000000000000000000000077d2141c446ae2d7000000000000000000000000000000000000000000000000000000000000000000000000000000000000000078fc40ca8a23cf02654d4a5638ba4d71bacaa9650000000000000000000000000000000000000000000000000000000060e8dfab00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000412210e8a00000000000000000000000000000000000000000000000000000000","accessList":null}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.2.0)
    at e.value (index.ts:213)
    at e.value (index.ts:225)
    at ae (json-rpc-provider.ts:76)
    at r.<anonymous> (json-rpc-provider.ts:512)
    at c (runtime.js:63)
    at Generator._invoke (runtime.js:293)
    at Generator.throw (runtime.js:118)
    at u (4.499580c4.chunk.js:2)
(anonymous) | @ | index.tsx:279
```

**Expected Behavior**
A transaction is prompted to be confirmed in the connected wallet, and liquidity added. Note that this works on V2.

**Additional Context**
![image](https://user-images.githubusercontent.com/16148007/125144737-19526c80-e11f-11eb-9ecd-8e8ae0a5dcf3.png)

**Comment by willhennessy** [comment]
@moodysalem wdyt?

**Comment by moodysalem** [comment]
We are aware fee-on-transfer does not work in V3.

Here is a reference of what does/doesn't work written up by Noah. (inclusive) means the fee is deducted from the transferred amount, e.g. you call transfer 10, recipient gets 9, 1 fee is taken out.

```
for future reference re. (inclusive) fee-on-transfer tokens:
v2
addLiquidity works
removeLiquidity works via special-purpose router function
swaps work via special-purpose router functions
v3
addLiquidity fails UNLESS VIA CUSTOM ROUTER
removeLiquidity works (WETH must be used instead of ETH)
swaps buying the FoT token work
swaps selling the FoT fail UNLESS VIA CUSTOM ROUTER
```

I don't think we really want to support fee on transfer, but it's possible we could in the next version of the swap router, although the NFT cannot as easily be upgraded.

**Comment by willhennessy** [comment]
Got it thanks moody! I didn't realize burn on transfer was a subset of a fee on transfer

Sorry neoxtreem, I hope that helps.

**Comment by NeoXtreem** [comment]
@moodysalem Thanks for the analysis. Why would you not want to support this? As many of the replies to @NoahZinsmeister's [tweet about this](https://twitter.com/NoahZinsmeister/status/1390021135048249345) indicate, this is detrimental for DeFi tokens and all RFI-based tokens.

**Comment by moodysalem** [comment]
> @moodysalem Thanks for the analysis. Why would you not want to support this? As many of the replies to @NoahZinsmeister's [tweet about this](https://twitter.com/NoahZinsmeister/status/1390021135048249345) indicate, this is detrimental for DeFi tokens and all RFI-based tokens.

Not sure what an RFI token is, but I share pretty much [this opinion](https://twitter.com/danrobinson/status/1291137586463830019?s=20), and I don't think it's a good design for an ERC20 token to break the semantics of `balanceOf`, `transfer` or `transferFrom`

**Comment by NeoXtreem** [comment]
@moodysalem Thanks for you reply.

[RFI](https://reflect.finance/) is a token on which many others are based such as SAFEMOON and HOKK. Their code is on Etherscan [here](https://etherscan.io/address/0xa1afffe3f4d611d252010e3eaf6f4d77088b0cd7#code).

I appreciate that you share someone's opinion on Twitter, but there are many opposing opinions replying to that tweet.

But this is not about opinions - it's about a technical standard, and the semantics you mention are not prescribed anywhere, as indicated by [this reply](https://twitter.com/pedrouid/status/1378765931543941123) and [this reply](https://twitter.com/josephdelong/status/1378742459799367681).

So, this seems more like Uniswap retroactively making up their own ERC-20 standards because the current V3 implementation made incorrect early assumptions that would be too complex to unravel now without danger of severely breaking the code.

**Comment by moodysalem** [comment]
Those aren't opposing opinions. I completely agree that ERC20 is an interface standard that does not define behavior, and RFI and other tokens _are_ ERC20 tokens. That doesn't mean if you interact with the ERC20 interface you have to "support" all the possible behaviors someone could introduce to their implementation (this is simply not possible for the spec as written).

Fee on transfer is a popular behavior, but there is no standard implementation or specification that makes it easy to support it (e.g. fixed fee vs flat fee vs random fee, methods that let you read the fee information on-chain), so it's a large engineering burden. We did not make incorrect assumptions, we chose not to support it in V3 periphery, and the same is true of the first version of the V2 router. If you would like to help you're welcome to try to make this information easier to extract, e.g.:
https://github.com/Uniswap/uniswap-v3-periphery/issues/170
