### ISSUE TITLE
I would like to add tokens. Farmer And One Token

### ISSUE THREAD

**Issue by farmerandone** [Uniswap/uniswap-interface#2013]
"name": "Farmer And One Token",
    "website": "https://farmeone.co.kr",
    "Description": "Farmer And One Token is a coin issued by Kanorak based on Ethereum ERC20.",
    "explorer": "https://etherscan.io/token/0xb8305439e5de26b4f913a5d9f3cca433f6700047",
    "type": "ERC20",
    "symbol": "FAO",
    "decimals": 18,
    "status": "active",
    "id": "0xb8305439e5de26b4f913a5d9f3cca433f6700047"

**Comment by willhennessy** [comment]
Hello, please submit your request here: https://github.com/Uniswap/default-token-list/issues/new?assignees=&labels=token+request&template=token-request.md&title=Add+%7BTOKEN_SYMBOL%7D%3A+%7BTOKEN_NAME%7D
