### ISSUE TITLE
<--- Last few GCs ---> <--- JS stacktrace --->

### ISSUE THREAD

**Issue by TouchSKY453** [Uniswap/uniswap-interface#2059]
**Bug Description**

<--- Last few GCs --->

[12777:0x5593300]   146003 ms: Scavenge 466.8 (485.6) -> 463.5 (485.6) MB, 1.9 / 0.0 ms  (average mu = 0.425, current mu = 0.430) allocation failure 
[12777:0x5593300]   146014 ms: Scavenge 466.1 (486.9) -> 464.3 (486.4) MB, 1.9 / 0.0 ms  (average mu = 0.425, current mu = 0.430) allocation failure 
[12777:0x5593300]   146947 ms: Mark-sweep 481.2 (503.3) -> 479.6 (501.0) MB, 880.6 / 0.0 ms  (average mu = 0.392, current mu = 0.332) allocation failure scavenge might not succeed

<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb22900 node::Abort() [/usr/local/bin/node]
 2: 0xa3c161 node::FatalError(char const*, char const*) [/usr/local/bin/node]
 3: 0xd0b15e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 4: 0xd0b4d7 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 5: 0xeec565  [/usr/local/bin/node]
 6: 0xefb295 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/bin/node]
 7: 0xefe38c v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/bin/node]
 8: 0xec2dbc v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/usr/local/bin/node]
 9: 0x123977b v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/usr/local/bin/node]
10: 0x16437d9  [/usr/local/bin/node]
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Steps to Reproduce**
1. git clone
2. yarn install
3. yarn run start    
   ...
I didn't do anything

**Comment by moodysalem** [comment]
how much memory do you have on the machine you're using? shouldn't run out of memory compiling the app, but it's possible if you have very little

**Comment by moodysalem** [comment]
think it's just a local issue
