### ISSUE TITLE
Wallet Connect `wc_sessionRequest` method contains invalid data

### ISSUE THREAD

**Issue by random-internet-guy** [Uniswap/uniswap-interface#2060]
**Bug Description**
The wallet connect session data is non-compliant. The wallet connect protocol states the `chainId` field should be an integer. Instead of an integer a string "MAINNET" is provided. This breaks any wallet that relies on the correct chain ID to be provided. Included is a JSON returned in the `wc_sessionRequest` method:

```JSON
{
   "id":1626358580021537,
   "jsonrpc":"2.0",
   "method":"wc_sessionRequest",
   "params":[
      {
         "peerId":"410f52da-1f48-495b-b018-a534f7cdc840",
         "peerMeta":{
            "description":"",
            "url":"https://app.uniswap.org",
            "icons":[
               "https://app.uniswap.org/./favicon.png",
               "https://app.uniswap.org/./images/192x192_App_Icon.png",
               "https://app.uniswap.org/./images/512x512_App_Icon.png"
            ],
            "name":"Uniswap Interface"
         },
         "chainId":"MAINNET"
      }
   ]
}
```

**Steps to Reproduce**

Go to the uniswap website
Scan a wallet connect QR code
Observe the data returned by `wc_sessionRequest`
   ...

**Expected Behavior**
the `chainId` field should provide an integer representing the chain ID of the network, i.e. 1 for ethereum mainnet

**Additional Context**
Not applicable

**Comment by moodysalem** [comment]
This bug was introduced with today's release, working on it now.

**Comment by moodysalem** [comment]
It should be fixed here https://github.com/Uniswap/uniswap-interface/commit/08a8f669e8d56c90d78483033c115bc83d568e42

Kicking off a release now

**Comment by moodysalem** [comment]
It should be fixed, thank you for reporting

**Comment by random-internet-guy** [comment]
Nice work. Thanks for the prompt response.
