### ISSUE TITLE
Loader icon missing

### ISSUE THREAD

**Issue by willhennessy** [Uniswap/uniswap-interface#2065]
**Bug Description**
While a transaction is pending approval in your wallet, the loading spinner icon is not loading correctly.

**Steps to Reproduce**

1. Connect to any network (L1 or L2)
2. Enter trade details, press swap
3. When the wallet signature screen appears, look at the loading spinner in uniawap app

![image](https://user-images.githubusercontent.com/5455577/125965573-1598151b-042a-4e71-891c-80b07c7a06b2.png)

`ipfs resolve -r /ipns/app.uniswap.org/static/media/blue-loader.249140da.svg: failed to get block for QmagpeHUN2mMauwu6qCUTjwkxV7QCCFUcZJTzzPhazqRC8: context deadline exceeded`

**Comment by moodysalem** [comment]
It's pinned to IPFS in pinata, and I can fetch it from cloudflare's IPFS gateway

https://gateway.pinata.cloud/ipfs/QmagpeHUN2mMauwu6qCUTjwkxV7QCCFUcZJTzzPhazqRC8/static/media/blue-loader.249140da.svg

https://cloudflare-ipfs.com/ipns/app.uniswap.org/static/media/blue-loader.249140da.svg
