### ISSUE TITLE
Unable to add liquidity to a token liquidity pair on Uniswap rinkeby testnet

### ISSUE THREAD

**Issue by fnhh04** [Uniswap/uniswap-interface#2105]
Hi Sir/Ms,

I have deployed a token (TEST) on Rinkeby testnet with the code as attached successfully but I was unable to add liquidity to the token pair (ETH/TEST) on the Uniswap app. My token has a 7% fee on transferFrom function for users who sell the token (add liquidity) on Uniswap and I'm not sure if this is causing the issue. Please advise how I may resolve this issue. 
[ERC20tokenSwapFee.txt](https://github.com/Uniswap/uniswap-interface/files/6872679/ERC20tokenSwapFee.txt)

**Comment by moodysalem** [comment]
Duplicate of https://github.com/Uniswap/uniswap-interface/issues/2010
