### ISSUE TITLE
Hot reloading doesn't work on windows

### ISSUE THREAD

**Issue by GiorgiSheklashvili** [Uniswap/uniswap-interface#2111]
**Bug Description**
When I'm editing and saving .ts files the project is not doing hot reloading and I need to run the project again to see the updates.

**Steps to Reproduce**

1. yarn start
2. edit any .ts file
3. Save it

**Expected Behavior**
Hot reloading of the project

**Additional Context**
I'm running my project from WSL of Windows 10 using Visual studio code.
I've created new project with "npx create-react-app my-app --template typescript" command to check if hot reloading works on my computer and it worked as expected.

**Comment by willhennessy** [comment]
Hi Giorgi, please visit the developer channel in our discord for help with this
