### ISSUE TITLE
Uniswap interface is not compatible with 1559 type 2 tx

### ISSUE THREAD

**Issue by crazybae** [Uniswap/uniswap-interface#2115]
**Bug Description**

We are developing a chrome extension-based wallet, called Dekey (www.dekey.app).
It fully supports coin/token transfer and Dapp-browsing in ethereum based chains including layer 2.

Recently, we have completed the development of EIP1559 type 2 tx functions and is testing in various Dapps including Uniswap in ropsten and rinkeby.  The production build will be deployed in the chrome app store at the end of this week.

As you know, there is no 'gasPrice' field in the type 2 tx, instead 'maxPriorityFeePerGas' and 'maxFeePerGas' should be inserted.  As shown in the attached image, Uniswap interface in ropsten still seems to require 'gasPrice' field in the tx result (delivered by a wallet) though the tx is processed well as a type 2 in the chain (see the following url).

https://ropsten.etherscan.io/tx/0x16a6a340df23f7f1978a5b54ff4e648c2c04eae4cf4a701024ac6ef73e7de715

**Steps to Reproduce**

1. Perform EIP1559 type 2 tx in Uniswap ropsten
2. You will meet the error like the attached image
3. See the tx result in etherscan

**Expected Behavior**
Uniswap interface should process the tx result differently depending on the tx type.

![image](https://user-images.githubusercontent.com/31330427/127022722-cd5a5900-ba58-4e10-a9b4-e86c5a5961fb.png)

**Comment by moodysalem** [comment]
London hard fork coming to mainnet in a week or two, need to fix this ASAP

**Comment by moodysalem** [comment]
related
https://github.com/ethers-io/ethers.js/issues/1610
https://github.com/ethers-io/ethers.js/issues/1766

**Comment by moodysalem** [comment]
@crazybae would you mind testing the PR deployment preview? https://uniswap-interface-git-upgrade-ethers-eip1559-uniswap.vercel.app/

**Comment by crazybae** [comment]
I works perfectly.  Thanks for your time and effort.
https://ropsten.etherscan.io/tx/0x11fa5739d60e4645487970783967482618c7aa903e8e23746b0c6154a888f567
