### ISSUE TITLE
Hello, help me, please, I withdrawn money for about 12 exchanges, until the funds ran out .... And without making a non-onin exchange, what should I do? is there any way to get the money back?

### ISSUE THREAD

**Issue by Roman6991** [Uniswap/uniswap-interface#2127]
Hello, help me, please, I withdrawn money for about 12 exchanges, until the funds ran out .... And without making a non-onin exchange, what should I do? is there any way to get the money back?

**Comment by Roman6991** [comment]
Hello, help me, please, I withdrawn money for about 12 exchanges, until the funds ran out .... And without making a non-onin exchange, what should I do? is there any way to get the money back?

**Comment by willhennessy** [comment]
Hi Roman, I'm sorry to hear about your trouble. It's unlikely that we can do much to help, but can you please describe your issue in more detail?

**Comment by Roman6991** [comment]
Here are all the transactions for debiting funds .. The exchange did
not work in more than one ... but the commission was written off ....
If it was my mistake and it is not possible to return the money, then
what did I do wrong and how can I avoid it in the future?



пн, 2 авг. 2021 г. в 20:37, Will Hennessy ***@***.***>:

**Comment by willhennessy** [comment]
What transactions?
