### ISSUE TITLE
When no default Fee Tier on Optimism, it still requires hitting "Edit"

### ISSUE THREAD

**Issue by asood123** [Uniswap/uniswap-interface#2148]
**Bug Description**
Fee Tier section requires hitting `Edit` even when no fee tier is suggested by default. I thought we were only hiding the choice of fee tiers when we defaulted to one.

**Steps to Reproduce**

1. Create new position on Optimism
2. Select ETH and DAI
3. Fee tier section lights up with "Edit" button but no default fee tier. 
   ...

**Expected Behavior**
I expected to see the three fee tiers open, rather than having to hit "Edit" first - when no default fee tier selected for the user.

**Additional Context**
![image](https://user-images.githubusercontent.com/6106941/128634883-6b07be3b-8168-4a59-ae4d-c7908d8474cf.png)

**Comment by asood123** [comment]
On mainnet, same steps preselect a fee tier

![image](https://user-images.githubusercontent.com/6106941/128634869-8aa160df-5f1b-478f-8dcd-440b8d97f4a2.png)

**Comment by justindomingue** [comment]
The options are expanded when I test here: https://app.uniswap.org/#/add/ETH/0xDA10009cBd5D07dd0CeCc66161FC93D7c9000da1.

@asood123 do you have more repro steps?

**Comment by asood123** [comment]
Now it's showing this: 
![image](https://user-images.githubusercontent.com/6106941/131387245-a954d7d5-3d78-42f9-9e22-b5fb176ec2c4.png)

Shouldn't the % selection add up to 100?

**Comment by justindomingue** [comment]
weird.. the optimism subgraph is down right now so not sure how you are getting data. I'm getting an indexing error when I try it.

**Comment by asood123** [comment]
Maybe I got partial data or something like that? Can check once it's back.

**Comment by justindomingue** [comment]
AFAICT the optimism subgraph is now back to normal.

I did notice that L2s update blocks more often and the data goes stale more quickly. Adjusted the freshness params.
