### ISSUE TITLE
Some methods of interaction between the embedded DApp and UniSwap in the wallet are invalid

### ISSUE THREAD

**Issue by hongyantao** [Uniswap/uniswap-interface#2189]
(Kotlin) After loading UniSwap with webView in the wallet and the authorization is successful, the payment cannot be canceled, the token cannot be authorized, and there is no notification after the payment is successful. Is there a development document for the developer?

**Comment by moodysalem** [comment]
I don't understand, seems like you're trying to build some kind of wallet that injects an ethereum provider into the window? This doesn't seem like a bug with the interface.

**Comment by hongyantao** [comment]
@moodysalem Develop files, documents, guides to Android employees? I need it now.
