### ISSUE TITLE
Safari pool layout bug

### ISSUE THREAD

**Issue by willhennessy** [Uniswap/uniswap-interface#2190]
**Bug Description**
Reported by Mike demarais on mobile Safari. I can't repro on Android chrome.
![IMG_20210810_224239](https://user-images.githubusercontent.com/5455577/128964483-4df9c4e2-0a97-4ff6-8c67-2b668f5b8aaa.jpg)

**Steps to Reproduce**
All pool pages on mobile safari

**Comment by hanabi62513** [comment]
英語で何言ってるのかわかりませんちゃんと教えてください

2021年8月11日(水) 12:21 Will Hennessy ***@***.***>:
