### ISSUE TITLE
builds are no longer deterministic

### ISSUE THREAD

**Issue by moodysalem** [Uniswap/uniswap-interface#2198]
**Bug Description**
these two releases are on the same commit
https://github.com/Uniswap/uniswap-interface/releases/tag/v4.12.9
https://github.com/Uniswap/uniswap-interface/releases/tag/v4.12.8

however they got different ipfs hashes

this hurts reproducibility! meaning it's hard for someone to pull this code down and build it and get the same result

**Comment by zzmp** [comment]
NB: The release name is not used when hashing the content ([docs](https://docs.pinata.cloud/api-pinning/pin-by-hash#:~:text=The%20%22pinataMetadata%22%20object%20will%20not%20be%20part%20of%20your%20content%20added%20to%20IPFS))

**Comment by zzmp** [comment]
Inspecting these assets through the [IPFS UI](webui.ipfs.io), the generated assets have different hashes:

- https://webui.ipfs.io/#/ipfs/QmNtfcu9bM8H7DmFx6rY8miEYvWRnJNZP2oroEN84Yb1D2
- https://webui.ipfs.io/#/ipfs/QmTxc2b8fWLPUr5Lmu7qAa7CyJ53awVZVeNYREp1PYh6Mf

Looking further into it, some of these files include a "POT-Creation-Date", which would account for distinct hashes:

```
% diff <(ipfs cat QmNtfcu9bM8H7DmFx6rY8miEYvWRnJNZP2oroEN84Yb1D2/asset-manifest.json) <(ipfs cat QmTxc2b8fWLPUr5Lmu7qAa7CyJ53awVZVeNYREp1PYh6Mf/asset-manifest.json)
109c109
<     "static/media/en-US.po": "./static/media/en-US.7e35a75a.po",
---
>     "static/media/en-US.po": "./static/media/en-US.213282ec.po",
```

```
% diff <(ipfs cat QmNtfcu9bM8H7DmFx6rY8miEYvWRnJNZP2oroEN84Yb1D2/static/media/en-US.7e35a75a.po) <(ipfs cat QmTxc2b8fWLPUr5Lmu7qAa7CyJ53awVZVeNYREp1PYh6Mf/static/media/en-US.213282ec.po)
3c3
< "POT-Creation-Date: 2021-08-10 14:34+0000\n"
---
> "POT-Creation-Date: 2021-08-11 12:07+0000\n"
```

I think it's likely that it's just this file (a translation file?), being required in other files and making the hashes non-deterministic.

**Comment by zzmp** [comment]
This occurs because en-US internationalization is not committed, so it is regenerated (with a new creation date) with every release. This has occured since May 29, with https://github.com/Uniswap/uniswap-interface/commit/408a07ebd49aa11625866b6de13ce96e8a3722cd.
