### ISSUE TITLE
Pasted Address for Token Doesn't Show Up

### ISSUE THREAD

**Issue by Mentors4EDU** [Uniswap/uniswap-interface#2216]
Hi, the pasted address for the token at: [0x1da4858ad385cc377165a298cc2ce3fce0c5fd31](https://etherscan.io/token/0x1da4858ad385cc377165a298cc2ce3fce0c5fd31) doesn't show up when somebody tries adding it to Uniswap. It is as if it isn't recognized at all. This is a bit problematic. Is there a way to whitelist the address so this can be fixed?

**Comment by moodysalem** [comment]
Probably because it doesn't implement decimals, which we need in order to parse user input.

**Comment by Mentors4EDU** [comment]
Hi, @moodysalem that is exactly what the problem is. I think I know what to do now. Thanks.
