### ISSUE TITLE
Incorrect infura node address for alternative chains connected via WalletConnect

### ISSUE THREAD

**Issue by MikaelLazarev** [Uniswap/uniswap-interface#2238]
**Bug Description**
App uses mainnet infura node to get information even if another network was used using WalletConnect

**Steps to Reproduce**

1. Connect Wallet Connect with Kovan (or any other testnet network)
2. Choose a token which is deployed on this net, but doesn't exists on Mainnet
2. Check console. You'll see that app tries to connect mainnet.infura... to get info and gets error

**Expected Behavior**
Switch node address to one which is needed to get correct onchain data.

**Comment by willhennessy** [comment]
closing because this is a bug in walletconnect and their team is aware of it

**Comment by moodysalem** [comment]
sorry i was working on this, i just pushed a fix to walletconnect
