### ISSUE TITLE
Add Arbitrum token list to interface

### ISSUE THREAD

**Issue by willhennessy** [Uniswap/uniswap-interface#2250]
The Arbitrum token list should be added to the interface and enabled on by default.

https://bridge.arbitrum.io/token-list-42161.json

https://docs.google.com/document/d/16HvbGKbvWkuvCN-PZGDmQMlD02hpa3jpfDZxeGqJ2Uw/edit#

**Comment by willhennessy** [comment]
possibly relevant:  when I try to manually import the Arbitrum token list, I get an "Error importing list"

https://bridge.arbitrum.io/token-list-42161.json

> Access to fetch at 'https://bridge.arbitrum.io/token-list-42161.json' from origin 'https://app.uniswap.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by zzmp** [comment]
The arbitrum token list is misconfigured. It should be sending the 'Access-Control-Allow-Origin' header to avoid this error, as documented in https://github.com/Uniswap/token-lists#deploying-your-list.
