### ISSUE TITLE
Auto fee tier on L2

### ISSUE THREAD

**Issue by willhennessy** [Uniswap/uniswap-interface#2253]
On Optimism and Arbitrum, auto fee tier is not triggering. Fee tier edit menu opens up with none selected. When I click on a fee tier, the chart says no data available but I know for sure there is liquidity in ETH/DAI.

We are experiencing issues with Optimism on The Graph right now. Could that be the cause?

But this occurs on Arbitrum too

<img width="925" alt="Screen Shot 2021-08-29 at 3 47 20 PM" src="https://user-images.githubusercontent.com/5455577/131263518-508919aa-7df2-40ab-96fe-0c3ee1526fbb.png">

**Comment by justindomingue** [comment]
We consider the graph data stale if the latest synced block is > 10 from the app block: https://github.com/Uniswap/uniswap-interface/blob/main/src/hooks/useFeeTierDistribution.ts#L14

**Comment by justindomingue** [comment]
For Arbitrum, @ianlapham is this still the right subgraph? https://github.com/Uniswap/uniswap-interface/blob/main/src/state/data/slice.ts#L13

**Comment by justindomingue** [comment]
On optimism, I'm getting `message: "indexing_error"` from the subgraph which I believe is expected based on the current state of the subgraph.

On Arbitrum, I do get data from the subgraph for usdc-eth for example. So I think it's an issue of early chain state. Data should fill up once it goes live.

**Comment by justindomingue** [comment]
@willhennessy I'll close this issue as WAI (optimism issue is also being tracked elsewhere).
