### ISSUE TITLE
Integration tests occasionally fail with `SecurityError: Blocked a frame with origin "http://localhost:3000" from accessing a cross-origin frame.`

### ISSUE THREAD

**Issue by cmcewen** [Uniswap/uniswap-interface#2265]
**Bug Description**
Integration tests occasionally fail with this error: `SecurityError: Blocked a frame with origin "http://localhost:3000" from accessing a cross-origin frame.`

**Steps to Reproduce**

1. Open a new PR
2. Wait for tests to maybe fail

**Expected Behavior**
Test should not fail unexpectedly

**Additional Context**
Sample run https://github.com/Uniswap/uniswap-interface/runs/3466096055?check_suite_focus=true

**Comment by zzmp** [comment]
Fixed with #2274
