### ISSUE TITLE
Add R64X

### ISSUE THREAD

**Issue by musHo** [Uniswap/uniswap-interface#2297]
Token name: 
`R64X`

Token/Contract address: 
`0xf3110b27f481f9ac3c1ba3c54de542accb2d913c
`

Token ERC20 Registry
https://etherscan.io/token/0xf3110b27f481f9ac3c1ba3c54de542accb2d913c

More info about token: 
https://r64x.com/

**Comment by willhennessy** [comment]
hello, please submit here: https://github.com/Uniswap/default-token-list/issues/new?assignees=&labels=token+request&template=token-request.md&title=Add+%7BTOKEN_SYMBOL%7D%3A+%7BTOKEN_NAME%7D
