### ISSUE TITLE
`string#replaceAll` may be causing browser incompatibility crashes

### ISSUE THREAD

**Issue by moodysalem** [Uniswap/uniswap-interface#2308]
https://github.com/Uniswap/uniswap-interface/blob/416a3f943357cfa25df9f66131179c922e9bea02/src/state/governance/hooks.ts#L138

https://caniuse.com/mdn-javascript_builtins_string_replaceall

**Comment by willhennessy** [comment]
related https://github.com/Uniswap/uniswap-interface/issues/2293

**Comment by NoahZinsmeister** [comment]
closing in favor of #2308
