### ISSUE TITLE
Call window.parent.postMessage when transaction is mined successfully

### ISSUE THREAD

**Issue by safareli** [Uniswap/uniswap-interface#350]
**Is your feature request related to a problem? Please describe.**
When embedding uniswap page in an app using an iframe in a dialog, you would like to know if user successfully purchased a token, so you can react to it by closing the dialog automatically.

**Describe the solution you'd like**
Solution would be to do execute `window.parent.postMessage(msg,"*")` when:
- swap transaction is mined
- send transaction is mined
- poll transaction is mined

And then parent can do:
```js
window.addEventListener("message", function(event) {
  if (event.origin == 'https://uniswap.exchange') {
    alert( "received: " + event.data );
    return;
  }
});
```
**Describe alternatives you've considered**
There is no alternative solution as you can't look into the iframe from different origin. `postMessage` api is way to communicate between pages from different origin.

**Additional context**

**Comment by moodysalem** [comment]
I'm concerned about the privacy implications of doing this, why should the parent window be entitled to information about the user's actions in Uniswap? Also not sure there's a way to do this that is privacy-safe, i.e. the host of the iframe can reliably link the IP or user agent to the swap/add/remove liquidity event with only the token address and the timestamp
