### ISSUE TITLE
Move token listing requests to a separate repo that is used as a package from the front end

### ISSUE THREAD

**Issue by pcowgill** [Uniswap/uniswap-interface#510]
**Is your feature request related to a problem? Please describe.**
I'd like to follow all of the activity on this repo other than token requests, but token requests end up being most of the activity.

**Describe the solution you'd like**
Move token listing requests and functionality to a separate repo that is imported as a package in this front end repo.

**Describe alternatives you've considered**
I haven't come up with any good alternatives.

**Additional context**
![Screenshot 2019-11-18 13 57 54](https://user-images.githubusercontent.com/2731712/69085349-7a3da600-0a0b-11ea-8039-d6ded888c7c5.png)

**Comment by moodysalem** [comment]
https://github.com/Uniswap/default-token-list
