### ISSUE TITLE
Add native Ledger and Trevor support

### ISSUE THREAD

**Issue by haydenadams** [Uniswap/uniswap-interface#518]

**Comment by thedavidmeister** [comment]
for example this happened and i cannot use uniswap with my ledger right now :(

https://github.com/MetaMask/metamask-extension/issues/8157

**Comment by victorelec14** [comment]
still no news?

**Comment by thedavidmeister** [comment]
topical with the nexus mutual hack targeting metamask

**Comment by moodysalem** [comment]
It would be great if Ledger/Trezor considered implementing some sort of WalletConnect bridge app, which would make them broadly compatible with dapps.
