### ISSUE TITLE
Show DAI value for Chai/DAI-HRD/cDAI

### ISSUE THREAD

**Issue by ChristophSiegenthaler** [Uniswap/uniswap-interface#570]
Wouldn't it be beneficial to have the actual DAI values in the exchange rate info? Or would this be too confusing?
a la: 1 ETH = 127 CHAI  = 128 DAI
I could see this as helpful for some of the compound tokens or interest earning DAI variants.

**Comment by NoahZinsmeister** [comment]
hey @ChristophSiegenthaler, this is a cool idea! it'd be nice if we could figure out some way to generically show the exchange rates for all assets of this type that are redeemable for another asset.

**Comment by ChristophSiegenthaler** [comment]
Maybe in combination with https://github.com/Uniswap/uniswap-frontend/issues/466?

**Comment by ChristophSiegenthaler** [comment]
Ideally with the actual rates from the contracts, i.e. by reading calculatedChi from the DAI-HRD contract etc. I tried implementing something but I haven't come up with a clean solution that works for some tokens yet (only patchwork and unclean code so far...) Help on this one would be appreciated :)

**Comment by moodysalem** [comment]
I think showing the fiat prices of assets should sufficiently cover this use case

**Comment by ChristophSiegenthaler** [comment]
Agreed. The Chai/DAI-HRD pairs have lost a lot of their appeal with the DSR at 0% :)
