### ISSUE TITLE
Portis doesn't work in Safari

### ISSUE THREAD

**Issue by paulrberg** [Uniswap/uniswap-interface#592]
**Bug Description**
I cannot connect to Portis wallet while using Uniswap in Safari.

**Steps to Reproduce**
1. Go to https://uniswap.exchange in Safari on OSX
2. Click on "Connect to a Wallet"
3. Select Portis
4. See the never-ending spinner

**Expected Behavior**
I should be able to connect my Portis wallet.

**Additional Context**
I made sure that the "Prevent cross-site tracking" and "Block all cookies checkboxes" privacy settings are turned off, as this is known to cause issues with other wallets like Wallet Link.

[Here's a screen recording for you](https://imgur.com/a/ACpbhJ6).

**Comment by NoahZinsmeister** [comment]
im seeing a 401 on https://api.portis.io/auth/is-dapp-authorized

**Comment by tomteman** [comment]
Looking into this, Safari has made some breaking changes revolving around the samesite flag

**Comment by tomteman** [comment]
https://bugs.webkit.org/show_bug.cgi?id=200857

:(

**Comment by PaulRBerg** [comment]
Thanks for debugging this, Tom! Sorry to hear this can't be fixed in Safari 13.

**Comment by moodysalem** [comment]
seeing as the bug is resolved and we have a separate issue to add portis back, this is obsolete
