### ISSUE TITLE
Certain mobile wallets cannot be connected if not authorised first

### ISSUE THREAD

**Issue by paulrberg** [Uniswap/uniswap-interface#593]
**Bug Description**
The list of connectable wallets appears as empty on some mobile wallets, such as Opera, after not granting access to the user's account the first time the dapp is opened.

**Steps to Reproduce**
1. Download Opera mobile on iOS or Android
2. Go to https://uniswap.exchange
3. Tap "Not Authorize"
4. Tap "Connect to a Wallet"
5. See an empty list

**Expected Behavior**
I should be able to connect my wallet even if I did not authorise it the first time.

**Additional Context**
Note that if you authorise it first, it works well. If you don't do it though, the only way to get it back working is by going to the settings and clearing your cache and cookies.

[Here's a screen recording for you](https://imgur.com/a/EQRRMOY) and a [related discussion on Twitter](https://twitter.com/intocryptoast/status/1213236701474304000).

**Comment by PaulRBerg** [comment]
I suspect this causes the bug:

https://github.com/Uniswap/uniswap-frontend/blob/beta/src/components/WalletModal/index.js#L202
