### ISSUE TITLE
a bug in uniswap page on Coingecko

### ISSUE THREAD

**Issue by GRMcoin** [Uniswap/uniswap-interface#707]
**Bug Description**
Dear Adams
Green Money (GRM) listed on Coingecko, but there is no connection between GRM on Coingecko and your exchange.
In other words, GRM trading on uniswap has no effect on GRM info on Coingecko.
Please help me.
Sincerely,
GRM team

https://www.coingecko.com/en/coins/green-money

**Steps to Reproduce**
1. Go to https://www.coingecko.com/en/coins/green-money
2. Find GRM/ETH
3. There is a ? In place of token name. The link of token on Coingecko is below but it is not appear and just show "?" GRM/ETH

**Expected Behavior**
Please connect Green Money (GRM) on your exchange with it's page on Coingecko

**Additional Context**
Add any other context about the problem here (screenshots, whether the bug only occurs only in certain mobile/desktop/browser environments, etc.)

**Comment by moodysalem** [comment]
Please reach out to coingecko
