### ISSUE TITLE
`window.postMessage` when widget size changes.

### ISSUE THREAD

**Issue by MicahZoltu** [Uniswap/uniswap-interface#721]
When embedding Uniswap as an iframe within a page, the UI may change sizes due to various user interactions such as expanding hidden sections, switching tabs, etc.  Unfortunately, browser iframe security prevents the hosting page from being aware of the internal sizing requirements of an iframe and thus the space allocated to the iframe cannot change automatically as the contents of the iframe change size.

In order to enable having the iframe resize to match its contents, the hosted page can use `window.postMessage` to communicate the sizing changes in a way that the host page can listen for and process.  You would just need to setup an event listener that fired anytime the hosted page changed size and fire that in a custom message to the window via `window.postMessage`.  The host page can then listen for those messages and when it receives one such message it can resize the iframe container to match the requirements.

**Comment by moodysalem** [comment]
I think a better solution is just to make the Uniswap swapping widget more responsive/tailored for embedding. Iframes shouldn't have to resize for their contents.

**Comment by MicahZoltu** [comment]
While I agree the widget should be responsive, that only supports top down layouts.  The widget should be able to be integrated in a bottom up layout where the widget tells it's container how big it is so the container can correctly size to fit it.  An alternative would be to have a very well defined static size that always correctly fits all parts of the UI that can be relied on (not currently the case).

**Comment by moodysalem** [comment]
>  the widget tells it's container how big it is so the container can correctly size to fit it.

even if the widget tells the container how big it is, the container is constrained by the size of the viewport, which is constrained by the device, so the parent page has to be responsive which forces the widget to be responsive

we can make a route (e.g. `/widget`) that renders a swapping widget that is responsive to both horizontal and vertical viewport as a proper solution

**Comment by MicahZoltu** [comment]
A good web page will be responsive in both directions (top down and bottom up).  For example, if you have a Uniswap widget in the middle of a vertical layout (e.g., a flex box) with content both above and below it, you may tell the widget how much width it has and then expect it to tell you how much height it has so you know how much vertical space to allocate it so it doesn't end up with a scroll bar.  As the horizontal width available to the widget changes, the vertical space it takes up changes.  If you do not have feedback in both directions then the two options are either hard-code a height that works in some cases but results in scrollbars in others, or you allocate enough vertical space such that you never have a scroll bar but in some cases you have a giant amount of wasted vertical space.

The one way to solve this *without* posting size changes to the host window would be to build multiple widgets that are all fixed size.  This way the page could pick the appropriate widget for the layout and integrate it tightly into the parent page.  With Uniswap v2, there is a single widget for swapping and adding liquidity and the user may switch between views.  Each view has different size requirements which is why this is a problem.
