### ISSUE TITLE
Add liquidity white screen

### ISSUE THREAD

**Issue by NoahZinsmeister** [Uniswap/uniswap-interface#848]
Visiting https://uniswap.exchange/add/0xc7AD46e0b8a400Bb3C915120d284AafbA8fc4735-0x44d59BB22ADfEf65de3BCB30685732D8b55f8061 on Rinkeby causes a white screen

**Comment by moodysalem** [comment]
![image](https://user-images.githubusercontent.com/7897876/83361582-1a2fa100-a358-11ea-9238-0f596888c2a5.png)

**Comment by NoahZinsmeister** [comment]
this is a very special case due to the deflationary nature of the specific token in question. it's not clear what the appropriate course of action is here.
