### ISSUE TITLE
recipient address and value is not filled out for send

### ISSUE THREAD

**Issue by ligi** [Uniswap/uniswap-interface#857]
the following URL works with v1: https://v1.uniswap.exchange/send?exactField=output?exactAmount=0.00338&inputCurrency=0x6b175474e89094c44da98b954eedeac495271d0f&outputCurrency=ETH&recipient=0x0402c3407dcbd476c3d2bbd80d1b375144baf4a2

but when using the very same with v2 like this:

https://uniswap.exchange/send?exactField=output?exactAmount=0.00338&inputCurrency=0x6b175474e89094c44da98b954eedeac495271d0f&outputCurrency=ETH&recipient=0x0402c3407dcbd476c3d2bbd80d1b375144baf4a2

the recipient address and value are not filled out for send

**Comment by moodysalem** [comment]
this now works
