### ISSUE TITLE
Unable to remove liquidity from SNX pool

### ISSUE THREAD

**Issue by Newmanford** [Uniswap/uniswap-interface#860]
I am unable to remove liquidity from the SNX pool, error shown by Metamask: 
``` {code: -32000, message: "gas required exceeds allowance (9990259) or always failing transaction"} ```
If i try to remove liquidity using zapper.fi, the transaction reverts, example [here](https://etherscan.io/tx/0xb9c91a40a8314709f140d20f69190ca98f2cdb0ceecfd8b70f49a36a70c0970a )
Screenshot:
![liq](https://user-images.githubusercontent.com/66457538/83839718-2c506d00-a6d3-11ea-92d7-a9cb39e2ed35.png)

What is causing this? and how to fix it? Please provide some assistance.
Thanks

**Comment by mattleong** [comment]
I am also seeing the same error when trying to swap PAMP -> ETH as well as when I try to pool ETH+SLP.

**Comment by moodysalem** [comment]
v1 interface issue

**Comment by oikos1** [comment]
A bit of a generic answer. Is it enough to close the issue in your opinion?

**Comment by moodysalem** [comment]
The code referenced by the issue is completely different-if you want to remove SNX liquidity from Uniswap V1 I recommend you try https://app.uniswap.org/#/migrate/v1

**Comment by trappist** [comment]
Workaround found elsewhere if this is still an issue: it seems to work if you elect to take weth instead of eth.
