### ISSUE TITLE
Change "Create Pool" to "Add Pool"?

### ISSUE THREAD

**Issue by danrobinson** [Uniswap/uniswap-interface#891]
On uniswap.exchange/pool, the “+ Create Pool” button is a little confusing, since it's not clear that that's where you should go to import a pool that is not listed. (You could click Join Another Pool and then click "Import it.", but that's counterintuitive if you're adding a pool that you already have liquidity in.) 

“+ Add Pool” seems like it would cover both meanings of "Create" and "Import".

**Comment by moodysalem** [comment]
create pool is gone now
