### ISSUE TITLE
Add PieDAO usd++

### ISSUE THREAD

**Issue by MickdeGraaf** [Uniswap/uniswap-interface#899]
**Please provide the following information for your token.**

Token Address: 0x9a48bd0ec040ea4f1d3147c025cd4076a2e71e3e
Token Name (from contract): PieDAO USD++ Pool
Token Decimals (from contract): 18
Token Symbol (from contract): USD++
Uniswap Exchange Address of Token: 0x17a791d8e241d4be11a59f7073b3122bb019facd

Link to the official homepage of token: usd.piedao.org
Link to CoinMarketCap or CoinGecko page of token: https://www.coingecko.com/nl/coins/piedao-usd

Some tokens (e.g. BNB) do not work with Uniswap v1. In order to assess if your token works correctly, please complete small-value transactions of each of the types below, and submit the Etherscan transaction links for our review.
Test `addLiquidity` transaction: 0xfef82281269eebf4cadee0e6a73974777499601295c97b536d2b3d66e625dbd6
Test `swap` transaction: 0x483ee8fddacae4943a44c25936cdc47b09495f0f213c4542110bfd55cd520644
Test `removeLiquidity` transaction: 0x50fcb90892f0309d96058968ed3fa5f4788f8a70e75e4fe787a576185cddbf5a

Are you willing to add liquidity to the liquidity pool for this token? (Y/N): Y
If so, how much liquidity are you willing to add?: I added 500 DAI and 500 USD++. The community will add more once listed

**Comment by MickdeGraaf** [comment]
@NoahZinsmeister Have you had the chance to take a look? USD++ now has a marketcap of over 1.5M USD but people have no easy way to supply liquidity for on Uniswap.

**Comment by moodysalem** [comment]
will go with tomorrow morning's deploy

**Comment by erieza09za08** [comment]
Fj xymعبد الجليل سعيد عبد فارع واريد الحفاظ العوائد وتشجيعنا نحن اخوة واصدقاء ونكون دوما وال
