### ISSUE TITLE
Improve "Approve & confirm" flow

### ISSUE THREAD

**Issue by callil** [Uniswap/uniswap-interface#960]
Right now a few people get stuck when swapping token -> ETH because they don't notice there are two buttons. We should add a simple progress bar underneath the buttons to help them notice there are two actions.

<img width="433" alt="Screen Shot 2020-07-15 at 11 44 50 AM" src="https://user-images.githubusercontent.com/1355319/87566190-a4299400-c690-11ea-89d1-49086623be02.png">

A better approach would be to attempt to use metatx and do a true approve&confirm in one transaction. It would be pretty nice if this were possible, especially if there was a way to avoid approving the max amnt of tokens to swap on each address and just doing it up to some reasonable limit based on the tx they are trying to execute.

**Comment by moodysalem** [comment]
This is covered by https://github.com/Uniswap/uniswap-interface/issues/1072
