### ISSUE TITLE
Error : Big Integer 0x00

### ISSUE THREAD

**Issue by cryptofanz** [Uniswap/uniswap-interface#973]
Hello, 
![Screenshot_2020-07-19-02-49-00-76_08800057d42e3b72e31ae4fd4c41ba57](https://user-images.githubusercontent.com/68485084/87863754-c7de2a00-c96f-11ea-9c0c-69b5b44284ba.jpg)
I have connected trust wallet on uniswap. I have been trying to remove liquidity from a pool and have been getting error. Screenshot attached. 

Kindly help me with a resolution of the problem. My address is 0xfd818B81BeaEa57b84211fD1626bb0A3Ea6D3F78

**Comment by moodysalem** [comment]
Please reopen if this is still a problem, I am not able to reproduce
