### ISSUE TITLE
ChiperCore.chiperCoreBridgeError

### ISSUE THREAD

**Issue by vegterdevries** [Uniswap/uniswap-interface#975]
**Bug Description**
![image](https://user-images.githubusercontent.com/62606232/87865471-1f7f9400-c976-11ea-8612-c0ade2a8f702.png)

**Steps to Reproduce**
1.Go to uniswap interface trough coinbase wallet on iphone
2.Swap eth with any erc20 token
3.Bug comes up , reading CipherCore CipherCoreBridge error

I just want to know what that means could any of you devs tell me? 
And how to fix this issue. I can not find anything about it online.

**Comment by moodysalem** [comment]
This looks like an issue with Coinbase Wallet. Have you tried contacting Coinbase for support?

**Comment by lauris121** [comment]
Did you find out how to fix it?
