### ISSUE TITLE
Request to add SWAP Token to my MetaMask

### ISSUE THREAD

**Issue by cborris** [Uniswap/uniswap-interface#978]
**Please provide the following information for your token.**

Token Address: 0xCC4304A31d09258b0029eA7FE63d032f52e44EFe
Token Name (from contract): TrustSwap Token
Token Decimals (from contract): 18
Token Symbol (from contract): 
![trustswap_32](https://user-images.githubusercontent.com/68545384/87935081-4cbc6700-ca88-11ea-9a28-93f5aa1a1af5.png)
Uniswap Exchange Address of Token: 0x7a250d5630b4cf539739df2c5dacb4c659f2488d

Link to the official homepage of token: https://trustswap.org
Link to CoinMarketCap or CoinGecko page of token: https://www.coingecko.com/en/coins/trustswap

Some tokens (e.g. BNB) do not work with Uniswap v1. In order to assess if your token works correctly, please complete small-value transactions of each of the types below, and submit the Etherscan transaction links for our review.
Test `addLiquidity` transaction: 
Test `swap` transaction: 
Test `removeLiquidity` transaction: 

Are you willing to add liquidity to the liquidity pool for this token? (Y/N): N
If so, how much liquidity are you willing to add?: 0

**Comment by callil** [comment]
There is no need to open this PR. You should add the token yourself to your wallet.

**Comment by callil** [comment]
It's related to how Metamask works - see here: https://discordapp.com/channels/597638925346930701/606886929094541313/734438057012494467
