### ISSUE TITLE
How could I connect to my ETH address in Uniswap with JavaScript

### ISSUE THREAD

**Issue by PokimLee** [Uniswap/uniswap-interface#985]
I can use the walletConnet connect Uniswap with Wallet

![image](https://user-images.githubusercontent.com/3247265/88045364-01d24a80-cb81-11ea-80d4-fafd1c43b71a.png)
But it's not enough for me, how could I connect to my ETH address in Uniswap with JavaScript. If this works,  the whole process will become more convenient and automatic

**Comment by moodysalem** [comment]
Ask this type of question in the developer discord channel
