### ISSUE TITLE
Uniswap lock liqidity

### ISSUE THREAD

**Issue by patsadow2** [Uniswap/uniswap-interface#992]
I was looking through the whole of internet and i cannot find how and where i can lock liquidity which prevent withdraws ?

And is there any way to check if some tokens have locked liquidity?

BR

**Comment by moodysalem** [comment]
The Uniswap Interface will not support "locking liquidity"

Locking liquidity does not protect swappers in any way. For example, a token creator can:
- mint token X
- deposit 1000 X and 1000 ETH into Uniswap
- lock liquidity of token X
- wait for people to buy X, pool has 900 X and 1100 ETH
- token creator mints more X, sells to pool, pool has 10000000 X and 0.1 ETH
- X is worthless, token creator took all ETH
