### ISSUE TITLE
Fail with error 'UniswapV2Router

### ISSUE THREAD

**Issue by Bild96** [Uniswap/uniswap-interface#997]
It's for the third time. Always ( losing ETH gas transactions for nothing !! ) 

Transaction Hash: 0x3dc600d8d6ad3a79e97624f7267d84aa2ad141983f3318dade698f750bc7761b

![Screenshot from 2020-07-22 22-57-45](https://user-images.githubusercontent.com/52472445/88228208-1d1b8380-cc6f-11ea-8c0e-bf45c775ab90.png)

I'm not sure if I'll use **uniswap** again or recommend it for anyone !

**Comment by haydenadams** [comment]
expired means the transaction took longer than 20 mins to execute (assuming you were using the default deadline) so it failed

This can be fixed by increasing your gas price 
https://metamask.zendesk.com/hc/en-us/articles/360015488771-How-to-Adjust-Gas-Price-and-Gas-Limit-

**Comment by Bild96** [comment]
It was a default setup ( didn't change the gas price after same fail error messages twice ) without getting swap result!

**Comment by haydenadams** [comment]
Yeah I understand all that. Sometimes metamask default gas price is too low and takes longer than 20 mins to complete which causes it to fail.

You can manually increase gas price to fast to guarantee execution or use another wallet (many use higher gas estimates)

**Comment by LuchoGil** [comment]
Did it work for you @Bild96?
Can you share me your experience?

**Comment by Bild96** [comment]
I didn't go through it again. Especially now with high etherum gas fees.

**Comment by alexx855** [comment]
Same problem here, all default values, new metamask account

![image](https://user-images.githubusercontent.com/1799851/114687774-ea1b9300-9cc8-11eb-82e4-2ec2fe311eb0.png)

So frustrating, since its my first experience with uniswap

**Comment by isti4github** [comment]
> I didn't go through it again. Especially now with high etherum gas fees.

Do you solve the issue? I am also working on same project.
